## Generated by tools/generate.nim - do not edit.
##
## Source:    Windows.winmd
## Namespace: Windows.AI
##
## Slot numbers are vtable indices. WinRT interfaces begin with
## IInspectable's six slots, so the first declared method is slot 6;
## delegates derive from IUnknown and begin at slot 3.
##
## Every method returns HRESULT and its declared return type becomes
## a trailing out-parameter.

import ../core
include ../abidef
export core
import ./types
export types

## Windows.AI.Actions.Hosting.IActionCatalog
const IID_IActionCatalog* = GUID(
    data1: 0xDBE7C537'u32, data2: 0x66EA'u16, data3: 0x5394'u16,
    data4: [0x90'u8, 0x85, 0x4F, 0xC1, 0x9D, 0x78, 0x37, 0x5C])
const Slot_IActionCatalog_GetAllActions* = 6
type Fn_IActionCatalog_GetAllActions* = proc(self: pointer, valueSize: ptr uint32, value: ptr ptr pointer): HRESULT {.abi.}
const Slot_IActionCatalog_add_Changed* = 7
type Fn_IActionCatalog_add_Changed* = proc(self: pointer, a1: pointer, value: ptr EventRegistrationToken): HRESULT {.abi.}
const Slot_IActionCatalog_remove_Changed* = 8
type Fn_IActionCatalog_remove_Changed* = proc(self: pointer, a1: EventRegistrationToken): HRESULT {.abi.}

## Windows.AI.Actions.Hosting.IActionCatalog2
const IID_IActionCatalog2* = GUID(
    data1: 0x370360B1'u32, data2: 0xA14B'u16, data3: 0x5EA8'u16,
    data4: [0xB6'u8, 0x11, 0xB5, 0xF7, 0x03, 0x42, 0xBA, 0x44])
const Slot_IActionCatalog2_GetActionsForInputs* = 6
type Fn_IActionCatalog2_GetActionsForInputs* = proc(self: pointer, a1Size: uint32, a1: ptr pointer, valueSize: ptr uint32, value: ptr ptr pointer): HRESULT {.abi.}
const Slot_IActionCatalog2_GetActionsForInputs2* = 7
type Fn_IActionCatalog2_GetActionsForInputs2* = proc(self: pointer, a1Size: uint32, a1: ptr pointer, a2: WindowId, valueSize: ptr uint32, value: ptr ptr pointer): HRESULT {.abi.}

## Windows.AI.Actions.Hosting.IActionCatalog3
const IID_IActionCatalog3* = GUID(
    data1: 0x2E05D518'u32, data2: 0x8680'u16, data3: 0x55D3'u16,
    data4: [0x82'u8, 0x0D, 0x26, 0x05, 0xAD, 0xB7, 0xD6, 0x2D])
const Slot_IActionCatalog3_GetActionsForCurrentApp* = 6
type Fn_IActionCatalog3_GetActionsForCurrentApp* = proc(self: pointer, valueSize: ptr uint32, value: ptr ptr pointer): HRESULT {.abi.}

## Windows.AI.Actions.Hosting.IActionDefinition
const IID_IActionDefinition* = GUID(
    data1: 0xFE766ADD'u32, data2: 0x924D'u16, data3: 0x5231'u16,
    data4: [0x85'u8, 0x5E, 0xDA, 0xC9, 0xE8, 0x2C, 0x7E, 0x6C])
const Slot_IActionDefinition_get_Id* = 6
type Fn_IActionDefinition_get_Id* = proc(self: pointer, value: ptr HSTRING): HRESULT {.abi.}
const Slot_IActionDefinition_get_Description* = 7
type Fn_IActionDefinition_get_Description* = proc(self: pointer, value: ptr HSTRING): HRESULT {.abi.}
const Slot_IActionDefinition_get_IconFullPath* = 8
type Fn_IActionDefinition_get_IconFullPath* = proc(self: pointer, value: ptr HSTRING): HRESULT {.abi.}
const Slot_IActionDefinition_get_PackageFamilyName* = 9
type Fn_IActionDefinition_get_PackageFamilyName* = proc(self: pointer, value: ptr HSTRING): HRESULT {.abi.}
const Slot_IActionDefinition_GetInputs* = 10
type Fn_IActionDefinition_GetInputs* = proc(self: pointer, valueSize: ptr uint32, value: ptr ptr pointer): HRESULT {.abi.}
const Slot_IActionDefinition_GetOutputs* = 11
type Fn_IActionDefinition_GetOutputs* = proc(self: pointer, valueSize: ptr uint32, value: ptr ptr pointer): HRESULT {.abi.}
const Slot_IActionDefinition_GetOverloads* = 12
type Fn_IActionDefinition_GetOverloads* = proc(self: pointer, valueSize: ptr uint32, value: ptr ptr pointer): HRESULT {.abi.}

## Windows.AI.Actions.Hosting.IActionDefinition2
const IID_IActionDefinition2* = GUID(
    data1: 0xC1F44733'u32, data2: 0xF563'u16, data3: 0x54E2'u16,
    data4: [0xBD'u8, 0x2B, 0xDC, 0x4C, 0x73, 0x20, 0x54, 0xCF])
const Slot_IActionDefinition2_get_DisplaysUI* = 6
type Fn_IActionDefinition2_get_DisplaysUI* = proc(self: pointer, value: ptr bool): HRESULT {.abi.}
const Slot_IActionDefinition2_get_UsesGenerativeAI* = 7
type Fn_IActionDefinition2_get_UsesGenerativeAI* = proc(self: pointer, value: ptr bool): HRESULT {.abi.}
const Slot_IActionDefinition2_get_SchemaVersion* = 8
type Fn_IActionDefinition2_get_SchemaVersion* = proc(self: pointer, value: ptr uint32): HRESULT {.abi.}

## Windows.AI.Actions.Hosting.IActionDefinition3
const IID_IActionDefinition3* = GUID(
    data1: 0x89C9A7E0'u32, data2: 0x4BFD'u16, data3: 0x55F4'u16,
    data4: [0x9E'u8, 0xED, 0xDC, 0xE2, 0x25, 0x01, 0x14, 0xFA])
const Slot_IActionDefinition3_get_PackageRelativeApplicationId* = 6
type Fn_IActionDefinition3_get_PackageRelativeApplicationId* = proc(self: pointer, value: ptr HSTRING): HRESULT {.abi.}

## Windows.AI.Actions.Hosting.IActionDefinition4
const IID_IActionDefinition4* = GUID(
    data1: 0x6DD91071'u32, data2: 0x8847'u16, data3: 0x55B6'u16,
    data4: [0x95'u8, 0x18, 0x9F, 0xF8, 0xDE, 0x42, 0x1E, 0xB7])
const Slot_IActionDefinition4_get_IsCurrentlyAvailable* = 6
type Fn_IActionDefinition4_get_IsCurrentlyAvailable* = proc(self: pointer, value: ptr bool): HRESULT {.abi.}

## Windows.AI.Actions.Hosting.IActionDefinition5
const IID_IActionDefinition5* = GUID(
    data1: 0x5BEA33EF'u32, data2: 0xD325'u16, data3: 0x53A8'u16,
    data4: [0x8D'u8, 0xB3, 0x0D, 0x77, 0x1F, 0x4D, 0x1E, 0x54])
const Slot_IActionDefinition5_GetIconFullPath* = 6
type Fn_IActionDefinition5_GetIconFullPath* = proc(self: pointer, a1PropertySet: pointer, value: ptr HSTRING): HRESULT {.abi.}

## Windows.AI.Actions.Hosting.IActionEntityRegistrationInfo
const IID_IActionEntityRegistrationInfo* = GUID(
    data1: 0xC3B92BDB'u32, data2: 0x03C3'u16, data3: 0x5A9E'u16,
    data4: [0xB0'u8, 0x49, 0x00, 0x2F, 0xA0, 0x40, 0x56, 0x99])
const Slot_IActionEntityRegistrationInfo_get_Name* = 6
type Fn_IActionEntityRegistrationInfo_get_Name* = proc(self: pointer, value: ptr HSTRING): HRESULT {.abi.}
const Slot_IActionEntityRegistrationInfo_put_Name* = 7
type Fn_IActionEntityRegistrationInfo_put_Name* = proc(self: pointer, a1: HSTRING): HRESULT {.abi.}
const Slot_IActionEntityRegistrationInfo_get_Kind* = 8
type Fn_IActionEntityRegistrationInfo_get_Kind* = proc(self: pointer, value: ptr ActionEntityKind): HRESULT {.abi.}
const Slot_IActionEntityRegistrationInfo_put_Kind* = 9
type Fn_IActionEntityRegistrationInfo_put_Kind* = proc(self: pointer, a1: ActionEntityKind): HRESULT {.abi.}

## Windows.AI.Actions.Hosting.IActionInstance
const IID_IActionInstance* = GUID(
    data1: 0x809BCB6E'u32, data2: 0xE6EF'u16, data3: 0x5F16'u16,
    data4: [0xB8'u8, 0x9A, 0x06, 0xB8, 0x89, 0x3D, 0xF2, 0x0E])
const Slot_IActionInstance_get_DisplayInfo* = 6
type Fn_IActionInstance_get_DisplayInfo* = proc(self: pointer, value: ptr pointer): HRESULT {.abi.}
const Slot_IActionInstance_get_Definition* = 7
type Fn_IActionInstance_get_Definition* = proc(self: pointer, value: ptr pointer): HRESULT {.abi.}
const Slot_IActionInstance_get_Context* = 8
type Fn_IActionInstance_get_Context* = proc(self: pointer, value: ptr pointer): HRESULT {.abi.}
const Slot_IActionInstance_InvokeAsync* = 9
type Fn_IActionInstance_InvokeAsync* = proc(self: pointer, value: ptr pointer): HRESULT {.abi.}

## Windows.AI.Actions.Hosting.IActionInstanceDisplayInfo
const IID_IActionInstanceDisplayInfo* = GUID(
    data1: 0xFCFDCE21'u32, data2: 0x678B'u16, data3: 0x5602'u16,
    data4: [0xB9'u8, 0xDC, 0x2F, 0x45, 0x33, 0xA6, 0xF4, 0xB2])
const Slot_IActionInstanceDisplayInfo_get_Description* = 6
type Fn_IActionInstanceDisplayInfo_get_Description* = proc(self: pointer, value: ptr HSTRING): HRESULT {.abi.}

## Windows.AI.Actions.Hosting.IActionOverload
const IID_IActionOverload* = GUID(
    data1: 0x5D184610'u32, data2: 0xD09D'u16, data3: 0x5375'u16,
    data4: [0x98'u8, 0x49, 0x50, 0x5C, 0x35, 0x9D, 0xCA, 0x01])
const Slot_IActionOverload_get_DescriptionTemplate* = 6
type Fn_IActionOverload_get_DescriptionTemplate* = proc(self: pointer, value: ptr HSTRING): HRESULT {.abi.}
const Slot_IActionOverload_GetInputs* = 7
type Fn_IActionOverload_GetInputs* = proc(self: pointer, valueSize: ptr uint32, value: ptr ptr pointer): HRESULT {.abi.}
const Slot_IActionOverload_InvokeAsync* = 8
type Fn_IActionOverload_InvokeAsync* = proc(self: pointer, a1ActionInvocationContext: pointer, value: ptr pointer): HRESULT {.abi.}

## Windows.AI.Actions.Hosting.IActionOverload2
const IID_IActionOverload2* = GUID(
    data1: 0x57EC9906'u32, data2: 0x8231'u16, data3: 0x5A9E'u16,
    data4: [0x92'u8, 0x9F, 0xBF, 0x39, 0xE9, 0x52, 0xEB, 0x93])
const Slot_IActionOverload2_InvokeFeedbackAsync* = 6
type Fn_IActionOverload2_InvokeFeedbackAsync* = proc(self: pointer, a1ActionInvocationContext: pointer, a2ActionFeedback: pointer, value: ptr pointer): HRESULT {.abi.}
const Slot_IActionOverload2_GetSupportsFeedback* = 7
type Fn_IActionOverload2_GetSupportsFeedback* = proc(self: pointer, value: ptr bool): HRESULT {.abi.}

## Windows.AI.Actions.IActionEntity
const IID_IActionEntity* = GUID(
    data1: 0x445E700F'u32, data2: 0x2122'u16, data3: 0x5668'u16,
    data4: [0x9A'u8, 0x16, 0x4C, 0xAB, 0x29, 0x82, 0xC5, 0xF4])
const Slot_IActionEntity_get_Kind* = 6
type Fn_IActionEntity_get_Kind* = proc(self: pointer, value: ptr ActionEntityKind): HRESULT {.abi.}
const Slot_IActionEntity_get_DisplayInfo* = 7
type Fn_IActionEntity_get_DisplayInfo* = proc(self: pointer, value: ptr pointer): HRESULT {.abi.}

## Windows.AI.Actions.IActionEntity2
const IID_IActionEntity2* = GUID(
    data1: 0x98FE136D'u32, data2: 0xDD3A'u16, data3: 0x58C1'u16,
    data4: [0xAF'u8, 0x76, 0xFE, 0xB4, 0xE1, 0x9D, 0xCE, 0x9E])
const Slot_IActionEntity2_get_Id* = 6
type Fn_IActionEntity2_get_Id* = proc(self: pointer, value: ptr HSTRING): HRESULT {.abi.}

## Windows.AI.Actions.IActionEntityDisplayInfo
const IID_IActionEntityDisplayInfo* = GUID(
    data1: 0x057A9EDE'u32, data2: 0x03E1'u16, data3: 0x55C6'u16,
    data4: [0xAC'u8, 0xBA, 0xC7, 0x05, 0x62, 0x16, 0x73, 0x5A])
const Slot_IActionEntityDisplayInfo_get_Title* = 6
type Fn_IActionEntityDisplayInfo_get_Title* = proc(self: pointer, value: ptr HSTRING): HRESULT {.abi.}

## Windows.AI.Actions.IActionEntityFactory
const IID_IActionEntityFactory* = GUID(
    data1: 0x9CB752A0'u32, data2: 0x5BF8'u16, data3: 0x5BE2'u16,
    data4: [0x91'u8, 0x6E, 0xB0, 0x0E, 0xFF, 0x80, 0x08, 0x8D])

## Windows.AI.Actions.IActionEntityFactory2
const IID_IActionEntityFactory2* = GUID(
    data1: 0xEA2FB6A5'u32, data2: 0xEC6D'u16, data3: 0x5180'u16,
    data4: [0x9D'u8, 0x30, 0xBC, 0x66, 0x3B, 0x84, 0xE7, 0xB8])
const Slot_IActionEntityFactory2_CreateFileEntity* = 6
type Fn_IActionEntityFactory2_CreateFileEntity* = proc(self: pointer, a1: HSTRING, value: ptr pointer): HRESULT {.abi.}
const Slot_IActionEntityFactory2_CreateDocumentEntity* = 7
type Fn_IActionEntityFactory2_CreateDocumentEntity* = proc(self: pointer, a1: HSTRING, value: ptr pointer): HRESULT {.abi.}
const Slot_IActionEntityFactory2_CreatePhotoEntity* = 8
type Fn_IActionEntityFactory2_CreatePhotoEntity* = proc(self: pointer, a1: HSTRING, value: ptr pointer): HRESULT {.abi.}
const Slot_IActionEntityFactory2_CreateTextEntity* = 9
type Fn_IActionEntityFactory2_CreateTextEntity* = proc(self: pointer, a1: HSTRING, value: ptr pointer): HRESULT {.abi.}

## Windows.AI.Actions.IActionEntityFactory3
const IID_IActionEntityFactory3* = GUID(
    data1: 0x4910E689'u32, data2: 0x00B5'u16, data3: 0x56BB'u16,
    data4: [0x9C'u8, 0x65, 0x0F, 0xCC, 0x76, 0x21, 0x52, 0x83])
const Slot_IActionEntityFactory3_CreateRemoteFileEntity* = 6
type Fn_IActionEntityFactory3_CreateRemoteFileEntity* = proc(self: pointer, a1: HSTRING, a2: RemoteFileKind, a3Uri: pointer, a4: HSTRING, a5: HSTRING, a6: HSTRING, a7: HSTRING, a8: HSTRING, value: ptr pointer): HRESULT {.abi.}
const Slot_IActionEntityFactory3_CreateTextEntity* = 7
type Fn_IActionEntityFactory3_CreateTextEntity* = proc(self: pointer, a1: HSTRING, a2: ActionEntityTextFormat, value: ptr pointer): HRESULT {.abi.}
const Slot_IActionEntityFactory3_CreateStreamingTextActionEntityWriter* = 8
type Fn_IActionEntityFactory3_CreateStreamingTextActionEntityWriter* = proc(self: pointer, a1: ActionEntityTextFormat, value: ptr pointer): HRESULT {.abi.}

## Windows.AI.Actions.IActionEntityFactory4
const IID_IActionEntityFactory4* = GUID(
    data1: 0x332EDA05'u32, data2: 0xDE0E'u16, data3: 0x5A58'u16,
    data4: [0xB3'u8, 0x18, 0xA2, 0xAD, 0x77, 0x1F, 0x01, 0x3D])
const Slot_IActionEntityFactory4_CreateTableEntity* = 6
type Fn_IActionEntityFactory4_CreateTableEntity* = proc(self: pointer, a1Size: uint32, a1: ptr HSTRING, a2: uint32, value: ptr pointer): HRESULT {.abi.}
const Slot_IActionEntityFactory4_CreateContactEntity* = 7
type Fn_IActionEntityFactory4_CreateContactEntity* = proc(self: pointer, a1Contact: pointer, value: ptr pointer): HRESULT {.abi.}

## Windows.AI.Actions.IActionEntityFactory5
const IID_IActionEntityFactory5* = GUID(
    data1: 0xB59FAAB1'u32, data2: 0xCFE4'u16, data3: 0x564A'u16,
    data4: [0xA5'u8, 0xBA, 0x53, 0xAD, 0x7F, 0xF6, 0xF9, 0x24])
const Slot_IActionEntityFactory5_CreateUriEntity* = 6
type Fn_IActionEntityFactory5_CreateUriEntity* = proc(self: pointer, a1Uri: pointer, value: ptr pointer): HRESULT {.abi.}
const Slot_IActionEntityFactory5_CreateArrayEntity* = 7
type Fn_IActionEntityFactory5_CreateArrayEntity* = proc(self: pointer, a1: ActionEntityKind, a2Size: uint32, a2: ptr pointer, value: ptr pointer): HRESULT {.abi.}

## Windows.AI.Actions.IActionEntityFactory6
const IID_IActionEntityFactory6* = GUID(
    data1: 0xDA7123DA'u32, data2: 0x5639'u16, data3: 0x590F'u16,
    data4: [0xA2'u8, 0xDB, 0xC3, 0xB5, 0xE2, 0x21, 0xF3, 0xB6])
const Slot_IActionEntityFactory6_CreateDateTimeEntity* = 6
type Fn_IActionEntityFactory6_CreateDateTimeEntity* = proc(self: pointer, a1: DateTime, value: ptr pointer): HRESULT {.abi.}
const Slot_IActionEntityFactory6_CreateAppointmentEntity* = 7
type Fn_IActionEntityFactory6_CreateAppointmentEntity* = proc(self: pointer, a1: HSTRING, a2Appointment: pointer, a3Size: uint32, a3: ptr pointer, value: ptr pointer): HRESULT {.abi.}

## Windows.AI.Actions.IActionEntityFactory7
const IID_IActionEntityFactory7* = GUID(
    data1: 0xB814B8D5'u32, data2: 0xC9B2'u16, data3: 0x51B5'u16,
    data4: [0xA3'u8, 0x42, 0x9F, 0xE0, 0x54, 0xD8, 0xA1, 0xEB])
const Slot_IActionEntityFactory7_CreateCustomTextEntity* = 6
type Fn_IActionEntityFactory7_CreateCustomTextEntity* = proc(self: pointer, a1: HSTRING, a2: HSTRING, a3: pointer, value: ptr pointer): HRESULT {.abi.}
const Slot_IActionEntityFactory7_CreateArrayEntityWithCustomKind* = 7
type Fn_IActionEntityFactory7_CreateArrayEntityWithCustomKind* = proc(self: pointer, a1: ActionEntityKind, a2: HSTRING, a3Size: uint32, a3: ptr pointer, value: ptr pointer): HRESULT {.abi.}

## Windows.AI.Actions.IActionEntityFactoryFactory
const IID_IActionEntityFactoryFactory* = GUID(
    data1: 0xC9147D8F'u32, data2: 0x88A0'u16, data3: 0x5EC0'u16,
    data4: [0xA5'u8, 0x64, 0x47, 0xE2, 0xA1, 0x08, 0x14, 0x12])

## Windows.AI.Actions.IActionFeedback
const IID_IActionFeedback* = GUID(
    data1: 0xA12EE7AB'u32, data2: 0x2454'u16, data3: 0x56C9'u16,
    data4: [0xBB'u8, 0xDF, 0xC0, 0x89, 0x45, 0x7F, 0xBC, 0x5E])
const Slot_IActionFeedback_get_FeedbackKind* = 6
type Fn_IActionFeedback_get_FeedbackKind* = proc(self: pointer, value: ptr ActionFeedbackKind): HRESULT {.abi.}

## Windows.AI.Actions.IActionInvocationContext
const IID_IActionInvocationContext* = GUID(
    data1: 0xC32B622E'u32, data2: 0x86E1'u16, data3: 0x5EBA'u16,
    data4: [0x96'u8, 0x61, 0x60, 0x59, 0x10, 0x10, 0x49, 0x78])
const Slot_IActionInvocationContext_get_EntityFactory* = 6
type Fn_IActionInvocationContext_get_EntityFactory* = proc(self: pointer, value: ptr pointer): HRESULT {.abi.}
const Slot_IActionInvocationContext_SetInputEntity* = 7
type Fn_IActionInvocationContext_SetInputEntity* = proc(self: pointer, a1: HSTRING, a2ActionEntity: pointer): HRESULT {.abi.}
const Slot_IActionInvocationContext_GetInputEntities* = 8
type Fn_IActionInvocationContext_GetInputEntities* = proc(self: pointer, valueSize: ptr uint32, value: ptr ptr pointer): HRESULT {.abi.}
const Slot_IActionInvocationContext_SetOutputEntity* = 9
type Fn_IActionInvocationContext_SetOutputEntity* = proc(self: pointer, a1: HSTRING, a2ActionEntity: pointer): HRESULT {.abi.}
const Slot_IActionInvocationContext_GetOutputEntities* = 10
type Fn_IActionInvocationContext_GetOutputEntities* = proc(self: pointer, valueSize: ptr uint32, value: ptr ptr pointer): HRESULT {.abi.}
const Slot_IActionInvocationContext_get_Result* = 11
type Fn_IActionInvocationContext_get_Result* = proc(self: pointer, value: ptr ActionInvocationResult): HRESULT {.abi.}
const Slot_IActionInvocationContext_put_Result* = 12
type Fn_IActionInvocationContext_put_Result* = proc(self: pointer, a1: ActionInvocationResult): HRESULT {.abi.}
const Slot_IActionInvocationContext_get_ExtendedError* = 13
type Fn_IActionInvocationContext_get_ExtendedError* = proc(self: pointer, value: ptr HRESULT): HRESULT {.abi.}
const Slot_IActionInvocationContext_put_ExtendedError* = 14
type Fn_IActionInvocationContext_put_ExtendedError* = proc(self: pointer, a1: HRESULT): HRESULT {.abi.}

## Windows.AI.Actions.IActionInvocationContext2
const IID_IActionInvocationContext2* = GUID(
    data1: 0x7C843086'u32, data2: 0x9279'u16, data3: 0x5BCD'u16,
    data4: [0x8F'u8, 0x2E, 0xD1, 0x51, 0x21, 0xE7, 0xA8, 0x27])
const Slot_IActionInvocationContext2_get_InvokerWindowId* = 6
type Fn_IActionInvocationContext2_get_InvokerWindowId* = proc(self: pointer, value: ptr WindowId): HRESULT {.abi.}
const Slot_IActionInvocationContext2_get_HelpDetails* = 7
type Fn_IActionInvocationContext2_get_HelpDetails* = proc(self: pointer, value: ptr pointer): HRESULT {.abi.}
const Slot_IActionInvocationContext2_get_ActionId* = 8
type Fn_IActionInvocationContext2_get_ActionId* = proc(self: pointer, value: ptr HSTRING): HRESULT {.abi.}
const Slot_IActionInvocationContext2_get_InvokerAppUserModelId* = 9
type Fn_IActionInvocationContext2_get_InvokerAppUserModelId* = proc(self: pointer, value: ptr HSTRING): HRESULT {.abi.}

## Windows.AI.Actions.IActionInvocationHelpDetails
const IID_IActionInvocationHelpDetails* = GUID(
    data1: 0x5430F272'u32, data2: 0x078F'u16, data3: 0x5722'u16,
    data4: [0x8F'u8, 0x7D, 0x90, 0xCF, 0x8D, 0xDD, 0x59, 0x5E])
const Slot_IActionInvocationHelpDetails_get_Kind* = 6
type Fn_IActionInvocationHelpDetails_get_Kind* = proc(self: pointer, value: ptr ActionInvocationHelpKind): HRESULT {.abi.}
const Slot_IActionInvocationHelpDetails_put_Kind* = 7
type Fn_IActionInvocationHelpDetails_put_Kind* = proc(self: pointer, a1: ActionInvocationHelpKind): HRESULT {.abi.}
const Slot_IActionInvocationHelpDetails_get_Title* = 8
type Fn_IActionInvocationHelpDetails_get_Title* = proc(self: pointer, value: ptr HSTRING): HRESULT {.abi.}
const Slot_IActionInvocationHelpDetails_put_Title* = 9
type Fn_IActionInvocationHelpDetails_put_Title* = proc(self: pointer, a1: HSTRING): HRESULT {.abi.}
const Slot_IActionInvocationHelpDetails_get_Description* = 10
type Fn_IActionInvocationHelpDetails_get_Description* = proc(self: pointer, value: ptr HSTRING): HRESULT {.abi.}
const Slot_IActionInvocationHelpDetails_put_Description* = 11
type Fn_IActionInvocationHelpDetails_put_Description* = proc(self: pointer, a1: HSTRING): HRESULT {.abi.}
const Slot_IActionInvocationHelpDetails_get_HelpUri* = 12
type Fn_IActionInvocationHelpDetails_get_HelpUri* = proc(self: pointer, value: ptr pointer): HRESULT {.abi.}
const Slot_IActionInvocationHelpDetails_put_HelpUri* = 13
type Fn_IActionInvocationHelpDetails_put_HelpUri* = proc(self: pointer, a1Uri: pointer): HRESULT {.abi.}
const Slot_IActionInvocationHelpDetails_get_HelpUriDescription* = 14
type Fn_IActionInvocationHelpDetails_get_HelpUriDescription* = proc(self: pointer, value: ptr HSTRING): HRESULT {.abi.}
const Slot_IActionInvocationHelpDetails_put_HelpUriDescription* = 15
type Fn_IActionInvocationHelpDetails_put_HelpUriDescription* = proc(self: pointer, a1: HSTRING): HRESULT {.abi.}

## Windows.AI.Actions.IActionInvocationHelpDetails2
const IID_IActionInvocationHelpDetails2* = GUID(
    data1: 0x307F6BA5'u32, data2: 0x5FDA'u16, data3: 0x59F1'u16,
    data4: [0x97'u8, 0x22, 0x18, 0x59, 0x80, 0x1A, 0xD5, 0x50])
const Slot_IActionInvocationHelpDetails2_add_Changed* = 6
type Fn_IActionInvocationHelpDetails2_add_Changed* = proc(self: pointer, a1: pointer, value: ptr EventRegistrationToken): HRESULT {.abi.}
const Slot_IActionInvocationHelpDetails2_remove_Changed* = 7
type Fn_IActionInvocationHelpDetails2_remove_Changed* = proc(self: pointer, a1: EventRegistrationToken): HRESULT {.abi.}

## Windows.AI.Actions.IActionRuntime
const IID_IActionRuntime* = GUID(
    data1: 0x206EFA2C'u32, data2: 0xC909'u16, data3: 0x508A'u16,
    data4: [0xB4'u8, 0xB0, 0x94, 0x82, 0xBE, 0x96, 0xDB, 0x9C])
const Slot_IActionRuntime_get_ActionCatalog* = 6
type Fn_IActionRuntime_get_ActionCatalog* = proc(self: pointer, value: ptr pointer): HRESULT {.abi.}
const Slot_IActionRuntime_get_EntityFactory* = 7
type Fn_IActionRuntime_get_EntityFactory* = proc(self: pointer, value: ptr pointer): HRESULT {.abi.}
const Slot_IActionRuntime_CreateInvocationContext* = 8
type Fn_IActionRuntime_CreateInvocationContext* = proc(self: pointer, a1: HSTRING, value: ptr pointer): HRESULT {.abi.}

## Windows.AI.Actions.IActionRuntime2
const IID_IActionRuntime2* = GUID(
    data1: 0x2DA4D2C0'u32, data2: 0xE593'u16, data3: 0x5350'u16,
    data4: [0x81'u8, 0x43, 0x15, 0xBB, 0x24, 0xF6, 0x34, 0x11])
const Slot_IActionRuntime2_CreateActionFeedback* = 6
type Fn_IActionRuntime2_CreateActionFeedback* = proc(self: pointer, a1: ActionFeedbackKind, value: ptr pointer): HRESULT {.abi.}
const Slot_IActionRuntime2_SetActionAvailability* = 7
type Fn_IActionRuntime2_SetActionAvailability* = proc(self: pointer, a1: HSTRING, a2: bool): HRESULT {.abi.}
const Slot_IActionRuntime2_GetActionAvailability* = 8
type Fn_IActionRuntime2_GetActionAvailability* = proc(self: pointer, a1: HSTRING, value: ptr bool): HRESULT {.abi.}

## Windows.AI.Actions.IActionRuntime3
const IID_IActionRuntime3* = GUID(
    data1: 0xF020C3C0'u32, data2: 0xCAEC'u16, data3: 0x5928'u16,
    data4: [0xAD'u8, 0x00, 0x81, 0x06, 0x9B, 0x80, 0xFB, 0xC1])
const Slot_IActionRuntime3_CreateInvocationContextWithWindowId* = 6
type Fn_IActionRuntime3_CreateInvocationContextWithWindowId* = proc(self: pointer, a1: HSTRING, a2: WindowId, value: ptr pointer): HRESULT {.abi.}
const Slot_IActionRuntime3_GetActionEntityById* = 7
type Fn_IActionRuntime3_GetActionEntityById* = proc(self: pointer, a1: HSTRING, value: ptr pointer): HRESULT {.abi.}
const Slot_IActionRuntime3_get_LatestSupportedSchemaVersion* = 8
type Fn_IActionRuntime3_get_LatestSupportedSchemaVersion* = proc(self: pointer, value: ptr uint32): HRESULT {.abi.}

## Windows.AI.Actions.IActionRuntime4
const IID_IActionRuntime4* = GUID(
    data1: 0x06851DCD'u32, data2: 0xC743'u16, data3: 0x5C7F'u16,
    data4: [0x88'u8, 0xA1, 0xBB, 0xAE, 0xB0, 0x2F, 0x5E, 0x28])
const Slot_IActionRuntime4_GetActionInvocationContextFromToken* = 6
type Fn_IActionRuntime4_GetActionInvocationContextFromToken* = proc(self: pointer, a1: HSTRING, value: ptr pointer): HRESULT {.abi.}

## Windows.AI.Actions.IActionRuntime5
const IID_IActionRuntime5* = GUID(
    data1: 0xC2E995B1'u32, data2: 0x52A9'u16, data3: 0x5F3A'u16,
    data4: [0xBE'u8, 0xBB, 0xA0, 0x46, 0x55, 0xE9, 0x62, 0x18])
const Slot_IActionRuntime5_get_CustomEntityStore* = 6
type Fn_IActionRuntime5_get_CustomEntityStore* = proc(self: pointer, value: ptr pointer): HRESULT {.abi.}

## Windows.AI.Actions.IActionRuntimeFactory
const IID_IActionRuntimeFactory* = GUID(
    data1: 0xD3F366E9'u32, data2: 0x8DC9'u16, data3: 0x50A0'u16,
    data4: [0x80'u8, 0x40, 0xE5, 0xC1, 0x4F, 0xA6, 0x09, 0xD6])

## Windows.AI.Actions.IActionRuntimeStatics
const IID_IActionRuntimeStatics* = GUID(
    data1: 0x2C697AAB'u32, data2: 0x55F2'u16, data3: 0x55AA'u16,
    data4: [0x9D'u8, 0x63, 0xA7, 0x3E, 0xC1, 0x90, 0xCE, 0xCD])
const Slot_IActionRuntimeStatics_GetDefault* = 6
type Fn_IActionRuntimeStatics_GetDefault* = proc(self: pointer, value: ptr pointer): HRESULT {.abi.}

## Windows.AI.Actions.IAppointmentActionEntity
const IID_IAppointmentActionEntity* = GUID(
    data1: 0x29DAA00E'u32, data2: 0xB474'u16, data3: 0x581C'u16,
    data4: [0xB5'u8, 0x55, 0x61, 0x87, 0xD1, 0xAA, 0x82, 0x31])
const Slot_IAppointmentActionEntity_get_SourceId* = 6
type Fn_IAppointmentActionEntity_get_SourceId* = proc(self: pointer, value: ptr HSTRING): HRESULT {.abi.}
const Slot_IAppointmentActionEntity_get_Appointment* = 7
type Fn_IAppointmentActionEntity_get_Appointment* = proc(self: pointer, value: ptr pointer): HRESULT {.abi.}
const Slot_IAppointmentActionEntity_GetAttendees* = 8
type Fn_IAppointmentActionEntity_GetAttendees* = proc(self: pointer, valueSize: ptr uint32, value: ptr ptr pointer): HRESULT {.abi.}
const Slot_IAppointmentActionEntity_GetPresentedFiles* = 9
type Fn_IAppointmentActionEntity_GetPresentedFiles* = proc(self: pointer, valueSize: ptr uint32, value: ptr ptr pointer): HRESULT {.abi.}
const Slot_IAppointmentActionEntity_SetPresentedFiles* = 10
type Fn_IAppointmentActionEntity_SetPresentedFiles* = proc(self: pointer, a1Size: uint32, a1: ptr pointer): HRESULT {.abi.}
const Slot_IAppointmentActionEntity_GetSharedFiles* = 11
type Fn_IAppointmentActionEntity_GetSharedFiles* = proc(self: pointer, valueSize: ptr uint32, value: ptr ptr pointer): HRESULT {.abi.}
const Slot_IAppointmentActionEntity_SetSharedFiles* = 12
type Fn_IAppointmentActionEntity_SetSharedFiles* = proc(self: pointer, a1Size: uint32, a1: ptr pointer): HRESULT {.abi.}

## Windows.AI.Actions.IArrayActionEntity
const IID_IArrayActionEntity* = GUID(
    data1: 0x45798E78'u32, data2: 0x1059'u16, data3: 0x5311'u16,
    data4: [0x8A'u8, 0x1B, 0xDE, 0x00, 0x81, 0xA4, 0xCA, 0x3B])
const Slot_IArrayActionEntity_get_ElementKind* = 6
type Fn_IArrayActionEntity_get_ElementKind* = proc(self: pointer, value: ptr ActionEntityKind): HRESULT {.abi.}
const Slot_IArrayActionEntity_GetAll* = 7
type Fn_IArrayActionEntity_GetAll* = proc(self: pointer, valueSize: ptr uint32, value: ptr ptr pointer): HRESULT {.abi.}

## Windows.AI.Actions.IArrayActionEntity2
const IID_IArrayActionEntity2* = GUID(
    data1: 0x7366E049'u32, data2: 0x7FE8'u16, data3: 0x5DF9'u16,
    data4: [0xBB'u8, 0xCA, 0xCE, 0xA5, 0xC0, 0xF3, 0xD3, 0x16])
const Slot_IArrayActionEntity2_get_CustomElementKind* = 6
type Fn_IArrayActionEntity2_get_CustomElementKind* = proc(self: pointer, value: ptr HSTRING): HRESULT {.abi.}

## Windows.AI.Actions.IContactActionEntity
const IID_IContactActionEntity* = GUID(
    data1: 0x458C3E07'u32, data2: 0x5892'u16, data3: 0x5485'u16,
    data4: [0xBD'u8, 0x9B, 0x8F, 0x7A, 0x54, 0x0C, 0x95, 0x01])
const Slot_IContactActionEntity_get_Contact* = 6
type Fn_IContactActionEntity_get_Contact* = proc(self: pointer, value: ptr pointer): HRESULT {.abi.}

## Windows.AI.Actions.ICustomActionEntityStore
const IID_ICustomActionEntityStore* = GUID(
    data1: 0xFA7B44D0'u32, data2: 0x1762'u16, data3: 0x5828'u16,
    data4: [0x99'u8, 0x38, 0xE7, 0xCA, 0xE5, 0x19, 0x9E, 0x01])
const Slot_ICustomActionEntityStore_GetLastModifiedTime* = 6
type Fn_ICustomActionEntityStore_GetLastModifiedTime* = proc(self: pointer, a1: HSTRING, value: ptr DateTime): HRESULT {.abi.}
const Slot_ICustomActionEntityStore_Insert* = 7
type Fn_ICustomActionEntityStore_Insert* = proc(self: pointer, a1CustomTextActionEntity: pointer): HRESULT {.abi.}
const Slot_ICustomActionEntityStore_InsertMany* = 8
type Fn_ICustomActionEntityStore_InsertMany* = proc(self: pointer, a1Size: uint32, a1: ptr pointer): HRESULT {.abi.}
const Slot_ICustomActionEntityStore_Delete* = 9
type Fn_ICustomActionEntityStore_Delete* = proc(self: pointer, a1: HSTRING): HRESULT {.abi.}

## Windows.AI.Actions.ICustomActionEntityStoreFactory
const IID_ICustomActionEntityStoreFactory* = GUID(
    data1: 0xD8B46BDB'u32, data2: 0x68A5'u16, data3: 0x5E07'u16,
    data4: [0x91'u8, 0x13, 0xAB, 0xB9, 0x24, 0x1A, 0xAA, 0xB1])

## Windows.AI.Actions.ICustomTextActionEntity
const IID_ICustomTextActionEntity* = GUID(
    data1: 0x50EAAC95'u32, data2: 0x1D6C'u16, data3: 0x54B0'u16,
    data4: [0x89'u8, 0x63, 0xE3, 0x8D, 0xEA, 0x3F, 0x6A, 0xEC])
const Slot_ICustomTextActionEntity_get_CustomTextKind* = 6
type Fn_ICustomTextActionEntity_get_CustomTextKind* = proc(self: pointer, value: ptr HSTRING): HRESULT {.abi.}
const Slot_ICustomTextActionEntity_get_KeyPhrase* = 7
type Fn_ICustomTextActionEntity_get_KeyPhrase* = proc(self: pointer, value: ptr HSTRING): HRESULT {.abi.}
const Slot_ICustomTextActionEntity_get_Properties* = 8
type Fn_ICustomTextActionEntity_get_Properties* = proc(self: pointer, value: ptr pointer): HRESULT {.abi.}

## Windows.AI.Actions.IDateTimeActionEntity
const IID_IDateTimeActionEntity* = GUID(
    data1: 0xFD5A0880'u32, data2: 0xEEAE'u16, data3: 0x553A'u16,
    data4: [0xBF'u8, 0xED, 0xA9, 0x22, 0x9D, 0x57, 0x44, 0x7D])
const Slot_IDateTimeActionEntity_get_DateTime* = 6
type Fn_IDateTimeActionEntity_get_DateTime* = proc(self: pointer, value: ptr DateTime): HRESULT {.abi.}

## Windows.AI.Actions.IDocumentActionEntity
const IID_IDocumentActionEntity* = GUID(
    data1: 0x56715297'u32, data2: 0x960B'u16, data3: 0x59FF'u16,
    data4: [0xAF'u8, 0x4B, 0xEC, 0xE1, 0x09, 0x8B, 0x2E, 0x36])
const Slot_IDocumentActionEntity_get_FullPath* = 6
type Fn_IDocumentActionEntity_get_FullPath* = proc(self: pointer, value: ptr HSTRING): HRESULT {.abi.}

## Windows.AI.Actions.IFileActionEntity
const IID_IFileActionEntity* = GUID(
    data1: 0xF20AB43F'u32, data2: 0x4C80'u16, data3: 0x5904'u16,
    data4: [0xBD'u8, 0x42, 0x3E, 0x62, 0x48, 0xBA, 0xBF, 0xCF])
const Slot_IFileActionEntity_get_FullPath* = 6
type Fn_IFileActionEntity_get_FullPath* = proc(self: pointer, value: ptr HSTRING): HRESULT {.abi.}

## Windows.AI.Actions.INamedActionEntity
const IID_INamedActionEntity* = GUID(
    data1: 0x1AAEBEEF'u32, data2: 0x435B'u16, data3: 0x5A0D'u16,
    data4: [0x81'u8, 0x82, 0x05, 0xFE, 0x4D, 0xD4, 0x77, 0x12])
const Slot_INamedActionEntity_get_Name* = 6
type Fn_INamedActionEntity_get_Name* = proc(self: pointer, value: ptr HSTRING): HRESULT {.abi.}
const Slot_INamedActionEntity_put_Name* = 7
type Fn_INamedActionEntity_put_Name* = proc(self: pointer, a1: HSTRING): HRESULT {.abi.}
const Slot_INamedActionEntity_get_Entity* = 8
type Fn_INamedActionEntity_get_Entity* = proc(self: pointer, value: ptr pointer): HRESULT {.abi.}
const Slot_INamedActionEntity_put_Entity* = 9
type Fn_INamedActionEntity_put_Entity* = proc(self: pointer, a1ActionEntity: pointer): HRESULT {.abi.}

## Windows.AI.Actions.IPhotoActionEntity
const IID_IPhotoActionEntity* = GUID(
    data1: 0x425123B3'u32, data2: 0x20EF'u16, data3: 0x51A6'u16,
    data4: [0xB3'u8, 0x5F, 0x84, 0x14, 0x38, 0x47, 0x65, 0xC5])
const Slot_IPhotoActionEntity_get_FullPath* = 6
type Fn_IPhotoActionEntity_get_FullPath* = proc(self: pointer, value: ptr HSTRING): HRESULT {.abi.}

## Windows.AI.Actions.IRemoteFileActionEntity
const IID_IRemoteFileActionEntity* = GUID(
    data1: 0xA5D8EC21'u32, data2: 0xA2BD'u16, data3: 0x545A'u16,
    data4: [0xAB'u8, 0xFC, 0xD7, 0xAA, 0x79, 0xFD, 0x0B, 0x81])
const Slot_IRemoteFileActionEntity_get_SourceId* = 6
type Fn_IRemoteFileActionEntity_get_SourceId* = proc(self: pointer, value: ptr HSTRING): HRESULT {.abi.}
const Slot_IRemoteFileActionEntity_get_FileKind* = 7
type Fn_IRemoteFileActionEntity_get_FileKind* = proc(self: pointer, value: ptr RemoteFileKind): HRESULT {.abi.}
const Slot_IRemoteFileActionEntity_get_SourceUri* = 8
type Fn_IRemoteFileActionEntity_get_SourceUri* = proc(self: pointer, value: ptr pointer): HRESULT {.abi.}
const Slot_IRemoteFileActionEntity_get_FileId* = 9
type Fn_IRemoteFileActionEntity_get_FileId* = proc(self: pointer, value: ptr HSTRING): HRESULT {.abi.}
const Slot_IRemoteFileActionEntity_get_ContentType* = 10
type Fn_IRemoteFileActionEntity_get_ContentType* = proc(self: pointer, value: ptr HSTRING): HRESULT {.abi.}
const Slot_IRemoteFileActionEntity_get_DriveId* = 11
type Fn_IRemoteFileActionEntity_get_DriveId* = proc(self: pointer, value: ptr HSTRING): HRESULT {.abi.}
const Slot_IRemoteFileActionEntity_get_AccountId* = 12
type Fn_IRemoteFileActionEntity_get_AccountId* = proc(self: pointer, value: ptr HSTRING): HRESULT {.abi.}
const Slot_IRemoteFileActionEntity_get_Extension* = 13
type Fn_IRemoteFileActionEntity_get_Extension* = proc(self: pointer, value: ptr HSTRING): HRESULT {.abi.}

## Windows.AI.Actions.IRemoteFileActionEntity2
const IID_IRemoteFileActionEntity2* = GUID(
    data1: 0x9CC8CC54'u32, data2: 0x77D8'u16, data3: 0x5537'u16,
    data4: [0x83'u8, 0xC4, 0x6F, 0x18, 0xC1, 0xBC, 0x9F, 0x67])
const Slot_IRemoteFileActionEntity2_get_Filename* = 6
type Fn_IRemoteFileActionEntity2_get_Filename* = proc(self: pointer, value: ptr HSTRING): HRESULT {.abi.}
const Slot_IRemoteFileActionEntity2_put_Filename* = 7
type Fn_IRemoteFileActionEntity2_put_Filename* = proc(self: pointer, a1: HSTRING): HRESULT {.abi.}
const Slot_IRemoteFileActionEntity2_get_Creator* = 8
type Fn_IRemoteFileActionEntity2_get_Creator* = proc(self: pointer, value: ptr pointer): HRESULT {.abi.}
const Slot_IRemoteFileActionEntity2_put_Creator* = 9
type Fn_IRemoteFileActionEntity2_put_Creator* = proc(self: pointer, a1ContactActionEntity: pointer): HRESULT {.abi.}
const Slot_IRemoteFileActionEntity2_get_LastUpdatedTime* = 10
type Fn_IRemoteFileActionEntity2_get_LastUpdatedTime* = proc(self: pointer, value: ptr pointer): HRESULT {.abi.}
const Slot_IRemoteFileActionEntity2_put_LastUpdatedTime* = 11
type Fn_IRemoteFileActionEntity2_put_LastUpdatedTime* = proc(self: pointer, a1: pointer): HRESULT {.abi.}
const Slot_IRemoteFileActionEntity2_SetContributors* = 12
type Fn_IRemoteFileActionEntity2_SetContributors* = proc(self: pointer, a1Size: uint32, a1: ptr pointer): HRESULT {.abi.}
const Slot_IRemoteFileActionEntity2_GetContributors* = 13
type Fn_IRemoteFileActionEntity2_GetContributors* = proc(self: pointer, valueSize: ptr uint32, value: ptr ptr pointer): HRESULT {.abi.}

## Windows.AI.Actions.IStreamingTextActionEntity
const IID_IStreamingTextActionEntity* = GUID(
    data1: 0x44CD8A16'u32, data2: 0xABC9'u16, data3: 0x5703'u16,
    data4: [0xB4'u8, 0xBF, 0x6F, 0xE8, 0xB7, 0xA8, 0x02, 0xFD])
const Slot_IStreamingTextActionEntity_get_IsComplete* = 6
type Fn_IStreamingTextActionEntity_get_IsComplete* = proc(self: pointer, value: ptr bool): HRESULT {.abi.}
const Slot_IStreamingTextActionEntity_GetText* = 7
type Fn_IStreamingTextActionEntity_GetText* = proc(self: pointer, value: ptr HSTRING): HRESULT {.abi.}
const Slot_IStreamingTextActionEntity_get_TextFormat* = 8
type Fn_IStreamingTextActionEntity_get_TextFormat* = proc(self: pointer, value: ptr ActionEntityTextFormat): HRESULT {.abi.}
const Slot_IStreamingTextActionEntity_add_TextChanged* = 9
type Fn_IStreamingTextActionEntity_add_TextChanged* = proc(self: pointer, a1: pointer, value: ptr EventRegistrationToken): HRESULT {.abi.}
const Slot_IStreamingTextActionEntity_remove_TextChanged* = 10
type Fn_IStreamingTextActionEntity_remove_TextChanged* = proc(self: pointer, a1: EventRegistrationToken): HRESULT {.abi.}

## Windows.AI.Actions.IStreamingTextActionEntityTextChangedArgs
const IID_IStreamingTextActionEntityTextChangedArgs* = GUID(
    data1: 0x2C62011F'u32, data2: 0x3E06'u16, data3: 0x588B'u16,
    data4: [0xA3'u8, 0xBD, 0xD7, 0x26, 0xBD, 0x82, 0xFB, 0x13])
const Slot_IStreamingTextActionEntityTextChangedArgs_get_Text* = 6
type Fn_IStreamingTextActionEntityTextChangedArgs_get_Text* = proc(self: pointer, value: ptr HSTRING): HRESULT {.abi.}
const Slot_IStreamingTextActionEntityTextChangedArgs_get_IsComplete* = 7
type Fn_IStreamingTextActionEntityTextChangedArgs_get_IsComplete* = proc(self: pointer, value: ptr bool): HRESULT {.abi.}

## Windows.AI.Actions.IStreamingTextActionEntityWriter
const IID_IStreamingTextActionEntityWriter* = GUID(
    data1: 0x6BCE2F76'u32, data2: 0xA8AF'u16, data3: 0x5FF2'u16,
    data4: [0x83'u8, 0x3C, 0x10, 0x87, 0x37, 0xBA, 0x0F, 0x42])
const Slot_IStreamingTextActionEntityWriter_get_ReaderEntity* = 6
type Fn_IStreamingTextActionEntityWriter_get_ReaderEntity* = proc(self: pointer, value: ptr pointer): HRESULT {.abi.}
const Slot_IStreamingTextActionEntityWriter_get_TextFormat* = 7
type Fn_IStreamingTextActionEntityWriter_get_TextFormat* = proc(self: pointer, value: ptr ActionEntityTextFormat): HRESULT {.abi.}
const Slot_IStreamingTextActionEntityWriter_SetText* = 8
type Fn_IStreamingTextActionEntityWriter_SetText* = proc(self: pointer, a1: HSTRING): HRESULT {.abi.}

## Windows.AI.Actions.ITableActionEntity
const IID_ITableActionEntity* = GUID(
    data1: 0x0F252CDB'u32, data2: 0xBA24'u16, data3: 0x5DBB'u16,
    data4: [0x9D'u8, 0x17, 0x1B, 0x30, 0x07, 0x73, 0xD1, 0x41])
const Slot_ITableActionEntity_GetTextContent* = 6
type Fn_ITableActionEntity_GetTextContent* = proc(self: pointer, valueSize: ptr uint32, value: ptr ptr HSTRING): HRESULT {.abi.}
const Slot_ITableActionEntity_get_RowCount* = 7
type Fn_ITableActionEntity_get_RowCount* = proc(self: pointer, value: ptr uint32): HRESULT {.abi.}
const Slot_ITableActionEntity_get_ColumnCount* = 8
type Fn_ITableActionEntity_get_ColumnCount* = proc(self: pointer, value: ptr uint32): HRESULT {.abi.}

## Windows.AI.Actions.ITextActionEntity
const IID_ITextActionEntity* = GUID(
    data1: 0x3C4EC25F'u32, data2: 0x5ADB'u16, data3: 0x5F73'u16,
    data4: [0xB8'u8, 0xF3, 0x08, 0x0F, 0xBE, 0xAD, 0xD6, 0x12])
const Slot_ITextActionEntity_get_Text* = 6
type Fn_ITextActionEntity_get_Text* = proc(self: pointer, value: ptr HSTRING): HRESULT {.abi.}

## Windows.AI.Actions.ITextActionEntity2
const IID_ITextActionEntity2* = GUID(
    data1: 0x7C500889'u32, data2: 0xCF08'u16, data3: 0x51E7'u16,
    data4: [0xBE'u8, 0xCA, 0xF0, 0xBB, 0xC7, 0xA7, 0x48, 0x6C])
const Slot_ITextActionEntity2_get_TextFormat* = 6
type Fn_ITextActionEntity2_get_TextFormat* = proc(self: pointer, value: ptr ActionEntityTextFormat): HRESULT {.abi.}

## Windows.AI.Actions.IUriActionEntity
const IID_IUriActionEntity* = GUID(
    data1: 0xA81CDE77'u32, data2: 0xBC25'u16, data3: 0x532D'u16,
    data4: [0x90'u8, 0x5E, 0xB0, 0x72, 0x5C, 0x5B, 0xCD, 0x4E])
const Slot_IUriActionEntity_get_Uri* = 6
type Fn_IUriActionEntity_get_Uri* = proc(self: pointer, value: ptr pointer): HRESULT {.abi.}

## Windows.AI.Actions.Provider.IActionFeedbackHandler
const IID_IActionFeedbackHandler* = GUID(
    data1: 0xA3FC3C51'u32, data2: 0xA8C6'u16, data3: 0x52C8'u16,
    data4: [0xAD'u8, 0x77, 0x37, 0xBF, 0x3E, 0x2B, 0x56, 0x5C])
const Slot_IActionFeedbackHandler_ProcessFeedbackAsync* = 6
type Fn_IActionFeedbackHandler_ProcessFeedbackAsync* = proc(self: pointer, a1ActionInvocationContext: pointer, a2ActionFeedback: pointer, value: ptr pointer): HRESULT {.abi.}

## Windows.AI.Actions.Provider.IActionProvider
const IID_IActionProvider* = GUID(
    data1: 0x62906C47'u32, data2: 0x3D07'u16, data3: 0x55F1'u16,
    data4: [0xAE'u8, 0xFA, 0x15, 0x22, 0x50, 0x5A, 0xFB, 0xBE])
const Slot_IActionProvider_InvokeAsync* = 6
type Fn_IActionProvider_InvokeAsync* = proc(self: pointer, a1ActionInvocationContext: pointer, value: ptr pointer): HRESULT {.abi.}

## Windows.AI.Agents.Mcp.IMcpMessageFilterExperimental
const IID_IMcpMessageFilterExperimental* = GUID(
    data1: 0xC5F8F821'u32, data2: 0x895C'u16, data3: 0x5241'u16,
    data4: [0xB4'u8, 0x5A, 0x92, 0xE2, 0x49, 0xA7, 0xD8, 0x73])
const Slot_IMcpMessageFilterExperimental_Initialize* = 6
type Fn_IMcpMessageFilterExperimental_Initialize* = proc(self: pointer, a1: HSTRING, a2: uint32, a3: HSTRING, a4: HSTRING, a5: uint32): HRESULT {.abi.}
const Slot_IMcpMessageFilterExperimental_OnMessage* = 7
type Fn_IMcpMessageFilterExperimental_OnMessage* = proc(self: pointer, a1: HSTRING, a2: McpMessageDirection, a3McpMessageFilterResponse: pointer): HRESULT {.abi.}

## Windows.AI.Agents.Mcp.IMcpMessageFilterResponse
const IID_IMcpMessageFilterResponse* = GUID(
    data1: 0x363CE02C'u32, data2: 0x7098'u16, data3: 0x5E13'u16,
    data4: [0xA4'u8, 0x08, 0x7B, 0x43, 0xE1, 0xF4, 0x52, 0xAC])

## Windows.AI.Agents.Mcp.IMcpMessageFilterResponseExperimental
const IID_IMcpMessageFilterResponseExperimental* = GUID(
    data1: 0xE215B5F2'u32, data2: 0xCB02'u16, data3: 0x56CF'u16,
    data4: [0xAA'u8, 0xB0, 0x84, 0xAE, 0xF6, 0x5D, 0x16, 0x65])
const Slot_IMcpMessageFilterResponseExperimental_get_IsAllowed* = 6
type Fn_IMcpMessageFilterResponseExperimental_get_IsAllowed* = proc(self: pointer, value: ptr bool): HRESULT {.abi.}
const Slot_IMcpMessageFilterResponseExperimental_put_IsAllowed* = 7
type Fn_IMcpMessageFilterResponseExperimental_put_IsAllowed* = proc(self: pointer, a1: bool): HRESULT {.abi.}
const Slot_IMcpMessageFilterResponseExperimental_get_MessageIfNotAllowed* = 8
type Fn_IMcpMessageFilterResponseExperimental_get_MessageIfNotAllowed* = proc(self: pointer, value: ptr HSTRING): HRESULT {.abi.}
const Slot_IMcpMessageFilterResponseExperimental_put_MessageIfNotAllowed* = 9
type Fn_IMcpMessageFilterResponseExperimental_put_MessageIfNotAllowed* = proc(self: pointer, a1: HSTRING): HRESULT {.abi.}

## Windows.AI.Agents.Mcp.IMcpMessageFilterResponseExperimental2
const IID_IMcpMessageFilterResponseExperimental2* = GUID(
    data1: 0x10F4B099'u32, data2: 0x6632'u16, data3: 0x505A'u16,
    data4: [0xA6'u8, 0x38, 0xE7, 0x04, 0xC7, 0xE4, 0x7A, 0xBF])
const Slot_IMcpMessageFilterResponseExperimental2_Allow* = 6
type Fn_IMcpMessageFilterResponseExperimental2_Allow* = proc(self: pointer): HRESULT {.abi.}
const Slot_IMcpMessageFilterResponseExperimental2_Reject* = 7
type Fn_IMcpMessageFilterResponseExperimental2_Reject* = proc(self: pointer, a1: HSTRING): HRESULT {.abi.}

## Windows.AI.MachineLearning.IImageFeatureDescriptor
const IID_IImageFeatureDescriptor* = GUID(
    data1: 0x365585A5'u32, data2: 0x171A'u16, data3: 0x4A2A'u16,
    data4: [0x98'u8, 0x5F, 0x26, 0x51, 0x59, 0xD3, 0x89, 0x5A])
const Slot_IImageFeatureDescriptor_get_BitmapPixelFormat* = 6
type Fn_IImageFeatureDescriptor_get_BitmapPixelFormat* = proc(self: pointer, value: ptr BitmapPixelFormat): HRESULT {.abi.}
const Slot_IImageFeatureDescriptor_get_BitmapAlphaMode* = 7
type Fn_IImageFeatureDescriptor_get_BitmapAlphaMode* = proc(self: pointer, value: ptr BitmapAlphaMode): HRESULT {.abi.}
const Slot_IImageFeatureDescriptor_get_Width* = 8
type Fn_IImageFeatureDescriptor_get_Width* = proc(self: pointer, value: ptr uint32): HRESULT {.abi.}
const Slot_IImageFeatureDescriptor_get_Height* = 9
type Fn_IImageFeatureDescriptor_get_Height* = proc(self: pointer, value: ptr uint32): HRESULT {.abi.}

## Windows.AI.MachineLearning.IImageFeatureDescriptor2
const IID_IImageFeatureDescriptor2* = GUID(
    data1: 0x2B27CCA7'u32, data2: 0xD533'u16, data3: 0x5862'u16,
    data4: [0xBB'u8, 0x98, 0x16, 0x11, 0xB1, 0x55, 0xB0, 0xE1])
const Slot_IImageFeatureDescriptor2_get_PixelRange* = 6
type Fn_IImageFeatureDescriptor2_get_PixelRange* = proc(self: pointer, value: ptr LearningModelPixelRange): HRESULT {.abi.}

## Windows.AI.MachineLearning.IImageFeatureValue
const IID_IImageFeatureValue* = GUID(
    data1: 0xF0414FD9'u32, data2: 0xC9AA'u16, data3: 0x4405'u16,
    data4: [0xB7'u8, 0xFB, 0x94, 0xF8, 0x7C, 0x8A, 0x30, 0x37])
const Slot_IImageFeatureValue_get_VideoFrame* = 6
type Fn_IImageFeatureValue_get_VideoFrame* = proc(self: pointer, value: ptr pointer): HRESULT {.abi.}

## Windows.AI.MachineLearning.IImageFeatureValueStatics
const IID_IImageFeatureValueStatics* = GUID(
    data1: 0x1BC317FD'u32, data2: 0x23CB'u16, data3: 0x4610'u16,
    data4: [0xB0'u8, 0x85, 0xC8, 0xE1, 0xC8, 0x7E, 0xBA, 0xA0])
const Slot_IImageFeatureValueStatics_CreateFromVideoFrame* = 6
type Fn_IImageFeatureValueStatics_CreateFromVideoFrame* = proc(self: pointer, a1VideoFrame: pointer, value: ptr pointer): HRESULT {.abi.}

## Windows.AI.MachineLearning.ILearningModel
const IID_ILearningModel* = GUID(
    data1: 0x5B8E4920'u32, data2: 0x489F'u16, data3: 0x4E86'u16,
    data4: [0x91'u8, 0x28, 0x26, 0x5A, 0x32, 0x7B, 0x78, 0xFA])
const Slot_ILearningModel_get_Author* = 6
type Fn_ILearningModel_get_Author* = proc(self: pointer, value: ptr HSTRING): HRESULT {.abi.}
const Slot_ILearningModel_get_Name* = 7
type Fn_ILearningModel_get_Name* = proc(self: pointer, value: ptr HSTRING): HRESULT {.abi.}
const Slot_ILearningModel_get_Domain* = 8
type Fn_ILearningModel_get_Domain* = proc(self: pointer, value: ptr HSTRING): HRESULT {.abi.}
const Slot_ILearningModel_get_Description* = 9
type Fn_ILearningModel_get_Description* = proc(self: pointer, value: ptr HSTRING): HRESULT {.abi.}
const Slot_ILearningModel_get_Version* = 10
type Fn_ILearningModel_get_Version* = proc(self: pointer, value: ptr int64): HRESULT {.abi.}
const Slot_ILearningModel_get_Metadata* = 11
type Fn_ILearningModel_get_Metadata* = proc(self: pointer, value: ptr pointer): HRESULT {.abi.}
const Slot_ILearningModel_get_InputFeatures* = 12
type Fn_ILearningModel_get_InputFeatures* = proc(self: pointer, value: ptr pointer): HRESULT {.abi.}
const Slot_ILearningModel_get_OutputFeatures* = 13
type Fn_ILearningModel_get_OutputFeatures* = proc(self: pointer, value: ptr pointer): HRESULT {.abi.}

## Windows.AI.MachineLearning.ILearningModelBinding
const IID_ILearningModelBinding* = GUID(
    data1: 0xEA312F20'u32, data2: 0x168F'u16, data3: 0x4F8C'u16,
    data4: [0x94'u8, 0xFE, 0x2E, 0x7A, 0xC3, 0x1B, 0x4A, 0xA8])
const Slot_ILearningModelBinding_Bind* = 6
type Fn_ILearningModelBinding_Bind* = proc(self: pointer, a1: HSTRING, a2: pointer): HRESULT {.abi.}
const Slot_ILearningModelBinding_Bind2* = 7
type Fn_ILearningModelBinding_Bind2* = proc(self: pointer, a1: HSTRING, a2: pointer, a3IPropertySet: pointer): HRESULT {.abi.}
const Slot_ILearningModelBinding_Clear* = 8
type Fn_ILearningModelBinding_Clear* = proc(self: pointer): HRESULT {.abi.}

## Windows.AI.MachineLearning.ILearningModelBindingFactory
const IID_ILearningModelBindingFactory* = GUID(
    data1: 0xC95F7A7A'u32, data2: 0xE788'u16, data3: 0x475E'u16,
    data4: [0x89'u8, 0x17, 0x23, 0xAA, 0x38, 0x1F, 0xAF, 0x0B])
const Slot_ILearningModelBindingFactory_CreateFromSession* = 6
type Fn_ILearningModelBindingFactory_CreateFromSession* = proc(self: pointer, a1LearningModelSession: pointer, value: ptr pointer): HRESULT {.abi.}

## Windows.AI.MachineLearning.ILearningModelDevice
const IID_ILearningModelDevice* = GUID(
    data1: 0xF5C2C8FE'u32, data2: 0x3F56'u16, data3: 0x4A8C'u16,
    data4: [0xAC'u8, 0x5F, 0xFD, 0xB9, 0x2D, 0x8B, 0x82, 0x52])
const Slot_ILearningModelDevice_get_AdapterId* = 6
type Fn_ILearningModelDevice_get_AdapterId* = proc(self: pointer, value: ptr DisplayAdapterId): HRESULT {.abi.}
const Slot_ILearningModelDevice_get_Direct3D11Device* = 7
type Fn_ILearningModelDevice_get_Direct3D11Device* = proc(self: pointer, value: ptr pointer): HRESULT {.abi.}

## Windows.AI.MachineLearning.ILearningModelDeviceFactory
const IID_ILearningModelDeviceFactory* = GUID(
    data1: 0x9CFFD74D'u32, data2: 0xB1E5'u16, data3: 0x4F20'u16,
    data4: [0x80'u8, 0xAD, 0x0A, 0x56, 0x69, 0x0D, 0xB0, 0x6B])
const Slot_ILearningModelDeviceFactory_Create* = 6
type Fn_ILearningModelDeviceFactory_Create* = proc(self: pointer, a1: LearningModelDeviceKind, value: ptr pointer): HRESULT {.abi.}

## Windows.AI.MachineLearning.ILearningModelDeviceStatics
const IID_ILearningModelDeviceStatics* = GUID(
    data1: 0x49F32107'u32, data2: 0xA8BF'u16, data3: 0x42BB'u16,
    data4: [0x92'u8, 0xC7, 0x10, 0xB1, 0x2D, 0xC5, 0xD2, 0x1F])
const Slot_ILearningModelDeviceStatics_CreateFromDirect3D11Device* = 6
type Fn_ILearningModelDeviceStatics_CreateFromDirect3D11Device* = proc(self: pointer, a1IDirect3DDevice: pointer, value: ptr pointer): HRESULT {.abi.}

## Windows.AI.MachineLearning.ILearningModelEvaluationResult
const IID_ILearningModelEvaluationResult* = GUID(
    data1: 0xB2F9BFCD'u32, data2: 0x960E'u16, data3: 0x49C0'u16,
    data4: [0x85'u8, 0x93, 0xEB, 0x19, 0x0A, 0xE3, 0xEE, 0xE2])
const Slot_ILearningModelEvaluationResult_get_CorrelationId* = 6
type Fn_ILearningModelEvaluationResult_get_CorrelationId* = proc(self: pointer, value: ptr HSTRING): HRESULT {.abi.}
const Slot_ILearningModelEvaluationResult_get_ErrorStatus* = 7
type Fn_ILearningModelEvaluationResult_get_ErrorStatus* = proc(self: pointer, value: ptr int32): HRESULT {.abi.}
const Slot_ILearningModelEvaluationResult_get_Succeeded* = 8
type Fn_ILearningModelEvaluationResult_get_Succeeded* = proc(self: pointer, value: ptr bool): HRESULT {.abi.}
const Slot_ILearningModelEvaluationResult_get_Outputs* = 9
type Fn_ILearningModelEvaluationResult_get_Outputs* = proc(self: pointer, value: ptr pointer): HRESULT {.abi.}

## Windows.AI.MachineLearning.ILearningModelFeatureDescriptor
const IID_ILearningModelFeatureDescriptor* = GUID(
    data1: 0xBC08CF7C'u32, data2: 0x6ED0'u16, data3: 0x4004'u16,
    data4: [0x97'u8, 0xBA, 0xB9, 0xA2, 0xEE, 0xCD, 0x2B, 0x4F])
const Slot_ILearningModelFeatureDescriptor_get_Name* = 6
type Fn_ILearningModelFeatureDescriptor_get_Name* = proc(self: pointer, value: ptr HSTRING): HRESULT {.abi.}
const Slot_ILearningModelFeatureDescriptor_get_Description* = 7
type Fn_ILearningModelFeatureDescriptor_get_Description* = proc(self: pointer, value: ptr HSTRING): HRESULT {.abi.}
const Slot_ILearningModelFeatureDescriptor_get_Kind* = 8
type Fn_ILearningModelFeatureDescriptor_get_Kind* = proc(self: pointer, value: ptr LearningModelFeatureKind): HRESULT {.abi.}
const Slot_ILearningModelFeatureDescriptor_get_IsRequired* = 9
type Fn_ILearningModelFeatureDescriptor_get_IsRequired* = proc(self: pointer, value: ptr bool): HRESULT {.abi.}

## Windows.AI.MachineLearning.ILearningModelFeatureValue
const IID_ILearningModelFeatureValue* = GUID(
    data1: 0xF51005DB'u32, data2: 0x4085'u16, data3: 0x4DFE'u16,
    data4: [0x9F'u8, 0xED, 0x95, 0xEB, 0x0C, 0x0C, 0xF7, 0x5C])
const Slot_ILearningModelFeatureValue_get_Kind* = 6
type Fn_ILearningModelFeatureValue_get_Kind* = proc(self: pointer, value: ptr LearningModelFeatureKind): HRESULT {.abi.}

## Windows.AI.MachineLearning.ILearningModelOperatorProvider
const IID_ILearningModelOperatorProvider* = GUID(
    data1: 0x2A222E5D'u32, data2: 0xAFB1'u16, data3: 0x47ED'u16,
    data4: [0xBF'u8, 0xAD, 0xB5, 0xB3, 0xA4, 0x59, 0xEC, 0x04])

## Windows.AI.MachineLearning.ILearningModelSession
const IID_ILearningModelSession* = GUID(
    data1: 0x8E58F8F6'u32, data2: 0xB787'u16, data3: 0x4C11'u16,
    data4: [0x90'u8, 0xF0, 0x71, 0x29, 0xAE, 0xCA, 0x74, 0xA9])
const Slot_ILearningModelSession_get_Model* = 6
type Fn_ILearningModelSession_get_Model* = proc(self: pointer, value: ptr pointer): HRESULT {.abi.}
const Slot_ILearningModelSession_get_Device* = 7
type Fn_ILearningModelSession_get_Device* = proc(self: pointer, value: ptr pointer): HRESULT {.abi.}
const Slot_ILearningModelSession_get_EvaluationProperties* = 8
type Fn_ILearningModelSession_get_EvaluationProperties* = proc(self: pointer, value: ptr pointer): HRESULT {.abi.}
const Slot_ILearningModelSession_EvaluateAsync* = 9
type Fn_ILearningModelSession_EvaluateAsync* = proc(self: pointer, a1LearningModelBinding: pointer, a2: HSTRING, value: ptr pointer): HRESULT {.abi.}
const Slot_ILearningModelSession_EvaluateFeaturesAsync* = 10
type Fn_ILearningModelSession_EvaluateFeaturesAsync* = proc(self: pointer, a1: pointer, a2: HSTRING, value: ptr pointer): HRESULT {.abi.}
const Slot_ILearningModelSession_Evaluate* = 11
type Fn_ILearningModelSession_Evaluate* = proc(self: pointer, a1LearningModelBinding: pointer, a2: HSTRING, value: ptr pointer): HRESULT {.abi.}
const Slot_ILearningModelSession_EvaluateFeatures* = 12
type Fn_ILearningModelSession_EvaluateFeatures* = proc(self: pointer, a1: pointer, a2: HSTRING, value: ptr pointer): HRESULT {.abi.}

## Windows.AI.MachineLearning.ILearningModelSessionFactory
const IID_ILearningModelSessionFactory* = GUID(
    data1: 0x0F6B881D'u32, data2: 0x1C9B'u16, data3: 0x47B6'u16,
    data4: [0xBF'u8, 0xE0, 0xF1, 0xCF, 0x62, 0xA6, 0x75, 0x79])
const Slot_ILearningModelSessionFactory_CreateFromModel* = 6
type Fn_ILearningModelSessionFactory_CreateFromModel* = proc(self: pointer, a1LearningModel: pointer, value: ptr pointer): HRESULT {.abi.}
const Slot_ILearningModelSessionFactory_CreateFromModelOnDevice* = 7
type Fn_ILearningModelSessionFactory_CreateFromModelOnDevice* = proc(self: pointer, a1LearningModel: pointer, a2LearningModelDevice: pointer, value: ptr pointer): HRESULT {.abi.}

## Windows.AI.MachineLearning.ILearningModelSessionFactory2
const IID_ILearningModelSessionFactory2* = GUID(
    data1: 0x4E5C88BF'u32, data2: 0x0A1F'u16, data3: 0x5FEC'u16,
    data4: [0xAD'u8, 0xE0, 0x2F, 0xD9, 0x1E, 0x4E, 0xF2, 0x9B])
const Slot_ILearningModelSessionFactory2_CreateFromModelOnDeviceWithSessionOptions* = 6
type Fn_ILearningModelSessionFactory2_CreateFromModelOnDeviceWithSessionOptions* = proc(self: pointer, a1LearningModel: pointer, a2LearningModelDevice: pointer, a3LearningModelSessionOptions: pointer, value: ptr pointer): HRESULT {.abi.}

## Windows.AI.MachineLearning.ILearningModelSessionOptions
const IID_ILearningModelSessionOptions* = GUID(
    data1: 0xB8F63FA1'u32, data2: 0x134D'u16, data3: 0x5133'u16,
    data4: [0x8C'u8, 0xFF, 0x3A, 0x5C, 0x3C, 0x26, 0x3B, 0xEB])
const Slot_ILearningModelSessionOptions_get_BatchSizeOverride* = 6
type Fn_ILearningModelSessionOptions_get_BatchSizeOverride* = proc(self: pointer, value: ptr uint32): HRESULT {.abi.}
const Slot_ILearningModelSessionOptions_put_BatchSizeOverride* = 7
type Fn_ILearningModelSessionOptions_put_BatchSizeOverride* = proc(self: pointer, a1: uint32): HRESULT {.abi.}

## Windows.AI.MachineLearning.ILearningModelSessionOptions2
const IID_ILearningModelSessionOptions2* = GUID(
    data1: 0x6FCD1DC4'u32, data2: 0x175F'u16, data3: 0x5BD2'u16,
    data4: [0x8D'u8, 0xE5, 0x2F, 0x20, 0x06, 0xA2, 0x5A, 0xDF])
const Slot_ILearningModelSessionOptions2_get_CloseModelOnSessionCreation* = 6
type Fn_ILearningModelSessionOptions2_get_CloseModelOnSessionCreation* = proc(self: pointer, value: ptr bool): HRESULT {.abi.}
const Slot_ILearningModelSessionOptions2_put_CloseModelOnSessionCreation* = 7
type Fn_ILearningModelSessionOptions2_put_CloseModelOnSessionCreation* = proc(self: pointer, a1: bool): HRESULT {.abi.}

## Windows.AI.MachineLearning.ILearningModelSessionOptions3
const IID_ILearningModelSessionOptions3* = GUID(
    data1: 0x58E15CEE'u32, data2: 0xD8C2'u16, data3: 0x56FC'u16,
    data4: [0x92'u8, 0xE8, 0x76, 0xD7, 0x51, 0x08, 0x10, 0x86])
const Slot_ILearningModelSessionOptions3_OverrideNamedDimension* = 6
type Fn_ILearningModelSessionOptions3_OverrideNamedDimension* = proc(self: pointer, a1: HSTRING, a2: uint32): HRESULT {.abi.}

## Windows.AI.MachineLearning.ILearningModelStatics
const IID_ILearningModelStatics* = GUID(
    data1: 0xE3B977E8'u32, data2: 0x6952'u16, data3: 0x4E47'u16,
    data4: [0x8E'u8, 0xF4, 0x1F, 0x7F, 0x07, 0x89, 0x7C, 0x6D])
const Slot_ILearningModelStatics_LoadFromStorageFileAsync* = 6
type Fn_ILearningModelStatics_LoadFromStorageFileAsync* = proc(self: pointer, a1IStorageFile: pointer, value: ptr pointer): HRESULT {.abi.}
const Slot_ILearningModelStatics_LoadFromStreamAsync* = 7
type Fn_ILearningModelStatics_LoadFromStreamAsync* = proc(self: pointer, a1IRandomAccessStreamReference: pointer, value: ptr pointer): HRESULT {.abi.}
const Slot_ILearningModelStatics_LoadFromFilePath* = 8
type Fn_ILearningModelStatics_LoadFromFilePath* = proc(self: pointer, a1: HSTRING, value: ptr pointer): HRESULT {.abi.}
const Slot_ILearningModelStatics_LoadFromStream* = 9
type Fn_ILearningModelStatics_LoadFromStream* = proc(self: pointer, a1IRandomAccessStreamReference: pointer, value: ptr pointer): HRESULT {.abi.}
const Slot_ILearningModelStatics_LoadFromStorageFileAsync2* = 10
type Fn_ILearningModelStatics_LoadFromStorageFileAsync2* = proc(self: pointer, a1IStorageFile: pointer, a2ILearningModelOperatorProvider: pointer, value: ptr pointer): HRESULT {.abi.}
const Slot_ILearningModelStatics_LoadFromStreamAsync2* = 11
type Fn_ILearningModelStatics_LoadFromStreamAsync2* = proc(self: pointer, a1IRandomAccessStreamReference: pointer, a2ILearningModelOperatorProvider: pointer, value: ptr pointer): HRESULT {.abi.}
const Slot_ILearningModelStatics_LoadFromFilePath2* = 12
type Fn_ILearningModelStatics_LoadFromFilePath2* = proc(self: pointer, a1: HSTRING, a2ILearningModelOperatorProvider: pointer, value: ptr pointer): HRESULT {.abi.}
const Slot_ILearningModelStatics_LoadFromStream2* = 13
type Fn_ILearningModelStatics_LoadFromStream2* = proc(self: pointer, a1IRandomAccessStreamReference: pointer, a2ILearningModelOperatorProvider: pointer, value: ptr pointer): HRESULT {.abi.}

## Windows.AI.MachineLearning.IMapFeatureDescriptor
const IID_IMapFeatureDescriptor* = GUID(
    data1: 0x530424BD'u32, data2: 0xA257'u16, data3: 0x436D'u16,
    data4: [0x9E'u8, 0x60, 0xC2, 0x98, 0x1F, 0x7C, 0xC5, 0xC4])
const Slot_IMapFeatureDescriptor_get_KeyKind* = 6
type Fn_IMapFeatureDescriptor_get_KeyKind* = proc(self: pointer, value: ptr TensorKind): HRESULT {.abi.}
const Slot_IMapFeatureDescriptor_get_ValueDescriptor* = 7
type Fn_IMapFeatureDescriptor_get_ValueDescriptor* = proc(self: pointer, value: ptr pointer): HRESULT {.abi.}

## Windows.AI.MachineLearning.ISequenceFeatureDescriptor
const IID_ISequenceFeatureDescriptor* = GUID(
    data1: 0x84F6945A'u32, data2: 0x562B'u16, data3: 0x4D62'u16,
    data4: [0xA8'u8, 0x51, 0x73, 0x9A, 0xCE, 0xD9, 0x66, 0x68])
const Slot_ISequenceFeatureDescriptor_get_ElementDescriptor* = 6
type Fn_ISequenceFeatureDescriptor_get_ElementDescriptor* = proc(self: pointer, value: ptr pointer): HRESULT {.abi.}

## Windows.AI.MachineLearning.ITensor
const IID_ITensor* = GUID(
    data1: 0x05489593'u32, data2: 0xA305'u16, data3: 0x4A25'u16,
    data4: [0xAD'u8, 0x09, 0x44, 0x01, 0x19, 0xB4, 0xB7, 0xF6])
const Slot_ITensor_get_TensorKind* = 6
type Fn_ITensor_get_TensorKind* = proc(self: pointer, value: ptr TensorKind): HRESULT {.abi.}
const Slot_ITensor_get_Shape* = 7
type Fn_ITensor_get_Shape* = proc(self: pointer, value: ptr pointer): HRESULT {.abi.}

## Windows.AI.MachineLearning.ITensorBoolean
const IID_ITensorBoolean* = GUID(
    data1: 0x50F311ED'u32, data2: 0x29E9'u16, data3: 0x4A5C'u16,
    data4: [0xA4'u8, 0x4D, 0x8F, 0xC5, 0x12, 0x58, 0x4E, 0xED])
const Slot_ITensorBoolean_GetAsVectorView* = 6
type Fn_ITensorBoolean_GetAsVectorView* = proc(self: pointer, value: ptr pointer): HRESULT {.abi.}

## Windows.AI.MachineLearning.ITensorBooleanStatics
const IID_ITensorBooleanStatics* = GUID(
    data1: 0x2796862C'u32, data2: 0x2357'u16, data3: 0x49A7'u16,
    data4: [0xB4'u8, 0x76, 0xD0, 0xAA, 0x3D, 0xFE, 0x68, 0x66])
const Slot_ITensorBooleanStatics_Create* = 6
type Fn_ITensorBooleanStatics_Create* = proc(self: pointer, value: ptr pointer): HRESULT {.abi.}
const Slot_ITensorBooleanStatics_Create2* = 7
type Fn_ITensorBooleanStatics_Create2* = proc(self: pointer, a1: pointer, value: ptr pointer): HRESULT {.abi.}
const Slot_ITensorBooleanStatics_CreateFromArray* = 8
type Fn_ITensorBooleanStatics_CreateFromArray* = proc(self: pointer, a1: pointer, a2Size: uint32, a2: ptr bool, value: ptr pointer): HRESULT {.abi.}
const Slot_ITensorBooleanStatics_CreateFromIterable* = 9
type Fn_ITensorBooleanStatics_CreateFromIterable* = proc(self: pointer, a1: pointer, a2: pointer, value: ptr pointer): HRESULT {.abi.}

## Windows.AI.MachineLearning.ITensorBooleanStatics2
const IID_ITensorBooleanStatics2* = GUID(
    data1: 0xA3A4A501'u32, data2: 0x6A2D'u16, data3: 0x52D7'u16,
    data4: [0xB0'u8, 0x4B, 0xC4, 0x35, 0xBA, 0xEE, 0x01, 0x15])
const Slot_ITensorBooleanStatics2_CreateFromShapeArrayAndDataArray* = 6
type Fn_ITensorBooleanStatics2_CreateFromShapeArrayAndDataArray* = proc(self: pointer, a1Size: uint32, a1: ptr int64, a2Size: uint32, a2: ptr bool, value: ptr pointer): HRESULT {.abi.}
const Slot_ITensorBooleanStatics2_CreateFromBuffer* = 7
type Fn_ITensorBooleanStatics2_CreateFromBuffer* = proc(self: pointer, a1Size: uint32, a1: ptr int64, a2IBuffer: pointer, value: ptr pointer): HRESULT {.abi.}

## Windows.AI.MachineLearning.ITensorDouble
const IID_ITensorDouble* = GUID(
    data1: 0x91E41252'u32, data2: 0x7A8F'u16, data3: 0x4F0E'u16,
    data4: [0xA2'u8, 0x8F, 0x96, 0x37, 0xFF, 0xC8, 0xA3, 0xD0])
const Slot_ITensorDouble_GetAsVectorView* = 6
type Fn_ITensorDouble_GetAsVectorView* = proc(self: pointer, value: ptr pointer): HRESULT {.abi.}

## Windows.AI.MachineLearning.ITensorDoubleStatics
const IID_ITensorDoubleStatics* = GUID(
    data1: 0xA86693C5'u32, data2: 0x9538'u16, data3: 0x44E7'u16,
    data4: [0xA3'u8, 0xCA, 0x5D, 0xF3, 0x74, 0xA5, 0xA7, 0x0C])
const Slot_ITensorDoubleStatics_Create* = 6
type Fn_ITensorDoubleStatics_Create* = proc(self: pointer, value: ptr pointer): HRESULT {.abi.}
const Slot_ITensorDoubleStatics_Create2* = 7
type Fn_ITensorDoubleStatics_Create2* = proc(self: pointer, a1: pointer, value: ptr pointer): HRESULT {.abi.}
const Slot_ITensorDoubleStatics_CreateFromArray* = 8
type Fn_ITensorDoubleStatics_CreateFromArray* = proc(self: pointer, a1: pointer, a2Size: uint32, a2: ptr float64, value: ptr pointer): HRESULT {.abi.}
const Slot_ITensorDoubleStatics_CreateFromIterable* = 9
type Fn_ITensorDoubleStatics_CreateFromIterable* = proc(self: pointer, a1: pointer, a2: pointer, value: ptr pointer): HRESULT {.abi.}

## Windows.AI.MachineLearning.ITensorDoubleStatics2
const IID_ITensorDoubleStatics2* = GUID(
    data1: 0x93A570DE'u32, data2: 0x5E9A'u16, data3: 0x5094'u16,
    data4: [0x85'u8, 0xC8, 0x59, 0x2C, 0x65, 0x5E, 0x68, 0xAC])
const Slot_ITensorDoubleStatics2_CreateFromShapeArrayAndDataArray* = 6
type Fn_ITensorDoubleStatics2_CreateFromShapeArrayAndDataArray* = proc(self: pointer, a1Size: uint32, a1: ptr int64, a2Size: uint32, a2: ptr float64, value: ptr pointer): HRESULT {.abi.}
const Slot_ITensorDoubleStatics2_CreateFromBuffer* = 7
type Fn_ITensorDoubleStatics2_CreateFromBuffer* = proc(self: pointer, a1Size: uint32, a1: ptr int64, a2IBuffer: pointer, value: ptr pointer): HRESULT {.abi.}

## Windows.AI.MachineLearning.ITensorFeatureDescriptor
const IID_ITensorFeatureDescriptor* = GUID(
    data1: 0x74455C80'u32, data2: 0x946A'u16, data3: 0x4310'u16,
    data4: [0xA1'u8, 0x9C, 0xEE, 0x0A, 0xF0, 0x28, 0xFC, 0xE4])
const Slot_ITensorFeatureDescriptor_get_TensorKind* = 6
type Fn_ITensorFeatureDescriptor_get_TensorKind* = proc(self: pointer, value: ptr TensorKind): HRESULT {.abi.}
const Slot_ITensorFeatureDescriptor_get_Shape* = 7
type Fn_ITensorFeatureDescriptor_get_Shape* = proc(self: pointer, value: ptr pointer): HRESULT {.abi.}

## Windows.AI.MachineLearning.ITensorFloat
const IID_ITensorFloat* = GUID(
    data1: 0xF2282D82'u32, data2: 0xAA02'u16, data3: 0x42C8'u16,
    data4: [0xA0'u8, 0xC8, 0xDF, 0x1E, 0xFC, 0x96, 0x76, 0xE1])
const Slot_ITensorFloat_GetAsVectorView* = 6
type Fn_ITensorFloat_GetAsVectorView* = proc(self: pointer, value: ptr pointer): HRESULT {.abi.}

## Windows.AI.MachineLearning.ITensorFloat16Bit
const IID_ITensorFloat16Bit* = GUID(
    data1: 0x0AB994FC'u32, data2: 0x5B89'u16, data3: 0x4C3C'u16,
    data4: [0xB5'u8, 0xE4, 0x52, 0x82, 0xA5, 0x31, 0x6C, 0x0A])
const Slot_ITensorFloat16Bit_GetAsVectorView* = 6
type Fn_ITensorFloat16Bit_GetAsVectorView* = proc(self: pointer, value: ptr pointer): HRESULT {.abi.}

## Windows.AI.MachineLearning.ITensorFloat16BitStatics
const IID_ITensorFloat16BitStatics* = GUID(
    data1: 0xA52DB6F5'u32, data2: 0x318A'u16, data3: 0x44D4'u16,
    data4: [0x82'u8, 0x0B, 0x0C, 0xDC, 0x70, 0x54, 0xA8, 0x4A])
const Slot_ITensorFloat16BitStatics_Create* = 6
type Fn_ITensorFloat16BitStatics_Create* = proc(self: pointer, value: ptr pointer): HRESULT {.abi.}
const Slot_ITensorFloat16BitStatics_Create2* = 7
type Fn_ITensorFloat16BitStatics_Create2* = proc(self: pointer, a1: pointer, value: ptr pointer): HRESULT {.abi.}
const Slot_ITensorFloat16BitStatics_CreateFromArray* = 8
type Fn_ITensorFloat16BitStatics_CreateFromArray* = proc(self: pointer, a1: pointer, a2Size: uint32, a2: ptr float32, value: ptr pointer): HRESULT {.abi.}
const Slot_ITensorFloat16BitStatics_CreateFromIterable* = 9
type Fn_ITensorFloat16BitStatics_CreateFromIterable* = proc(self: pointer, a1: pointer, a2: pointer, value: ptr pointer): HRESULT {.abi.}

## Windows.AI.MachineLearning.ITensorFloat16BitStatics2
const IID_ITensorFloat16BitStatics2* = GUID(
    data1: 0x68545726'u32, data2: 0x2DC7'u16, data3: 0x51BF'u16,
    data4: [0xB4'u8, 0x70, 0x0B, 0x34, 0x4C, 0xC2, 0xA1, 0xBC])
const Slot_ITensorFloat16BitStatics2_CreateFromShapeArrayAndDataArray* = 6
type Fn_ITensorFloat16BitStatics2_CreateFromShapeArrayAndDataArray* = proc(self: pointer, a1Size: uint32, a1: ptr int64, a2Size: uint32, a2: ptr float32, value: ptr pointer): HRESULT {.abi.}
const Slot_ITensorFloat16BitStatics2_CreateFromBuffer* = 7
type Fn_ITensorFloat16BitStatics2_CreateFromBuffer* = proc(self: pointer, a1Size: uint32, a1: ptr int64, a2IBuffer: pointer, value: ptr pointer): HRESULT {.abi.}

## Windows.AI.MachineLearning.ITensorFloatStatics
const IID_ITensorFloatStatics* = GUID(
    data1: 0xDBCD395B'u32, data2: 0x3BA3'u16, data3: 0x452F'u16,
    data4: [0xB1'u8, 0x0D, 0x3C, 0x13, 0x5E, 0x57, 0x3F, 0xA9])
const Slot_ITensorFloatStatics_Create* = 6
type Fn_ITensorFloatStatics_Create* = proc(self: pointer, value: ptr pointer): HRESULT {.abi.}
const Slot_ITensorFloatStatics_Create2* = 7
type Fn_ITensorFloatStatics_Create2* = proc(self: pointer, a1: pointer, value: ptr pointer): HRESULT {.abi.}
const Slot_ITensorFloatStatics_CreateFromArray* = 8
type Fn_ITensorFloatStatics_CreateFromArray* = proc(self: pointer, a1: pointer, a2Size: uint32, a2: ptr float32, value: ptr pointer): HRESULT {.abi.}
const Slot_ITensorFloatStatics_CreateFromIterable* = 9
type Fn_ITensorFloatStatics_CreateFromIterable* = proc(self: pointer, a1: pointer, a2: pointer, value: ptr pointer): HRESULT {.abi.}

## Windows.AI.MachineLearning.ITensorFloatStatics2
const IID_ITensorFloatStatics2* = GUID(
    data1: 0x24610BC1'u32, data2: 0x5E44'u16, data3: 0x5713'u16,
    data4: [0xB2'u8, 0x81, 0x8F, 0x4A, 0xD4, 0xD5, 0x55, 0xE8])
const Slot_ITensorFloatStatics2_CreateFromShapeArrayAndDataArray* = 6
type Fn_ITensorFloatStatics2_CreateFromShapeArrayAndDataArray* = proc(self: pointer, a1Size: uint32, a1: ptr int64, a2Size: uint32, a2: ptr float32, value: ptr pointer): HRESULT {.abi.}
const Slot_ITensorFloatStatics2_CreateFromBuffer* = 7
type Fn_ITensorFloatStatics2_CreateFromBuffer* = proc(self: pointer, a1Size: uint32, a1: ptr int64, a2IBuffer: pointer, value: ptr pointer): HRESULT {.abi.}

## Windows.AI.MachineLearning.ITensorInt16Bit
const IID_ITensorInt16Bit* = GUID(
    data1: 0x98A32D39'u32, data2: 0xE6D6'u16, data3: 0x44AF'u16,
    data4: [0x8A'u8, 0xFA, 0xBA, 0xEB, 0xC4, 0x4D, 0xC0, 0x20])
const Slot_ITensorInt16Bit_GetAsVectorView* = 6
type Fn_ITensorInt16Bit_GetAsVectorView* = proc(self: pointer, value: ptr pointer): HRESULT {.abi.}

## Windows.AI.MachineLearning.ITensorInt16BitStatics
const IID_ITensorInt16BitStatics* = GUID(
    data1: 0x98646293'u32, data2: 0x266E'u16, data3: 0x4B1A'u16,
    data4: [0x82'u8, 0x1F, 0xE6, 0x0D, 0x70, 0x89, 0x8B, 0x91])
const Slot_ITensorInt16BitStatics_Create* = 6
type Fn_ITensorInt16BitStatics_Create* = proc(self: pointer, value: ptr pointer): HRESULT {.abi.}
const Slot_ITensorInt16BitStatics_Create2* = 7
type Fn_ITensorInt16BitStatics_Create2* = proc(self: pointer, a1: pointer, value: ptr pointer): HRESULT {.abi.}
const Slot_ITensorInt16BitStatics_CreateFromArray* = 8
type Fn_ITensorInt16BitStatics_CreateFromArray* = proc(self: pointer, a1: pointer, a2Size: uint32, a2: ptr int16, value: ptr pointer): HRESULT {.abi.}
const Slot_ITensorInt16BitStatics_CreateFromIterable* = 9
type Fn_ITensorInt16BitStatics_CreateFromIterable* = proc(self: pointer, a1: pointer, a2: pointer, value: ptr pointer): HRESULT {.abi.}

## Windows.AI.MachineLearning.ITensorInt16BitStatics2
const IID_ITensorInt16BitStatics2* = GUID(
    data1: 0x0CD70CF4'u32, data2: 0x696C'u16, data3: 0x5E5F'u16,
    data4: [0x95'u8, 0xD8, 0x5E, 0xBF, 0x96, 0x70, 0x14, 0x8B])
const Slot_ITensorInt16BitStatics2_CreateFromShapeArrayAndDataArray* = 6
type Fn_ITensorInt16BitStatics2_CreateFromShapeArrayAndDataArray* = proc(self: pointer, a1Size: uint32, a1: ptr int64, a2Size: uint32, a2: ptr int16, value: ptr pointer): HRESULT {.abi.}
const Slot_ITensorInt16BitStatics2_CreateFromBuffer* = 7
type Fn_ITensorInt16BitStatics2_CreateFromBuffer* = proc(self: pointer, a1Size: uint32, a1: ptr int64, a2IBuffer: pointer, value: ptr pointer): HRESULT {.abi.}

## Windows.AI.MachineLearning.ITensorInt32Bit
const IID_ITensorInt32Bit* = GUID(
    data1: 0x2C0C28D3'u32, data2: 0x207C'u16, data3: 0x4486'u16,
    data4: [0xA7'u8, 0xD2, 0x88, 0x45, 0x22, 0xC5, 0xE5, 0x89])
const Slot_ITensorInt32Bit_GetAsVectorView* = 6
type Fn_ITensorInt32Bit_GetAsVectorView* = proc(self: pointer, value: ptr pointer): HRESULT {.abi.}

## Windows.AI.MachineLearning.ITensorInt32BitStatics
const IID_ITensorInt32BitStatics* = GUID(
    data1: 0x6539864B'u32, data2: 0x52FA'u16, data3: 0x4E35'u16,
    data4: [0x90'u8, 0x7C, 0x83, 0x4C, 0xAC, 0x41, 0x7B, 0x50])
const Slot_ITensorInt32BitStatics_Create* = 6
type Fn_ITensorInt32BitStatics_Create* = proc(self: pointer, value: ptr pointer): HRESULT {.abi.}
const Slot_ITensorInt32BitStatics_Create2* = 7
type Fn_ITensorInt32BitStatics_Create2* = proc(self: pointer, a1: pointer, value: ptr pointer): HRESULT {.abi.}
const Slot_ITensorInt32BitStatics_CreateFromArray* = 8
type Fn_ITensorInt32BitStatics_CreateFromArray* = proc(self: pointer, a1: pointer, a2Size: uint32, a2: ptr int32, value: ptr pointer): HRESULT {.abi.}
const Slot_ITensorInt32BitStatics_CreateFromIterable* = 9
type Fn_ITensorInt32BitStatics_CreateFromIterable* = proc(self: pointer, a1: pointer, a2: pointer, value: ptr pointer): HRESULT {.abi.}

## Windows.AI.MachineLearning.ITensorInt32BitStatics2
const IID_ITensorInt32BitStatics2* = GUID(
    data1: 0x7C4B079A'u32, data2: 0xE956'u16, data3: 0x5CE0'u16,
    data4: [0xA3'u8, 0xBD, 0x15, 0x7D, 0x9D, 0x79, 0xB5, 0xEC])
const Slot_ITensorInt32BitStatics2_CreateFromShapeArrayAndDataArray* = 6
type Fn_ITensorInt32BitStatics2_CreateFromShapeArrayAndDataArray* = proc(self: pointer, a1Size: uint32, a1: ptr int64, a2Size: uint32, a2: ptr int32, value: ptr pointer): HRESULT {.abi.}
const Slot_ITensorInt32BitStatics2_CreateFromBuffer* = 7
type Fn_ITensorInt32BitStatics2_CreateFromBuffer* = proc(self: pointer, a1Size: uint32, a1: ptr int64, a2IBuffer: pointer, value: ptr pointer): HRESULT {.abi.}

## Windows.AI.MachineLearning.ITensorInt64Bit
const IID_ITensorInt64Bit* = GUID(
    data1: 0x499665BA'u32, data2: 0x1FA2'u16, data3: 0x45AD'u16,
    data4: [0xAF'u8, 0x25, 0xA0, 0xBD, 0x9B, 0xDA, 0x4C, 0x87])
const Slot_ITensorInt64Bit_GetAsVectorView* = 6
type Fn_ITensorInt64Bit_GetAsVectorView* = proc(self: pointer, value: ptr pointer): HRESULT {.abi.}

## Windows.AI.MachineLearning.ITensorInt64BitStatics
const IID_ITensorInt64BitStatics* = GUID(
    data1: 0x9648AD9D'u32, data2: 0x1198'u16, data3: 0x4D74'u16,
    data4: [0x95'u8, 0x17, 0x78, 0x3A, 0xB6, 0x2B, 0x9C, 0xC2])
const Slot_ITensorInt64BitStatics_Create* = 6
type Fn_ITensorInt64BitStatics_Create* = proc(self: pointer, value: ptr pointer): HRESULT {.abi.}
const Slot_ITensorInt64BitStatics_Create2* = 7
type Fn_ITensorInt64BitStatics_Create2* = proc(self: pointer, a1: pointer, value: ptr pointer): HRESULT {.abi.}
const Slot_ITensorInt64BitStatics_CreateFromArray* = 8
type Fn_ITensorInt64BitStatics_CreateFromArray* = proc(self: pointer, a1: pointer, a2Size: uint32, a2: ptr int64, value: ptr pointer): HRESULT {.abi.}
const Slot_ITensorInt64BitStatics_CreateFromIterable* = 9
type Fn_ITensorInt64BitStatics_CreateFromIterable* = proc(self: pointer, a1: pointer, a2: pointer, value: ptr pointer): HRESULT {.abi.}

## Windows.AI.MachineLearning.ITensorInt64BitStatics2
const IID_ITensorInt64BitStatics2* = GUID(
    data1: 0x6D3D9DCB'u32, data2: 0xFF40'u16, data3: 0x5EC2'u16,
    data4: [0x89'u8, 0xFE, 0x08, 0x4E, 0x2B, 0x6B, 0xC6, 0xDB])
const Slot_ITensorInt64BitStatics2_CreateFromShapeArrayAndDataArray* = 6
type Fn_ITensorInt64BitStatics2_CreateFromShapeArrayAndDataArray* = proc(self: pointer, a1Size: uint32, a1: ptr int64, a2Size: uint32, a2: ptr int64, value: ptr pointer): HRESULT {.abi.}
const Slot_ITensorInt64BitStatics2_CreateFromBuffer* = 7
type Fn_ITensorInt64BitStatics2_CreateFromBuffer* = proc(self: pointer, a1Size: uint32, a1: ptr int64, a2IBuffer: pointer, value: ptr pointer): HRESULT {.abi.}

## Windows.AI.MachineLearning.ITensorInt8Bit
const IID_ITensorInt8Bit* = GUID(
    data1: 0xCDDD97C5'u32, data2: 0xFFD8'u16, data3: 0x4FEF'u16,
    data4: [0xAE'u8, 0xFB, 0x30, 0xE1, 0xA4, 0x85, 0xB2, 0xEE])
const Slot_ITensorInt8Bit_GetAsVectorView* = 6
type Fn_ITensorInt8Bit_GetAsVectorView* = proc(self: pointer, value: ptr pointer): HRESULT {.abi.}

## Windows.AI.MachineLearning.ITensorInt8BitStatics
const IID_ITensorInt8BitStatics* = GUID(
    data1: 0xB1A12284'u32, data2: 0x095C'u16, data3: 0x4C76'u16,
    data4: [0xA6'u8, 0x61, 0xAC, 0x4C, 0xEE, 0x1F, 0x3E, 0x8B])
const Slot_ITensorInt8BitStatics_Create* = 6
type Fn_ITensorInt8BitStatics_Create* = proc(self: pointer, value: ptr pointer): HRESULT {.abi.}
const Slot_ITensorInt8BitStatics_Create2* = 7
type Fn_ITensorInt8BitStatics_Create2* = proc(self: pointer, a1: pointer, value: ptr pointer): HRESULT {.abi.}
const Slot_ITensorInt8BitStatics_CreateFromArray* = 8
type Fn_ITensorInt8BitStatics_CreateFromArray* = proc(self: pointer, a1: pointer, a2Size: uint32, a2: ptr uint8, value: ptr pointer): HRESULT {.abi.}
const Slot_ITensorInt8BitStatics_CreateFromIterable* = 9
type Fn_ITensorInt8BitStatics_CreateFromIterable* = proc(self: pointer, a1: pointer, a2: pointer, value: ptr pointer): HRESULT {.abi.}

## Windows.AI.MachineLearning.ITensorInt8BitStatics2
const IID_ITensorInt8BitStatics2* = GUID(
    data1: 0xC0D59637'u32, data2: 0xC468'u16, data3: 0x56FB'u16,
    data4: [0x95'u8, 0x35, 0xC0, 0x52, 0xBD, 0xB9, 0x3D, 0xC0])
const Slot_ITensorInt8BitStatics2_CreateFromShapeArrayAndDataArray* = 6
type Fn_ITensorInt8BitStatics2_CreateFromShapeArrayAndDataArray* = proc(self: pointer, a1Size: uint32, a1: ptr int64, a2Size: uint32, a2: ptr uint8, value: ptr pointer): HRESULT {.abi.}
const Slot_ITensorInt8BitStatics2_CreateFromBuffer* = 7
type Fn_ITensorInt8BitStatics2_CreateFromBuffer* = proc(self: pointer, a1Size: uint32, a1: ptr int64, a2IBuffer: pointer, value: ptr pointer): HRESULT {.abi.}

## Windows.AI.MachineLearning.ITensorString
const IID_ITensorString* = GUID(
    data1: 0x582335C8'u32, data2: 0xBDB1'u16, data3: 0x4610'u16,
    data4: [0xBC'u8, 0x75, 0x35, 0xE9, 0xCB, 0xF0, 0x09, 0xB7])
const Slot_ITensorString_GetAsVectorView* = 6
type Fn_ITensorString_GetAsVectorView* = proc(self: pointer, value: ptr pointer): HRESULT {.abi.}

## Windows.AI.MachineLearning.ITensorStringStatics
const IID_ITensorStringStatics* = GUID(
    data1: 0x83623324'u32, data2: 0xCF26'u16, data3: 0x4F17'u16,
    data4: [0xA2'u8, 0xD4, 0x20, 0xEF, 0x8D, 0x09, 0x7D, 0x53])
const Slot_ITensorStringStatics_Create* = 6
type Fn_ITensorStringStatics_Create* = proc(self: pointer, value: ptr pointer): HRESULT {.abi.}
const Slot_ITensorStringStatics_Create2* = 7
type Fn_ITensorStringStatics_Create2* = proc(self: pointer, a1: pointer, value: ptr pointer): HRESULT {.abi.}
const Slot_ITensorStringStatics_CreateFromArray* = 8
type Fn_ITensorStringStatics_CreateFromArray* = proc(self: pointer, a1: pointer, a2Size: uint32, a2: ptr HSTRING, value: ptr pointer): HRESULT {.abi.}
const Slot_ITensorStringStatics_CreateFromIterable* = 9
type Fn_ITensorStringStatics_CreateFromIterable* = proc(self: pointer, a1: pointer, a2: pointer, value: ptr pointer): HRESULT {.abi.}

## Windows.AI.MachineLearning.ITensorStringStatics2
const IID_ITensorStringStatics2* = GUID(
    data1: 0x9E355ED0'u32, data2: 0xC8E2'u16, data3: 0x5254'u16,
    data4: [0x91'u8, 0x37, 0x01, 0x93, 0xA3, 0x66, 0x8F, 0xD8])
const Slot_ITensorStringStatics2_CreateFromShapeArrayAndDataArray* = 6
type Fn_ITensorStringStatics2_CreateFromShapeArrayAndDataArray* = proc(self: pointer, a1Size: uint32, a1: ptr int64, a2Size: uint32, a2: ptr HSTRING, value: ptr pointer): HRESULT {.abi.}

## Windows.AI.MachineLearning.ITensorUInt16Bit
const IID_ITensorUInt16Bit* = GUID(
    data1: 0x68140F4B'u32, data2: 0x23C0'u16, data3: 0x42F3'u16,
    data4: [0x81'u8, 0xF6, 0xA8, 0x91, 0xC0, 0x11, 0xBC, 0x3F])
const Slot_ITensorUInt16Bit_GetAsVectorView* = 6
type Fn_ITensorUInt16Bit_GetAsVectorView* = proc(self: pointer, value: ptr pointer): HRESULT {.abi.}

## Windows.AI.MachineLearning.ITensorUInt16BitStatics
const IID_ITensorUInt16BitStatics* = GUID(
    data1: 0x5DF745DD'u32, data2: 0x028A'u16, data3: 0x481A'u16,
    data4: [0xA2'u8, 0x7C, 0xC7, 0xE6, 0x43, 0x5E, 0x52, 0xDD])
const Slot_ITensorUInt16BitStatics_Create* = 6
type Fn_ITensorUInt16BitStatics_Create* = proc(self: pointer, value: ptr pointer): HRESULT {.abi.}
const Slot_ITensorUInt16BitStatics_Create2* = 7
type Fn_ITensorUInt16BitStatics_Create2* = proc(self: pointer, a1: pointer, value: ptr pointer): HRESULT {.abi.}
const Slot_ITensorUInt16BitStatics_CreateFromArray* = 8
type Fn_ITensorUInt16BitStatics_CreateFromArray* = proc(self: pointer, a1: pointer, a2Size: uint32, a2: ptr uint16, value: ptr pointer): HRESULT {.abi.}
const Slot_ITensorUInt16BitStatics_CreateFromIterable* = 9
type Fn_ITensorUInt16BitStatics_CreateFromIterable* = proc(self: pointer, a1: pointer, a2: pointer, value: ptr pointer): HRESULT {.abi.}

## Windows.AI.MachineLearning.ITensorUInt16BitStatics2
const IID_ITensorUInt16BitStatics2* = GUID(
    data1: 0x8AF40C64'u32, data2: 0xD69F'u16, data3: 0x5315'u16,
    data4: [0x93'u8, 0x48, 0x49, 0x08, 0x77, 0xBB, 0xD6, 0x42])
const Slot_ITensorUInt16BitStatics2_CreateFromShapeArrayAndDataArray* = 6
type Fn_ITensorUInt16BitStatics2_CreateFromShapeArrayAndDataArray* = proc(self: pointer, a1Size: uint32, a1: ptr int64, a2Size: uint32, a2: ptr uint16, value: ptr pointer): HRESULT {.abi.}
const Slot_ITensorUInt16BitStatics2_CreateFromBuffer* = 7
type Fn_ITensorUInt16BitStatics2_CreateFromBuffer* = proc(self: pointer, a1Size: uint32, a1: ptr int64, a2IBuffer: pointer, value: ptr pointer): HRESULT {.abi.}

## Windows.AI.MachineLearning.ITensorUInt32Bit
const IID_ITensorUInt32Bit* = GUID(
    data1: 0xD8C9C2FF'u32, data2: 0x7511'u16, data3: 0x45A3'u16,
    data4: [0xBF'u8, 0xAC, 0xC3, 0x8F, 0x37, 0x0D, 0x22, 0x37])
const Slot_ITensorUInt32Bit_GetAsVectorView* = 6
type Fn_ITensorUInt32Bit_GetAsVectorView* = proc(self: pointer, value: ptr pointer): HRESULT {.abi.}

## Windows.AI.MachineLearning.ITensorUInt32BitStatics
const IID_ITensorUInt32BitStatics* = GUID(
    data1: 0x417C3837'u32, data2: 0xE773'u16, data3: 0x4378'u16,
    data4: [0x8E'u8, 0x7F, 0x0C, 0xC3, 0x3D, 0xBE, 0xA6, 0x97])
const Slot_ITensorUInt32BitStatics_Create* = 6
type Fn_ITensorUInt32BitStatics_Create* = proc(self: pointer, value: ptr pointer): HRESULT {.abi.}
const Slot_ITensorUInt32BitStatics_Create2* = 7
type Fn_ITensorUInt32BitStatics_Create2* = proc(self: pointer, a1: pointer, value: ptr pointer): HRESULT {.abi.}
const Slot_ITensorUInt32BitStatics_CreateFromArray* = 8
type Fn_ITensorUInt32BitStatics_CreateFromArray* = proc(self: pointer, a1: pointer, a2Size: uint32, a2: ptr uint32, value: ptr pointer): HRESULT {.abi.}
const Slot_ITensorUInt32BitStatics_CreateFromIterable* = 9
type Fn_ITensorUInt32BitStatics_CreateFromIterable* = proc(self: pointer, a1: pointer, a2: pointer, value: ptr pointer): HRESULT {.abi.}

## Windows.AI.MachineLearning.ITensorUInt32BitStatics2
const IID_ITensorUInt32BitStatics2* = GUID(
    data1: 0xEF1A1F1C'u32, data2: 0x314E'u16, data3: 0x569D'u16,
    data4: [0xB4'u8, 0x96, 0x5C, 0x84, 0x47, 0xD2, 0x0C, 0xD2])
const Slot_ITensorUInt32BitStatics2_CreateFromShapeArrayAndDataArray* = 6
type Fn_ITensorUInt32BitStatics2_CreateFromShapeArrayAndDataArray* = proc(self: pointer, a1Size: uint32, a1: ptr int64, a2Size: uint32, a2: ptr uint32, value: ptr pointer): HRESULT {.abi.}
const Slot_ITensorUInt32BitStatics2_CreateFromBuffer* = 7
type Fn_ITensorUInt32BitStatics2_CreateFromBuffer* = proc(self: pointer, a1Size: uint32, a1: ptr int64, a2IBuffer: pointer, value: ptr pointer): HRESULT {.abi.}

## Windows.AI.MachineLearning.ITensorUInt64Bit
const IID_ITensorUInt64Bit* = GUID(
    data1: 0x2E70FFAD'u32, data2: 0x04BF'u16, data3: 0x4825'u16,
    data4: [0x83'u8, 0x9A, 0x82, 0xBA, 0xEF, 0x8C, 0x78, 0x86])
const Slot_ITensorUInt64Bit_GetAsVectorView* = 6
type Fn_ITensorUInt64Bit_GetAsVectorView* = proc(self: pointer, value: ptr pointer): HRESULT {.abi.}

## Windows.AI.MachineLearning.ITensorUInt64BitStatics
const IID_ITensorUInt64BitStatics* = GUID(
    data1: 0x7A7E20EB'u32, data2: 0x242F'u16, data3: 0x47CB'u16,
    data4: [0xA9'u8, 0xC6, 0xF6, 0x02, 0xEC, 0xFB, 0xFE, 0xE4])
const Slot_ITensorUInt64BitStatics_Create* = 6
type Fn_ITensorUInt64BitStatics_Create* = proc(self: pointer, value: ptr pointer): HRESULT {.abi.}
const Slot_ITensorUInt64BitStatics_Create2* = 7
type Fn_ITensorUInt64BitStatics_Create2* = proc(self: pointer, a1: pointer, value: ptr pointer): HRESULT {.abi.}
const Slot_ITensorUInt64BitStatics_CreateFromArray* = 8
type Fn_ITensorUInt64BitStatics_CreateFromArray* = proc(self: pointer, a1: pointer, a2Size: uint32, a2: ptr uint64, value: ptr pointer): HRESULT {.abi.}
const Slot_ITensorUInt64BitStatics_CreateFromIterable* = 9
type Fn_ITensorUInt64BitStatics_CreateFromIterable* = proc(self: pointer, a1: pointer, a2: pointer, value: ptr pointer): HRESULT {.abi.}

## Windows.AI.MachineLearning.ITensorUInt64BitStatics2
const IID_ITensorUInt64BitStatics2* = GUID(
    data1: 0x085A687D'u32, data2: 0x67E1'u16, data3: 0x5B1E'u16,
    data4: [0xB2'u8, 0x32, 0x4F, 0xAB, 0xE9, 0xCA, 0x20, 0xB3])
const Slot_ITensorUInt64BitStatics2_CreateFromShapeArrayAndDataArray* = 6
type Fn_ITensorUInt64BitStatics2_CreateFromShapeArrayAndDataArray* = proc(self: pointer, a1Size: uint32, a1: ptr int64, a2Size: uint32, a2: ptr uint64, value: ptr pointer): HRESULT {.abi.}
const Slot_ITensorUInt64BitStatics2_CreateFromBuffer* = 7
type Fn_ITensorUInt64BitStatics2_CreateFromBuffer* = proc(self: pointer, a1Size: uint32, a1: ptr int64, a2IBuffer: pointer, value: ptr pointer): HRESULT {.abi.}

## Windows.AI.MachineLearning.ITensorUInt8Bit
const IID_ITensorUInt8Bit* = GUID(
    data1: 0x58E1AE27'u32, data2: 0x622B'u16, data3: 0x48E3'u16,
    data4: [0xBE'u8, 0x22, 0xD8, 0x67, 0xAE, 0xD1, 0xDA, 0xAC])
const Slot_ITensorUInt8Bit_GetAsVectorView* = 6
type Fn_ITensorUInt8Bit_GetAsVectorView* = proc(self: pointer, value: ptr pointer): HRESULT {.abi.}

## Windows.AI.MachineLearning.ITensorUInt8BitStatics
const IID_ITensorUInt8BitStatics* = GUID(
    data1: 0x05F67583'u32, data2: 0xBC24'u16, data3: 0x4220'u16,
    data4: [0x8A'u8, 0x41, 0x2D, 0xCD, 0x8C, 0x5E, 0xD3, 0x3C])
const Slot_ITensorUInt8BitStatics_Create* = 6
type Fn_ITensorUInt8BitStatics_Create* = proc(self: pointer, value: ptr pointer): HRESULT {.abi.}
const Slot_ITensorUInt8BitStatics_Create2* = 7
type Fn_ITensorUInt8BitStatics_Create2* = proc(self: pointer, a1: pointer, value: ptr pointer): HRESULT {.abi.}
const Slot_ITensorUInt8BitStatics_CreateFromArray* = 8
type Fn_ITensorUInt8BitStatics_CreateFromArray* = proc(self: pointer, a1: pointer, a2Size: uint32, a2: ptr uint8, value: ptr pointer): HRESULT {.abi.}
const Slot_ITensorUInt8BitStatics_CreateFromIterable* = 9
type Fn_ITensorUInt8BitStatics_CreateFromIterable* = proc(self: pointer, a1: pointer, a2: pointer, value: ptr pointer): HRESULT {.abi.}

## Windows.AI.MachineLearning.ITensorUInt8BitStatics2
const IID_ITensorUInt8BitStatics2* = GUID(
    data1: 0x2BA042D6'u32, data2: 0x373E'u16, data3: 0x5A3A'u16,
    data4: [0xA2'u8, 0xFC, 0xA6, 0xC4, 0x1B, 0xD5, 0x27, 0x89])
const Slot_ITensorUInt8BitStatics2_CreateFromShapeArrayAndDataArray* = 6
type Fn_ITensorUInt8BitStatics2_CreateFromShapeArrayAndDataArray* = proc(self: pointer, a1Size: uint32, a1: ptr int64, a2Size: uint32, a2: ptr uint8, value: ptr pointer): HRESULT {.abi.}
const Slot_ITensorUInt8BitStatics2_CreateFromBuffer* = 7
type Fn_ITensorUInt8BitStatics2_CreateFromBuffer* = proc(self: pointer, a1Size: uint32, a1: ptr int64, a2IBuffer: pointer, value: ptr pointer): HRESULT {.abi.}

## Windows.AI.MachineLearning.Preview.IImageVariableDescriptorPreview
const IID_IImageVariableDescriptorPreview* = GUID(
    data1: 0x7AE1FA72'u32, data2: 0x029E'u16, data3: 0x4DC5'u16,
    data4: [0xA2'u8, 0xF8, 0x5F, 0xB7, 0x63, 0x15, 0x41, 0x50])
const Slot_IImageVariableDescriptorPreview_get_BitmapPixelFormat* = 6
type Fn_IImageVariableDescriptorPreview_get_BitmapPixelFormat* = proc(self: pointer, value: ptr BitmapPixelFormat): HRESULT {.abi.}
const Slot_IImageVariableDescriptorPreview_get_Width* = 7
type Fn_IImageVariableDescriptorPreview_get_Width* = proc(self: pointer, value: ptr uint32): HRESULT {.abi.}
const Slot_IImageVariableDescriptorPreview_get_Height* = 8
type Fn_IImageVariableDescriptorPreview_get_Height* = proc(self: pointer, value: ptr uint32): HRESULT {.abi.}

## Windows.AI.MachineLearning.Preview.IInferencingOptionsPreview
const IID_IInferencingOptionsPreview* = GUID(
    data1: 0x47BC8205'u32, data2: 0x4D36'u16, data3: 0x47A9'u16,
    data4: [0x8F'u8, 0x68, 0xFF, 0xCB, 0x33, 0x9D, 0xD0, 0xFC])
const Slot_IInferencingOptionsPreview_get_PreferredDeviceKind* = 6
type Fn_IInferencingOptionsPreview_get_PreferredDeviceKind* = proc(self: pointer, value: ptr LearningModelDeviceKindPreview): HRESULT {.abi.}
const Slot_IInferencingOptionsPreview_put_PreferredDeviceKind* = 7
type Fn_IInferencingOptionsPreview_put_PreferredDeviceKind* = proc(self: pointer, a1: LearningModelDeviceKindPreview): HRESULT {.abi.}
const Slot_IInferencingOptionsPreview_get_IsTracingEnabled* = 8
type Fn_IInferencingOptionsPreview_get_IsTracingEnabled* = proc(self: pointer, value: ptr bool): HRESULT {.abi.}
const Slot_IInferencingOptionsPreview_put_IsTracingEnabled* = 9
type Fn_IInferencingOptionsPreview_put_IsTracingEnabled* = proc(self: pointer, a1: bool): HRESULT {.abi.}
const Slot_IInferencingOptionsPreview_get_MaxBatchSize* = 10
type Fn_IInferencingOptionsPreview_get_MaxBatchSize* = proc(self: pointer, value: ptr int32): HRESULT {.abi.}
const Slot_IInferencingOptionsPreview_put_MaxBatchSize* = 11
type Fn_IInferencingOptionsPreview_put_MaxBatchSize* = proc(self: pointer, a1: int32): HRESULT {.abi.}
const Slot_IInferencingOptionsPreview_get_MinimizeMemoryAllocation* = 12
type Fn_IInferencingOptionsPreview_get_MinimizeMemoryAllocation* = proc(self: pointer, value: ptr bool): HRESULT {.abi.}
const Slot_IInferencingOptionsPreview_put_MinimizeMemoryAllocation* = 13
type Fn_IInferencingOptionsPreview_put_MinimizeMemoryAllocation* = proc(self: pointer, a1: bool): HRESULT {.abi.}
const Slot_IInferencingOptionsPreview_get_ReclaimMemoryAfterEvaluation* = 14
type Fn_IInferencingOptionsPreview_get_ReclaimMemoryAfterEvaluation* = proc(self: pointer, value: ptr bool): HRESULT {.abi.}
const Slot_IInferencingOptionsPreview_put_ReclaimMemoryAfterEvaluation* = 15
type Fn_IInferencingOptionsPreview_put_ReclaimMemoryAfterEvaluation* = proc(self: pointer, a1: bool): HRESULT {.abi.}

## Windows.AI.MachineLearning.Preview.ILearningModelBindingPreview
const IID_ILearningModelBindingPreview* = GUID(
    data1: 0x93C901E8'u32, data2: 0x6C78'u16, data3: 0x4B4F'u16,
    data4: [0xAE'u8, 0xC1, 0xA6, 0xBB, 0x9E, 0x69, 0x16, 0x24])
const Slot_ILearningModelBindingPreview_Bind* = 6
type Fn_ILearningModelBindingPreview_Bind* = proc(self: pointer, a1: HSTRING, a2: pointer): HRESULT {.abi.}
const Slot_ILearningModelBindingPreview_Bind2* = 7
type Fn_ILearningModelBindingPreview_Bind2* = proc(self: pointer, a1: HSTRING, a2: pointer, a3IPropertySet: pointer): HRESULT {.abi.}
const Slot_ILearningModelBindingPreview_Clear* = 8
type Fn_ILearningModelBindingPreview_Clear* = proc(self: pointer): HRESULT {.abi.}

## Windows.AI.MachineLearning.Preview.ILearningModelBindingPreviewFactory
const IID_ILearningModelBindingPreviewFactory* = GUID(
    data1: 0x48B8219F'u32, data2: 0x1E51'u16, data3: 0x4D77'u16,
    data4: [0xAE'u8, 0x50, 0x3E, 0xC1, 0x64, 0xAD, 0x34, 0x80])
const Slot_ILearningModelBindingPreviewFactory_CreateFromModel* = 6
type Fn_ILearningModelBindingPreviewFactory_CreateFromModel* = proc(self: pointer, a1LearningModelPreview: pointer, value: ptr pointer): HRESULT {.abi.}

## Windows.AI.MachineLearning.Preview.ILearningModelDescriptionPreview
const IID_ILearningModelDescriptionPreview* = GUID(
    data1: 0xF52C09C6'u32, data2: 0x8611'u16, data3: 0x40AD'u16,
    data4: [0x8E'u8, 0x59, 0xDE, 0x3F, 0xD7, 0x03, 0x0A, 0x40])
const Slot_ILearningModelDescriptionPreview_get_Author* = 6
type Fn_ILearningModelDescriptionPreview_get_Author* = proc(self: pointer, value: ptr HSTRING): HRESULT {.abi.}
const Slot_ILearningModelDescriptionPreview_get_Name* = 7
type Fn_ILearningModelDescriptionPreview_get_Name* = proc(self: pointer, value: ptr HSTRING): HRESULT {.abi.}
const Slot_ILearningModelDescriptionPreview_get_Domain* = 8
type Fn_ILearningModelDescriptionPreview_get_Domain* = proc(self: pointer, value: ptr HSTRING): HRESULT {.abi.}
const Slot_ILearningModelDescriptionPreview_get_Description* = 9
type Fn_ILearningModelDescriptionPreview_get_Description* = proc(self: pointer, value: ptr HSTRING): HRESULT {.abi.}
const Slot_ILearningModelDescriptionPreview_get_Version* = 10
type Fn_ILearningModelDescriptionPreview_get_Version* = proc(self: pointer, value: ptr int64): HRESULT {.abi.}
const Slot_ILearningModelDescriptionPreview_get_Metadata* = 11
type Fn_ILearningModelDescriptionPreview_get_Metadata* = proc(self: pointer, value: ptr pointer): HRESULT {.abi.}
const Slot_ILearningModelDescriptionPreview_get_InputFeatures* = 12
type Fn_ILearningModelDescriptionPreview_get_InputFeatures* = proc(self: pointer, value: ptr pointer): HRESULT {.abi.}
const Slot_ILearningModelDescriptionPreview_get_OutputFeatures* = 13
type Fn_ILearningModelDescriptionPreview_get_OutputFeatures* = proc(self: pointer, value: ptr pointer): HRESULT {.abi.}

## Windows.AI.MachineLearning.Preview.ILearningModelEvaluationResultPreview
const IID_ILearningModelEvaluationResultPreview* = GUID(
    data1: 0xDF25EA9F'u32, data2: 0x9863'u16, data3: 0x4088'u16,
    data4: [0x84'u8, 0x98, 0x87, 0xA1, 0xF4, 0x68, 0x6F, 0x92])
const Slot_ILearningModelEvaluationResultPreview_get_CorrelationId* = 6
type Fn_ILearningModelEvaluationResultPreview_get_CorrelationId* = proc(self: pointer, value: ptr HSTRING): HRESULT {.abi.}
const Slot_ILearningModelEvaluationResultPreview_get_Outputs* = 7
type Fn_ILearningModelEvaluationResultPreview_get_Outputs* = proc(self: pointer, value: ptr pointer): HRESULT {.abi.}

## Windows.AI.MachineLearning.Preview.ILearningModelPreview
const IID_ILearningModelPreview* = GUID(
    data1: 0x049C266A'u32, data2: 0x93B4'u16, data3: 0x478C'u16,
    data4: [0xAE'u8, 0xB8, 0x70, 0x15, 0x7B, 0xF0, 0xFF, 0x94])
const Slot_ILearningModelPreview_EvaluateAsync* = 6
type Fn_ILearningModelPreview_EvaluateAsync* = proc(self: pointer, a1LearningModelBindingPreview: pointer, a2: HSTRING, value: ptr pointer): HRESULT {.abi.}
const Slot_ILearningModelPreview_EvaluateFeaturesAsync* = 7
type Fn_ILearningModelPreview_EvaluateFeaturesAsync* = proc(self: pointer, a1: pointer, a2: HSTRING, value: ptr pointer): HRESULT {.abi.}
const Slot_ILearningModelPreview_get_Description* = 8
type Fn_ILearningModelPreview_get_Description* = proc(self: pointer, value: ptr pointer): HRESULT {.abi.}
const Slot_ILearningModelPreview_get_InferencingOptions* = 9
type Fn_ILearningModelPreview_get_InferencingOptions* = proc(self: pointer, value: ptr pointer): HRESULT {.abi.}
const Slot_ILearningModelPreview_put_InferencingOptions* = 10
type Fn_ILearningModelPreview_put_InferencingOptions* = proc(self: pointer, a1InferencingOptionsPreview: pointer): HRESULT {.abi.}

## Windows.AI.MachineLearning.Preview.ILearningModelPreviewStatics
const IID_ILearningModelPreviewStatics* = GUID(
    data1: 0x164BBB60'u32, data2: 0x8465'u16, data3: 0x4786'u16,
    data4: [0x8B'u8, 0x93, 0x2C, 0x16, 0xA8, 0x92, 0x89, 0xD7])
const Slot_ILearningModelPreviewStatics_LoadModelFromStorageFileAsync* = 6
type Fn_ILearningModelPreviewStatics_LoadModelFromStorageFileAsync* = proc(self: pointer, a1IStorageFile: pointer, value: ptr pointer): HRESULT {.abi.}
const Slot_ILearningModelPreviewStatics_LoadModelFromStreamAsync* = 7
type Fn_ILearningModelPreviewStatics_LoadModelFromStreamAsync* = proc(self: pointer, a1IRandomAccessStreamReference: pointer, value: ptr pointer): HRESULT {.abi.}

## Windows.AI.MachineLearning.Preview.ILearningModelVariableDescriptorPreview
const IID_ILearningModelVariableDescriptorPreview* = GUID(
    data1: 0xB13DF682'u32, data2: 0xFC30'u16, data3: 0x492B'u16,
    data4: [0x8E'u8, 0xA0, 0xED, 0x1F, 0x53, 0xC0, 0xB0, 0x38])
const Slot_ILearningModelVariableDescriptorPreview_get_Name* = 6
type Fn_ILearningModelVariableDescriptorPreview_get_Name* = proc(self: pointer, value: ptr HSTRING): HRESULT {.abi.}
const Slot_ILearningModelVariableDescriptorPreview_get_Description* = 7
type Fn_ILearningModelVariableDescriptorPreview_get_Description* = proc(self: pointer, value: ptr HSTRING): HRESULT {.abi.}
const Slot_ILearningModelVariableDescriptorPreview_get_ModelFeatureKind* = 8
type Fn_ILearningModelVariableDescriptorPreview_get_ModelFeatureKind* = proc(self: pointer, value: ptr LearningModelFeatureKindPreview): HRESULT {.abi.}
const Slot_ILearningModelVariableDescriptorPreview_get_IsRequired* = 9
type Fn_ILearningModelVariableDescriptorPreview_get_IsRequired* = proc(self: pointer, value: ptr bool): HRESULT {.abi.}

## Windows.AI.MachineLearning.Preview.IMapVariableDescriptorPreview
const IID_IMapVariableDescriptorPreview* = GUID(
    data1: 0x3CB38370'u32, data2: 0xC02B'u16, data3: 0x4236'u16,
    data4: [0xB3'u8, 0xE8, 0x6B, 0xDC, 0xA4, 0x9C, 0x31, 0x29])
const Slot_IMapVariableDescriptorPreview_get_KeyKind* = 6
type Fn_IMapVariableDescriptorPreview_get_KeyKind* = proc(self: pointer, value: ptr FeatureElementKindPreview): HRESULT {.abi.}
const Slot_IMapVariableDescriptorPreview_get_ValidStringKeys* = 7
type Fn_IMapVariableDescriptorPreview_get_ValidStringKeys* = proc(self: pointer, value: ptr pointer): HRESULT {.abi.}
const Slot_IMapVariableDescriptorPreview_get_ValidIntegerKeys* = 8
type Fn_IMapVariableDescriptorPreview_get_ValidIntegerKeys* = proc(self: pointer, value: ptr pointer): HRESULT {.abi.}
const Slot_IMapVariableDescriptorPreview_get_Fields* = 9
type Fn_IMapVariableDescriptorPreview_get_Fields* = proc(self: pointer, value: ptr pointer): HRESULT {.abi.}

## Windows.AI.MachineLearning.Preview.ISequenceVariableDescriptorPreview
const IID_ISequenceVariableDescriptorPreview* = GUID(
    data1: 0x9CD8F292'u32, data2: 0x98B2'u16, data3: 0x4530'u16,
    data4: [0xA1'u8, 0xB6, 0x2D, 0xED, 0x5F, 0xEC, 0xBC, 0x26])
const Slot_ISequenceVariableDescriptorPreview_get_ElementType* = 6
type Fn_ISequenceVariableDescriptorPreview_get_ElementType* = proc(self: pointer, value: ptr pointer): HRESULT {.abi.}

## Windows.AI.MachineLearning.Preview.ITensorVariableDescriptorPreview
const IID_ITensorVariableDescriptorPreview* = GUID(
    data1: 0xA80F501A'u32, data2: 0x9AAC'u16, data3: 0x4233'u16,
    data4: [0x97'u8, 0x84, 0xAC, 0xEA, 0xF9, 0x25, 0x10, 0xB5])
const Slot_ITensorVariableDescriptorPreview_get_DataType* = 6
type Fn_ITensorVariableDescriptorPreview_get_DataType* = proc(self: pointer, value: ptr FeatureElementKindPreview): HRESULT {.abi.}
const Slot_ITensorVariableDescriptorPreview_get_Shape* = 7
type Fn_ITensorVariableDescriptorPreview_get_Shape* = proc(self: pointer, value: ptr pointer): HRESULT {.abi.}

