## Generated by tools/generate.nim - do not edit.
##
## Source:    Windows.winmd
## Namespace: Windows.AI
##
## Each interface is its vtable: an object whose fields are the
## methods in declaration order, after IInspectable's six (IUnknown's
## three for a delegate). Every method returns HRESULT and its
## declared return type becomes a trailing out-parameter.

import std/hashes
export hashes
import ../core
include ../abidef
export core
import ./types
export types

## Windows.AI.Actions.Hosting.IActionCatalog
const IID_IActionCatalog* = guid"DBE7C537-66EA-5394-9085-4FC19D78375C"
type IActionCatalogVtbl* = object of IInspectableVtbl
  GetAllActions*: proc(self: pointer, valueSize: ptr uint32,
                       value: ptr ptr pointer): HRESULT {.abi.}
  add_Changed*: proc(self: pointer, a1: pointer,
                     value: ptr EventRegistrationToken): HRESULT {.abi.}
  remove_Changed*: proc(self: pointer, a1: EventRegistrationToken
                       ): HRESULT {.abi.}

## Windows.AI.Actions.Hosting.IActionCatalog2
const IID_IActionCatalog2* = guid"370360B1-A14B-5EA8-B611-B5F70342BA44"
type IActionCatalog2Vtbl* = object of IInspectableVtbl
  GetActionsForInputs*: proc(self: pointer, a1Size: uint32, a1: ptr pointer,
                             valueSize: ptr uint32, value: ptr ptr pointer
                            ): HRESULT {.abi.}
  GetActionsForInputs2*: proc(self: pointer, a1Size: uint32, a1: ptr pointer,
                              a2: WindowId, valueSize: ptr uint32,
                              value: ptr ptr pointer): HRESULT {.abi.}

## Windows.AI.Actions.Hosting.IActionCatalog3
const IID_IActionCatalog3* = guid"2E05D518-8680-55D3-820D-2605ADB7D62D"
type IActionCatalog3Vtbl* = object of IInspectableVtbl
  GetActionsForCurrentApp*: proc(self: pointer, valueSize: ptr uint32,
                                 value: ptr ptr pointer): HRESULT {.abi.}

## Windows.AI.Actions.Hosting.IActionDefinition
const IID_IActionDefinition* = guid"FE766ADD-924D-5231-855E-DAC9E82C7E6C"
type IActionDefinitionVtbl* = object of IInspectableVtbl
  get_Id*: proc(self: pointer, value: ptr HSTRING): HRESULT {.abi.}
  get_Description*: proc(self: pointer, value: ptr HSTRING): HRESULT {.abi.}
  get_IconFullPath*: proc(self: pointer, value: ptr HSTRING): HRESULT {.abi.}
  get_PackageFamilyName*: proc(self: pointer, value: ptr HSTRING
                              ): HRESULT {.abi.}
  GetInputs*: proc(self: pointer, valueSize: ptr uint32,
                   value: ptr ptr pointer): HRESULT {.abi.}
  GetOutputs*: proc(self: pointer, valueSize: ptr uint32,
                    value: ptr ptr pointer): HRESULT {.abi.}
  GetOverloads*: proc(self: pointer, valueSize: ptr uint32,
                      value: ptr ptr pointer): HRESULT {.abi.}

## Windows.AI.Actions.Hosting.IActionDefinition2
const IID_IActionDefinition2* = guid"C1F44733-F563-54E2-BD2B-DC4C732054CF"
type IActionDefinition2Vtbl* = object of IInspectableVtbl
  get_DisplaysUI*: proc(self: pointer, value: ptr bool): HRESULT {.abi.}
  get_UsesGenerativeAI*: proc(self: pointer, value: ptr bool): HRESULT {.abi.}
  get_SchemaVersion*: proc(self: pointer, value: ptr uint32): HRESULT {.abi.}

## Windows.AI.Actions.Hosting.IActionDefinition3
const IID_IActionDefinition3* = guid"89C9A7E0-4BFD-55F4-9EED-DCE2250114FA"
type IActionDefinition3Vtbl* = object of IInspectableVtbl
  get_PackageRelativeApplicationId*: proc(self: pointer, value: ptr HSTRING
                                         ): HRESULT {.abi.}

## Windows.AI.Actions.Hosting.IActionDefinition4
const IID_IActionDefinition4* = guid"6DD91071-8847-55B6-9518-9FF8DE421EB7"
type IActionDefinition4Vtbl* = object of IInspectableVtbl
  get_IsCurrentlyAvailable*: proc(self: pointer, value: ptr bool
                                 ): HRESULT {.abi.}

## Windows.AI.Actions.Hosting.IActionDefinition5
const IID_IActionDefinition5* = guid"5BEA33EF-D325-53A8-8DB3-0D771F4D1E54"
type IActionDefinition5Vtbl* = object of IInspectableVtbl
  GetIconFullPath*: proc(self: pointer, a1PropertySet: pointer,
                         value: ptr HSTRING): HRESULT {.abi.}

## Windows.AI.Actions.Hosting.IActionEntityRegistrationInfo
const IID_IActionEntityRegistrationInfo* = guid"C3B92BDB-03C3-5A9E-B049-002FA0405699"
type IActionEntityRegistrationInfoVtbl* = object of IInspectableVtbl
  get_Name*: proc(self: pointer, value: ptr HSTRING): HRESULT {.abi.}
  put_Name*: proc(self: pointer, a1: HSTRING): HRESULT {.abi.}
  get_Kind*: proc(self: pointer, value: ptr ActionEntityKind): HRESULT {.abi.}
  put_Kind*: proc(self: pointer, a1: ActionEntityKind): HRESULT {.abi.}

## Windows.AI.Actions.Hosting.IActionInstance
const IID_IActionInstance* = guid"809BCB6E-E6EF-5F16-B89A-06B8893DF20E"
type IActionInstanceVtbl* = object of IInspectableVtbl
  get_DisplayInfo*: proc(self: pointer, value: ptr pointer): HRESULT {.abi.}
  get_Definition*: proc(self: pointer, value: ptr pointer): HRESULT {.abi.}
  get_Context*: proc(self: pointer, value: ptr pointer): HRESULT {.abi.}
  InvokeAsync*: proc(self: pointer, value: ptr pointer): HRESULT {.abi.}

## Windows.AI.Actions.Hosting.IActionInstanceDisplayInfo
const IID_IActionInstanceDisplayInfo* = guid"FCFDCE21-678B-5602-B9DC-2F4533A6F4B2"
type IActionInstanceDisplayInfoVtbl* = object of IInspectableVtbl
  get_Description*: proc(self: pointer, value: ptr HSTRING): HRESULT {.abi.}

## Windows.AI.Actions.Hosting.IActionOverload
const IID_IActionOverload* = guid"5D184610-D09D-5375-9849-505C359DCA01"
type IActionOverloadVtbl* = object of IInspectableVtbl
  get_DescriptionTemplate*: proc(self: pointer, value: ptr HSTRING
                                ): HRESULT {.abi.}
  GetInputs*: proc(self: pointer, valueSize: ptr uint32,
                   value: ptr ptr pointer): HRESULT {.abi.}
  InvokeAsync*: proc(self: pointer, a1ActionInvocationContext: pointer,
                     value: ptr pointer): HRESULT {.abi.}

## Windows.AI.Actions.Hosting.IActionOverload2
const IID_IActionOverload2* = guid"57EC9906-8231-5A9E-929F-BF39E952EB93"
type IActionOverload2Vtbl* = object of IInspectableVtbl
  InvokeFeedbackAsync*: proc(self: pointer,
                             a1ActionInvocationContext: pointer,
                             a2ActionFeedback: pointer, value: ptr pointer
                            ): HRESULT {.abi.}
  GetSupportsFeedback*: proc(self: pointer, value: ptr bool): HRESULT {.abi.}

## Windows.AI.Actions.IActionEntity
const IID_IActionEntity* = guid"445E700F-2122-5668-9A16-4CAB2982C5F4"
type IActionEntityVtbl* = object of IInspectableVtbl
  get_Kind*: proc(self: pointer, value: ptr ActionEntityKind): HRESULT {.abi.}
  get_DisplayInfo*: proc(self: pointer, value: ptr pointer): HRESULT {.abi.}

## Windows.AI.Actions.IActionEntity2
const IID_IActionEntity2* = guid"98FE136D-DD3A-58C1-AF76-FEB4E19DCE9E"
type IActionEntity2Vtbl* = object of IInspectableVtbl
  get_Id*: proc(self: pointer, value: ptr HSTRING): HRESULT {.abi.}

## Windows.AI.Actions.IActionEntityDisplayInfo
const IID_IActionEntityDisplayInfo* = guid"057A9EDE-03E1-55C6-ACBA-C7056216735A"
type IActionEntityDisplayInfoVtbl* = object of IInspectableVtbl
  get_Title*: proc(self: pointer, value: ptr HSTRING): HRESULT {.abi.}

## Windows.AI.Actions.IActionEntityFactory
const IID_IActionEntityFactory* = guid"9CB752A0-5BF8-5BE2-916E-B00EFF80088D"
type IActionEntityFactoryVtbl* = object of IInspectableVtbl

## Windows.AI.Actions.IActionEntityFactory2
const IID_IActionEntityFactory2* = guid"EA2FB6A5-EC6D-5180-9D30-BC663B84E7B8"
type IActionEntityFactory2Vtbl* = object of IInspectableVtbl
  CreateFileEntity*: proc(self: pointer, a1: HSTRING, value: ptr pointer
                         ): HRESULT {.abi.}
  CreateDocumentEntity*: proc(self: pointer, a1: HSTRING, value: ptr pointer
                             ): HRESULT {.abi.}
  CreatePhotoEntity*: proc(self: pointer, a1: HSTRING, value: ptr pointer
                          ): HRESULT {.abi.}
  CreateTextEntity*: proc(self: pointer, a1: HSTRING, value: ptr pointer
                         ): HRESULT {.abi.}

## Windows.AI.Actions.IActionEntityFactory3
const IID_IActionEntityFactory3* = guid"4910E689-00B5-56BB-9C65-0FCC76215283"
type IActionEntityFactory3Vtbl* = object of IInspectableVtbl
  CreateRemoteFileEntity*: proc(self: pointer, a1: HSTRING,
                                a2: RemoteFileKind, a3Uri: pointer,
                                a4: HSTRING, a5: HSTRING, a6: HSTRING,
                                a7: HSTRING, a8: HSTRING, value: ptr pointer
                               ): HRESULT {.abi.}
  CreateTextEntity*: proc(self: pointer, a1: HSTRING,
                          a2: ActionEntityTextFormat, value: ptr pointer
                         ): HRESULT {.abi.}
  CreateStreamingTextActionEntityWriter*: proc(self: pointer,
                                               a1: ActionEntityTextFormat,
                                               value: ptr pointer
                                              ): HRESULT {.abi.}

## Windows.AI.Actions.IActionEntityFactory4
const IID_IActionEntityFactory4* = guid"332EDA05-DE0E-5A58-B318-A2AD771F013D"
type IActionEntityFactory4Vtbl* = object of IInspectableVtbl
  CreateTableEntity*: proc(self: pointer, a1Size: uint32, a1: ptr HSTRING,
                           a2: uint32, value: ptr pointer): HRESULT {.abi.}
  CreateContactEntity*: proc(self: pointer, a1Contact: pointer,
                             value: ptr pointer): HRESULT {.abi.}

## Windows.AI.Actions.IActionEntityFactory5
const IID_IActionEntityFactory5* = guid"B59FAAB1-CFE4-564A-A5BA-53AD7FF6F924"
type IActionEntityFactory5Vtbl* = object of IInspectableVtbl
  CreateUriEntity*: proc(self: pointer, a1Uri: pointer, value: ptr pointer
                        ): HRESULT {.abi.}
  CreateArrayEntity*: proc(self: pointer, a1: ActionEntityKind,
                           a2Size: uint32, a2: ptr pointer, value: ptr pointer
                          ): HRESULT {.abi.}

## Windows.AI.Actions.IActionEntityFactory6
const IID_IActionEntityFactory6* = guid"DA7123DA-5639-590F-A2DB-C3B5E221F3B6"
type IActionEntityFactory6Vtbl* = object of IInspectableVtbl
  CreateDateTimeEntity*: proc(self: pointer, a1: DateTime, value: ptr pointer
                             ): HRESULT {.abi.}
  CreateAppointmentEntity*: proc(self: pointer, a1: HSTRING,
                                 a2Appointment: pointer, a3Size: uint32,
                                 a3: ptr pointer, value: ptr pointer
                                ): HRESULT {.abi.}

## Windows.AI.Actions.IActionEntityFactory7
const IID_IActionEntityFactory7* = guid"B814B8D5-C9B2-51B5-A342-9FE054D8A1EB"
type IActionEntityFactory7Vtbl* = object of IInspectableVtbl
  CreateCustomTextEntity*: proc(self: pointer, a1: HSTRING, a2: HSTRING,
                                a3: pointer, value: ptr pointer
                               ): HRESULT {.abi.}
  CreateArrayEntityWithCustomKind*: proc(self: pointer, a1: ActionEntityKind,
                                         a2: HSTRING, a3Size: uint32,
                                         a3: ptr pointer, value: ptr pointer
                                        ): HRESULT {.abi.}

## Windows.AI.Actions.IActionEntityFactoryFactory
const IID_IActionEntityFactoryFactory* = guid"C9147D8F-88A0-5EC0-A564-47E2A1081412"
type IActionEntityFactoryFactoryVtbl* = object of IInspectableVtbl

## Windows.AI.Actions.IActionFeedback
const IID_IActionFeedback* = guid"A12EE7AB-2454-56C9-BBDF-C089457FBC5E"
type IActionFeedbackVtbl* = object of IInspectableVtbl
  get_FeedbackKind*: proc(self: pointer, value: ptr ActionFeedbackKind
                         ): HRESULT {.abi.}

## Windows.AI.Actions.IActionInvocationContext
const IID_IActionInvocationContext* = guid"C32B622E-86E1-5EBA-9661-605910104978"
type IActionInvocationContextVtbl* = object of IInspectableVtbl
  get_EntityFactory*: proc(self: pointer, value: ptr pointer): HRESULT {.abi.}
  SetInputEntity*: proc(self: pointer, a1: HSTRING, a2ActionEntity: pointer
                       ): HRESULT {.abi.}
  GetInputEntities*: proc(self: pointer, valueSize: ptr uint32,
                          value: ptr ptr pointer): HRESULT {.abi.}
  SetOutputEntity*: proc(self: pointer, a1: HSTRING, a2ActionEntity: pointer
                        ): HRESULT {.abi.}
  GetOutputEntities*: proc(self: pointer, valueSize: ptr uint32,
                           value: ptr ptr pointer): HRESULT {.abi.}
  get_Result*: proc(self: pointer, value: ptr ActionInvocationResult
                   ): HRESULT {.abi.}
  put_Result*: proc(self: pointer, a1: ActionInvocationResult
                   ): HRESULT {.abi.}
  get_ExtendedError*: proc(self: pointer, value: ptr HRESULT): HRESULT {.abi.}
  put_ExtendedError*: proc(self: pointer, a1: HRESULT): HRESULT {.abi.}

## Windows.AI.Actions.IActionInvocationContext2
const IID_IActionInvocationContext2* = guid"7C843086-9279-5BCD-8F2E-D15121E7A827"
type IActionInvocationContext2Vtbl* = object of IInspectableVtbl
  get_InvokerWindowId*: proc(self: pointer, value: ptr WindowId
                            ): HRESULT {.abi.}
  get_HelpDetails*: proc(self: pointer, value: ptr pointer): HRESULT {.abi.}
  get_ActionId*: proc(self: pointer, value: ptr HSTRING): HRESULT {.abi.}
  get_InvokerAppUserModelId*: proc(self: pointer, value: ptr HSTRING
                                  ): HRESULT {.abi.}

## Windows.AI.Actions.IActionInvocationHelpDetails
const IID_IActionInvocationHelpDetails* = guid"5430F272-078F-5722-8F7D-90CF8DDD595E"
type IActionInvocationHelpDetailsVtbl* = object of IInspectableVtbl
  get_Kind*: proc(self: pointer, value: ptr ActionInvocationHelpKind
                 ): HRESULT {.abi.}
  put_Kind*: proc(self: pointer, a1: ActionInvocationHelpKind
                 ): HRESULT {.abi.}
  get_Title*: proc(self: pointer, value: ptr HSTRING): HRESULT {.abi.}
  put_Title*: proc(self: pointer, a1: HSTRING): HRESULT {.abi.}
  get_Description*: proc(self: pointer, value: ptr HSTRING): HRESULT {.abi.}
  put_Description*: proc(self: pointer, a1: HSTRING): HRESULT {.abi.}
  get_HelpUri*: proc(self: pointer, value: ptr pointer): HRESULT {.abi.}
  put_HelpUri*: proc(self: pointer, a1Uri: pointer): HRESULT {.abi.}
  get_HelpUriDescription*: proc(self: pointer, value: ptr HSTRING
                               ): HRESULT {.abi.}
  put_HelpUriDescription*: proc(self: pointer, a1: HSTRING): HRESULT {.abi.}

## Windows.AI.Actions.IActionInvocationHelpDetails2
const IID_IActionInvocationHelpDetails2* = guid"307F6BA5-5FDA-59F1-9722-1859801AD550"
type IActionInvocationHelpDetails2Vtbl* = object of IInspectableVtbl
  add_Changed*: proc(self: pointer, a1: pointer,
                     value: ptr EventRegistrationToken): HRESULT {.abi.}
  remove_Changed*: proc(self: pointer, a1: EventRegistrationToken
                       ): HRESULT {.abi.}

## Windows.AI.Actions.IActionRuntime
const IID_IActionRuntime* = guid"206EFA2C-C909-508A-B4B0-9482BE96DB9C"
type IActionRuntimeVtbl* = object of IInspectableVtbl
  get_ActionCatalog*: proc(self: pointer, value: ptr pointer): HRESULT {.abi.}
  get_EntityFactory*: proc(self: pointer, value: ptr pointer): HRESULT {.abi.}
  CreateInvocationContext*: proc(self: pointer, a1: HSTRING,
                                 value: ptr pointer): HRESULT {.abi.}

## Windows.AI.Actions.IActionRuntime2
const IID_IActionRuntime2* = guid"2DA4D2C0-E593-5350-8143-15BB24F63411"
type IActionRuntime2Vtbl* = object of IInspectableVtbl
  CreateActionFeedback*: proc(self: pointer, a1: ActionFeedbackKind,
                              value: ptr pointer): HRESULT {.abi.}
  SetActionAvailability*: proc(self: pointer, a1: HSTRING, a2: bool
                              ): HRESULT {.abi.}
  GetActionAvailability*: proc(self: pointer, a1: HSTRING, value: ptr bool
                              ): HRESULT {.abi.}

## Windows.AI.Actions.IActionRuntime3
const IID_IActionRuntime3* = guid"F020C3C0-CAEC-5928-AD00-81069B80FBC1"
type IActionRuntime3Vtbl* = object of IInspectableVtbl
  CreateInvocationContextWithWindowId*: proc(self: pointer, a1: HSTRING,
                                             a2: WindowId, value: ptr pointer
                                            ): HRESULT {.abi.}
  GetActionEntityById*: proc(self: pointer, a1: HSTRING, value: ptr pointer
                            ): HRESULT {.abi.}
  get_LatestSupportedSchemaVersion*: proc(self: pointer, value: ptr uint32
                                         ): HRESULT {.abi.}

## Windows.AI.Actions.IActionRuntime4
const IID_IActionRuntime4* = guid"06851DCD-C743-5C7F-88A1-BBAEB02F5E28"
type IActionRuntime4Vtbl* = object of IInspectableVtbl
  GetActionInvocationContextFromToken*: proc(self: pointer, a1: HSTRING,
                                             value: ptr pointer
                                            ): HRESULT {.abi.}

## Windows.AI.Actions.IActionRuntime5
const IID_IActionRuntime5* = guid"C2E995B1-52A9-5F3A-BEBB-A04655E96218"
type IActionRuntime5Vtbl* = object of IInspectableVtbl
  get_CustomEntityStore*: proc(self: pointer, value: ptr pointer
                              ): HRESULT {.abi.}

## Windows.AI.Actions.IActionRuntimeFactory
const IID_IActionRuntimeFactory* = guid"D3F366E9-8DC9-50A0-8040-E5C14FA609D6"
type IActionRuntimeFactoryVtbl* = object of IInspectableVtbl

## Windows.AI.Actions.IActionRuntimeStatics
const IID_IActionRuntimeStatics* = guid"2C697AAB-55F2-55AA-9D63-A73EC190CECD"
type IActionRuntimeStaticsVtbl* = object of IInspectableVtbl
  GetDefault*: proc(self: pointer, value: ptr pointer): HRESULT {.abi.}

## Windows.AI.Actions.IAppointmentActionEntity
const IID_IAppointmentActionEntity* = guid"29DAA00E-B474-581C-B555-6187D1AA8231"
type IAppointmentActionEntityVtbl* = object of IInspectableVtbl
  get_SourceId*: proc(self: pointer, value: ptr HSTRING): HRESULT {.abi.}
  get_Appointment*: proc(self: pointer, value: ptr pointer): HRESULT {.abi.}
  GetAttendees*: proc(self: pointer, valueSize: ptr uint32,
                      value: ptr ptr pointer): HRESULT {.abi.}
  GetPresentedFiles*: proc(self: pointer, valueSize: ptr uint32,
                           value: ptr ptr pointer): HRESULT {.abi.}
  SetPresentedFiles*: proc(self: pointer, a1Size: uint32, a1: ptr pointer
                          ): HRESULT {.abi.}
  GetSharedFiles*: proc(self: pointer, valueSize: ptr uint32,
                        value: ptr ptr pointer): HRESULT {.abi.}
  SetSharedFiles*: proc(self: pointer, a1Size: uint32, a1: ptr pointer
                       ): HRESULT {.abi.}

## Windows.AI.Actions.IArrayActionEntity
const IID_IArrayActionEntity* = guid"45798E78-1059-5311-8A1B-DE0081A4CA3B"
type IArrayActionEntityVtbl* = object of IInspectableVtbl
  get_ElementKind*: proc(self: pointer, value: ptr ActionEntityKind
                        ): HRESULT {.abi.}
  GetAll*: proc(self: pointer, valueSize: ptr uint32, value: ptr ptr pointer
               ): HRESULT {.abi.}

## Windows.AI.Actions.IArrayActionEntity2
const IID_IArrayActionEntity2* = guid"7366E049-7FE8-5DF9-BBCA-CEA5C0F3D316"
type IArrayActionEntity2Vtbl* = object of IInspectableVtbl
  get_CustomElementKind*: proc(self: pointer, value: ptr HSTRING
                              ): HRESULT {.abi.}

## Windows.AI.Actions.IContactActionEntity
const IID_IContactActionEntity* = guid"458C3E07-5892-5485-BD9B-8F7A540C9501"
type IContactActionEntityVtbl* = object of IInspectableVtbl
  get_Contact*: proc(self: pointer, value: ptr pointer): HRESULT {.abi.}

## Windows.AI.Actions.ICustomActionEntityStore
const IID_ICustomActionEntityStore* = guid"FA7B44D0-1762-5828-9938-E7CAE5199E01"
type ICustomActionEntityStoreVtbl* = object of IInspectableVtbl
  GetLastModifiedTime*: proc(self: pointer, a1: HSTRING, value: ptr DateTime
                            ): HRESULT {.abi.}
  Insert*: proc(self: pointer, a1CustomTextActionEntity: pointer
               ): HRESULT {.abi.}
  InsertMany*: proc(self: pointer, a1Size: uint32, a1: ptr pointer
                   ): HRESULT {.abi.}
  Delete*: proc(self: pointer, a1: HSTRING): HRESULT {.abi.}

## Windows.AI.Actions.ICustomActionEntityStoreFactory
const IID_ICustomActionEntityStoreFactory* = guid"D8B46BDB-68A5-5E07-9113-ABB9241AAAB1"
type ICustomActionEntityStoreFactoryVtbl* = object of IInspectableVtbl

## Windows.AI.Actions.ICustomTextActionEntity
const IID_ICustomTextActionEntity* = guid"50EAAC95-1D6C-54B0-8963-E38DEA3F6AEC"
type ICustomTextActionEntityVtbl* = object of IInspectableVtbl
  get_CustomTextKind*: proc(self: pointer, value: ptr HSTRING
                           ): HRESULT {.abi.}
  get_KeyPhrase*: proc(self: pointer, value: ptr HSTRING): HRESULT {.abi.}
  get_Properties*: proc(self: pointer, value: ptr pointer): HRESULT {.abi.}

## Windows.AI.Actions.IDateTimeActionEntity
const IID_IDateTimeActionEntity* = guid"FD5A0880-EEAE-553A-BFED-A9229D57447D"
type IDateTimeActionEntityVtbl* = object of IInspectableVtbl
  get_DateTime*: proc(self: pointer, value: ptr DateTime): HRESULT {.abi.}

## Windows.AI.Actions.IDocumentActionEntity
const IID_IDocumentActionEntity* = guid"56715297-960B-59FF-AF4B-ECE1098B2E36"
type IDocumentActionEntityVtbl* = object of IInspectableVtbl
  get_FullPath*: proc(self: pointer, value: ptr HSTRING): HRESULT {.abi.}

## Windows.AI.Actions.IFileActionEntity
const IID_IFileActionEntity* = guid"F20AB43F-4C80-5904-BD42-3E6248BABFCF"
type IFileActionEntityVtbl* = object of IInspectableVtbl
  get_FullPath*: proc(self: pointer, value: ptr HSTRING): HRESULT {.abi.}

## Windows.AI.Actions.INamedActionEntity
const IID_INamedActionEntity* = guid"1AAEBEEF-435B-5A0D-8182-05FE4DD47712"
type INamedActionEntityVtbl* = object of IInspectableVtbl
  get_Name*: proc(self: pointer, value: ptr HSTRING): HRESULT {.abi.}
  put_Name*: proc(self: pointer, a1: HSTRING): HRESULT {.abi.}
  get_Entity*: proc(self: pointer, value: ptr pointer): HRESULT {.abi.}
  put_Entity*: proc(self: pointer, a1ActionEntity: pointer): HRESULT {.abi.}

## Windows.AI.Actions.IPhotoActionEntity
const IID_IPhotoActionEntity* = guid"425123B3-20EF-51A6-B35F-8414384765C5"
type IPhotoActionEntityVtbl* = object of IInspectableVtbl
  get_FullPath*: proc(self: pointer, value: ptr HSTRING): HRESULT {.abi.}

## Windows.AI.Actions.IRemoteFileActionEntity
const IID_IRemoteFileActionEntity* = guid"A5D8EC21-A2BD-545A-ABFC-D7AA79FD0B81"
type IRemoteFileActionEntityVtbl* = object of IInspectableVtbl
  get_SourceId*: proc(self: pointer, value: ptr HSTRING): HRESULT {.abi.}
  get_FileKind*: proc(self: pointer, value: ptr RemoteFileKind
                     ): HRESULT {.abi.}
  get_SourceUri*: proc(self: pointer, value: ptr pointer): HRESULT {.abi.}
  get_FileId*: proc(self: pointer, value: ptr HSTRING): HRESULT {.abi.}
  get_ContentType*: proc(self: pointer, value: ptr HSTRING): HRESULT {.abi.}
  get_DriveId*: proc(self: pointer, value: ptr HSTRING): HRESULT {.abi.}
  get_AccountId*: proc(self: pointer, value: ptr HSTRING): HRESULT {.abi.}
  get_Extension*: proc(self: pointer, value: ptr HSTRING): HRESULT {.abi.}

## Windows.AI.Actions.IRemoteFileActionEntity2
const IID_IRemoteFileActionEntity2* = guid"9CC8CC54-77D8-5537-83C4-6F18C1BC9F67"
type IRemoteFileActionEntity2Vtbl* = object of IInspectableVtbl
  get_Filename*: proc(self: pointer, value: ptr HSTRING): HRESULT {.abi.}
  put_Filename*: proc(self: pointer, a1: HSTRING): HRESULT {.abi.}
  get_Creator*: proc(self: pointer, value: ptr pointer): HRESULT {.abi.}
  put_Creator*: proc(self: pointer, a1ContactActionEntity: pointer
                    ): HRESULT {.abi.}
  get_LastUpdatedTime*: proc(self: pointer, value: ptr pointer
                            ): HRESULT {.abi.}
  put_LastUpdatedTime*: proc(self: pointer, a1: pointer): HRESULT {.abi.}
  SetContributors*: proc(self: pointer, a1Size: uint32, a1: ptr pointer
                        ): HRESULT {.abi.}
  GetContributors*: proc(self: pointer, valueSize: ptr uint32,
                         value: ptr ptr pointer): HRESULT {.abi.}

## Windows.AI.Actions.IStreamingTextActionEntity
const IID_IStreamingTextActionEntity* = guid"44CD8A16-ABC9-5703-B4BF-6FE8B7A802FD"
type IStreamingTextActionEntityVtbl* = object of IInspectableVtbl
  get_IsComplete*: proc(self: pointer, value: ptr bool): HRESULT {.abi.}
  GetText*: proc(self: pointer, value: ptr HSTRING): HRESULT {.abi.}
  get_TextFormat*: proc(self: pointer, value: ptr ActionEntityTextFormat
                       ): HRESULT {.abi.}
  add_TextChanged*: proc(self: pointer, a1: pointer,
                         value: ptr EventRegistrationToken): HRESULT {.abi.}
  remove_TextChanged*: proc(self: pointer, a1: EventRegistrationToken
                           ): HRESULT {.abi.}

## Windows.AI.Actions.IStreamingTextActionEntityTextChangedArgs
const IID_IStreamingTextActionEntityTextChangedArgs* = guid"2C62011F-3E06-588B-A3BD-D726BD82FB13"
type IStreamingTextActionEntityTextChangedArgsVtbl* = object of IInspectableVtbl
  get_Text*: proc(self: pointer, value: ptr HSTRING): HRESULT {.abi.}
  get_IsComplete*: proc(self: pointer, value: ptr bool): HRESULT {.abi.}

## Windows.AI.Actions.IStreamingTextActionEntityWriter
const IID_IStreamingTextActionEntityWriter* = guid"6BCE2F76-A8AF-5FF2-833C-108737BA0F42"
type IStreamingTextActionEntityWriterVtbl* = object of IInspectableVtbl
  get_ReaderEntity*: proc(self: pointer, value: ptr pointer): HRESULT {.abi.}
  get_TextFormat*: proc(self: pointer, value: ptr ActionEntityTextFormat
                       ): HRESULT {.abi.}
  SetText*: proc(self: pointer, a1: HSTRING): HRESULT {.abi.}

## Windows.AI.Actions.ITableActionEntity
const IID_ITableActionEntity* = guid"0F252CDB-BA24-5DBB-9D17-1B300773D141"
type ITableActionEntityVtbl* = object of IInspectableVtbl
  GetTextContent*: proc(self: pointer, valueSize: ptr uint32,
                        value: ptr ptr HSTRING): HRESULT {.abi.}
  get_RowCount*: proc(self: pointer, value: ptr uint32): HRESULT {.abi.}
  get_ColumnCount*: proc(self: pointer, value: ptr uint32): HRESULT {.abi.}

## Windows.AI.Actions.ITextActionEntity
const IID_ITextActionEntity* = guid"3C4EC25F-5ADB-5F73-B8F3-080FBEADD612"
type ITextActionEntityVtbl* = object of IInspectableVtbl
  get_Text*: proc(self: pointer, value: ptr HSTRING): HRESULT {.abi.}

## Windows.AI.Actions.ITextActionEntity2
const IID_ITextActionEntity2* = guid"7C500889-CF08-51E7-BECA-F0BBC7A7486C"
type ITextActionEntity2Vtbl* = object of IInspectableVtbl
  get_TextFormat*: proc(self: pointer, value: ptr ActionEntityTextFormat
                       ): HRESULT {.abi.}

## Windows.AI.Actions.IUriActionEntity
const IID_IUriActionEntity* = guid"A81CDE77-BC25-532D-905E-B0725C5BCD4E"
type IUriActionEntityVtbl* = object of IInspectableVtbl
  get_Uri*: proc(self: pointer, value: ptr pointer): HRESULT {.abi.}

## Windows.AI.Actions.Provider.IActionFeedbackHandler
const IID_IActionFeedbackHandler* = guid"A3FC3C51-A8C6-52C8-AD77-37BF3E2B565C"
type IActionFeedbackHandlerVtbl* = object of IInspectableVtbl
  ProcessFeedbackAsync*: proc(self: pointer,
                              a1ActionInvocationContext: pointer,
                              a2ActionFeedback: pointer, value: ptr pointer
                             ): HRESULT {.abi.}

## Windows.AI.Actions.Provider.IActionProvider
const IID_IActionProvider* = guid"62906C47-3D07-55F1-AEFA-1522505AFBBE"
type IActionProviderVtbl* = object of IInspectableVtbl
  InvokeAsync*: proc(self: pointer, a1ActionInvocationContext: pointer,
                     value: ptr pointer): HRESULT {.abi.}

## Windows.AI.Agents.Mcp.IMcpMessageFilterExperimental
const IID_IMcpMessageFilterExperimental* = guid"C5F8F821-895C-5241-B45A-92E249A7D873"
type IMcpMessageFilterExperimentalVtbl* = object of IInspectableVtbl
  Initialize*: proc(self: pointer, a1: HSTRING, a2: uint32, a3: HSTRING,
                    a4: HSTRING, a5: uint32): HRESULT {.abi.}
  OnMessage*: proc(self: pointer, a1: HSTRING, a2: McpMessageDirection,
                   a3McpMessageFilterResponse: pointer): HRESULT {.abi.}

## Windows.AI.Agents.Mcp.IMcpMessageFilterResponse
const IID_IMcpMessageFilterResponse* = guid"363CE02C-7098-5E13-A408-7B43E1F452AC"
type IMcpMessageFilterResponseVtbl* = object of IInspectableVtbl

## Windows.AI.Agents.Mcp.IMcpMessageFilterResponseExperimental
const IID_IMcpMessageFilterResponseExperimental* = guid"E215B5F2-CB02-56CF-AAB0-84AEF65D1665"
type IMcpMessageFilterResponseExperimentalVtbl* = object of IInspectableVtbl
  get_IsAllowed*: proc(self: pointer, value: ptr bool): HRESULT {.abi.}
  put_IsAllowed*: proc(self: pointer, a1: bool): HRESULT {.abi.}
  get_MessageIfNotAllowed*: proc(self: pointer, value: ptr HSTRING
                                ): HRESULT {.abi.}
  put_MessageIfNotAllowed*: proc(self: pointer, a1: HSTRING): HRESULT {.abi.}

## Windows.AI.Agents.Mcp.IMcpMessageFilterResponseExperimental2
const IID_IMcpMessageFilterResponseExperimental2* = guid"10F4B099-6632-505A-A638-E704C7E47ABF"
type IMcpMessageFilterResponseExperimental2Vtbl* = object of IInspectableVtbl
  Allow*: proc(self: pointer): HRESULT {.abi.}
  Reject*: proc(self: pointer, a1: HSTRING): HRESULT {.abi.}

## Windows.AI.MachineLearning.IImageFeatureDescriptor
const IID_IImageFeatureDescriptor* = guid"365585A5-171A-4A2A-985F-265159D3895A"
type IImageFeatureDescriptorVtbl* = object of IInspectableVtbl
  get_BitmapPixelFormat*: proc(self: pointer, value: ptr BitmapPixelFormat
                              ): HRESULT {.abi.}
  get_BitmapAlphaMode*: proc(self: pointer, value: ptr BitmapAlphaMode
                            ): HRESULT {.abi.}
  get_Width*: proc(self: pointer, value: ptr uint32): HRESULT {.abi.}
  get_Height*: proc(self: pointer, value: ptr uint32): HRESULT {.abi.}

## Windows.AI.MachineLearning.IImageFeatureDescriptor2
const IID_IImageFeatureDescriptor2* = guid"2B27CCA7-D533-5862-BB98-1611B155B0E1"
type IImageFeatureDescriptor2Vtbl* = object of IInspectableVtbl
  get_PixelRange*: proc(self: pointer, value: ptr LearningModelPixelRange
                       ): HRESULT {.abi.}

## Windows.AI.MachineLearning.IImageFeatureValue
const IID_IImageFeatureValue* = guid"F0414FD9-C9AA-4405-B7FB-94F87C8A3037"
type IImageFeatureValueVtbl* = object of IInspectableVtbl
  get_VideoFrame*: proc(self: pointer, value: ptr pointer): HRESULT {.abi.}

## Windows.AI.MachineLearning.IImageFeatureValueStatics
const IID_IImageFeatureValueStatics* = guid"1BC317FD-23CB-4610-B085-C8E1C87EBAA0"
type IImageFeatureValueStaticsVtbl* = object of IInspectableVtbl
  CreateFromVideoFrame*: proc(self: pointer, a1VideoFrame: pointer,
                              value: ptr pointer): HRESULT {.abi.}

## Windows.AI.MachineLearning.ILearningModel
const IID_ILearningModel* = guid"5B8E4920-489F-4E86-9128-265A327B78FA"
type ILearningModelVtbl* = object of IInspectableVtbl
  get_Author*: proc(self: pointer, value: ptr HSTRING): HRESULT {.abi.}
  get_Name*: proc(self: pointer, value: ptr HSTRING): HRESULT {.abi.}
  get_Domain*: proc(self: pointer, value: ptr HSTRING): HRESULT {.abi.}
  get_Description*: proc(self: pointer, value: ptr HSTRING): HRESULT {.abi.}
  get_Version*: proc(self: pointer, value: ptr int64): HRESULT {.abi.}
  get_Metadata*: proc(self: pointer, value: ptr pointer): HRESULT {.abi.}
  get_InputFeatures*: proc(self: pointer, value: ptr pointer): HRESULT {.abi.}
  get_OutputFeatures*: proc(self: pointer, value: ptr pointer
                           ): HRESULT {.abi.}

## Windows.AI.MachineLearning.ILearningModelBinding
const IID_ILearningModelBinding* = guid"EA312F20-168F-4F8C-94FE-2E7AC31B4AA8"
type ILearningModelBindingVtbl* = object of IInspectableVtbl
  `Bind`*: proc(self: pointer, a1: HSTRING, a2: pointer): HRESULT {.abi.}
  Bind2*: proc(self: pointer, a1: HSTRING, a2: pointer,
               a3IPropertySet: pointer): HRESULT {.abi.}
  Clear*: proc(self: pointer): HRESULT {.abi.}

## Windows.AI.MachineLearning.ILearningModelBindingFactory
const IID_ILearningModelBindingFactory* = guid"C95F7A7A-E788-475E-8917-23AA381FAF0B"
type ILearningModelBindingFactoryVtbl* = object of IInspectableVtbl
  CreateFromSession*: proc(self: pointer, a1LearningModelSession: pointer,
                           value: ptr pointer): HRESULT {.abi.}

## Windows.AI.MachineLearning.ILearningModelDevice
const IID_ILearningModelDevice* = guid"F5C2C8FE-3F56-4A8C-AC5F-FDB92D8B8252"
type ILearningModelDeviceVtbl* = object of IInspectableVtbl
  get_AdapterId*: proc(self: pointer, value: ptr DisplayAdapterId
                      ): HRESULT {.abi.}
  get_Direct3D11Device*: proc(self: pointer, value: ptr pointer
                             ): HRESULT {.abi.}

## Windows.AI.MachineLearning.ILearningModelDeviceFactory
const IID_ILearningModelDeviceFactory* = guid"9CFFD74D-B1E5-4F20-80AD-0A56690DB06B"
type ILearningModelDeviceFactoryVtbl* = object of IInspectableVtbl
  Create*: proc(self: pointer, a1: LearningModelDeviceKind, value: ptr pointer
               ): HRESULT {.abi.}

## Windows.AI.MachineLearning.ILearningModelDeviceStatics
const IID_ILearningModelDeviceStatics* = guid"49F32107-A8BF-42BB-92C7-10B12DC5D21F"
type ILearningModelDeviceStaticsVtbl* = object of IInspectableVtbl
  CreateFromDirect3D11Device*: proc(self: pointer, a1IDirect3DDevice: pointer,
                                    value: ptr pointer): HRESULT {.abi.}

## Windows.AI.MachineLearning.ILearningModelEvaluationResult
const IID_ILearningModelEvaluationResult* = guid"B2F9BFCD-960E-49C0-8593-EB190AE3EEE2"
type ILearningModelEvaluationResultVtbl* = object of IInspectableVtbl
  get_CorrelationId*: proc(self: pointer, value: ptr HSTRING): HRESULT {.abi.}
  get_ErrorStatus*: proc(self: pointer, value: ptr int32): HRESULT {.abi.}
  get_Succeeded*: proc(self: pointer, value: ptr bool): HRESULT {.abi.}
  get_Outputs*: proc(self: pointer, value: ptr pointer): HRESULT {.abi.}

## Windows.AI.MachineLearning.ILearningModelFeatureDescriptor
const IID_ILearningModelFeatureDescriptor* = guid"BC08CF7C-6ED0-4004-97BA-B9A2EECD2B4F"
type ILearningModelFeatureDescriptorVtbl* = object of IInspectableVtbl
  get_Name*: proc(self: pointer, value: ptr HSTRING): HRESULT {.abi.}
  get_Description*: proc(self: pointer, value: ptr HSTRING): HRESULT {.abi.}
  get_Kind*: proc(self: pointer, value: ptr LearningModelFeatureKind
                 ): HRESULT {.abi.}
  get_IsRequired*: proc(self: pointer, value: ptr bool): HRESULT {.abi.}

## Windows.AI.MachineLearning.ILearningModelFeatureValue
const IID_ILearningModelFeatureValue* = guid"F51005DB-4085-4DFE-9FED-95EB0C0CF75C"
type ILearningModelFeatureValueVtbl* = object of IInspectableVtbl
  get_Kind*: proc(self: pointer, value: ptr LearningModelFeatureKind
                 ): HRESULT {.abi.}

## Windows.AI.MachineLearning.ILearningModelOperatorProvider
const IID_ILearningModelOperatorProvider* = guid"2A222E5D-AFB1-47ED-BFAD-B5B3A459EC04"
type ILearningModelOperatorProviderVtbl* = object of IInspectableVtbl

## Windows.AI.MachineLearning.ILearningModelSession
const IID_ILearningModelSession* = guid"8E58F8F6-B787-4C11-90F0-7129AECA74A9"
type ILearningModelSessionVtbl* = object of IInspectableVtbl
  get_Model*: proc(self: pointer, value: ptr pointer): HRESULT {.abi.}
  get_Device*: proc(self: pointer, value: ptr pointer): HRESULT {.abi.}
  get_EvaluationProperties*: proc(self: pointer, value: ptr pointer
                                 ): HRESULT {.abi.}
  EvaluateAsync*: proc(self: pointer, a1LearningModelBinding: pointer,
                       a2: HSTRING, value: ptr pointer): HRESULT {.abi.}
  EvaluateFeaturesAsync*: proc(self: pointer, a1: pointer, a2: HSTRING,
                               value: ptr pointer): HRESULT {.abi.}
  Evaluate*: proc(self: pointer, a1LearningModelBinding: pointer, a2: HSTRING,
                  value: ptr pointer): HRESULT {.abi.}
  EvaluateFeatures*: proc(self: pointer, a1: pointer, a2: HSTRING,
                          value: ptr pointer): HRESULT {.abi.}

## Windows.AI.MachineLearning.ILearningModelSessionFactory
const IID_ILearningModelSessionFactory* = guid"0F6B881D-1C9B-47B6-BFE0-F1CF62A67579"
type ILearningModelSessionFactoryVtbl* = object of IInspectableVtbl
  CreateFromModel*: proc(self: pointer, a1LearningModel: pointer,
                         value: ptr pointer): HRESULT {.abi.}
  CreateFromModelOnDevice*: proc(self: pointer, a1LearningModel: pointer,
                                 a2LearningModelDevice: pointer,
                                 value: ptr pointer): HRESULT {.abi.}

## Windows.AI.MachineLearning.ILearningModelSessionFactory2
const IID_ILearningModelSessionFactory2* = guid"4E5C88BF-0A1F-5FEC-ADE0-2FD91E4EF29B"
type ILearningModelSessionFactory2Vtbl* = object of IInspectableVtbl
  CreateFromModelOnDeviceWithSessionOptions*: proc(self: pointer,
                                                   a1LearningModel: pointer,
                                                   a2LearningModelDevice: pointer,
                                                   a3LearningModelSessionOptions: pointer,
                                                   value: ptr pointer
                                                  ): HRESULT {.abi.}

## Windows.AI.MachineLearning.ILearningModelSessionOptions
const IID_ILearningModelSessionOptions* = guid"B8F63FA1-134D-5133-8CFF-3A5C3C263BEB"
type ILearningModelSessionOptionsVtbl* = object of IInspectableVtbl
  get_BatchSizeOverride*: proc(self: pointer, value: ptr uint32
                              ): HRESULT {.abi.}
  put_BatchSizeOverride*: proc(self: pointer, a1: uint32): HRESULT {.abi.}

## Windows.AI.MachineLearning.ILearningModelSessionOptions2
const IID_ILearningModelSessionOptions2* = guid"6FCD1DC4-175F-5BD2-8DE5-2F2006A25ADF"
type ILearningModelSessionOptions2Vtbl* = object of IInspectableVtbl
  get_CloseModelOnSessionCreation*: proc(self: pointer, value: ptr bool
                                        ): HRESULT {.abi.}
  put_CloseModelOnSessionCreation*: proc(self: pointer, a1: bool
                                        ): HRESULT {.abi.}

## Windows.AI.MachineLearning.ILearningModelSessionOptions3
const IID_ILearningModelSessionOptions3* = guid"58E15CEE-D8C2-56FC-92E8-76D751081086"
type ILearningModelSessionOptions3Vtbl* = object of IInspectableVtbl
  OverrideNamedDimension*: proc(self: pointer, a1: HSTRING, a2: uint32
                               ): HRESULT {.abi.}

## Windows.AI.MachineLearning.ILearningModelStatics
const IID_ILearningModelStatics* = guid"E3B977E8-6952-4E47-8EF4-1F7F07897C6D"
type ILearningModelStaticsVtbl* = object of IInspectableVtbl
  LoadFromStorageFileAsync*: proc(self: pointer, a1IStorageFile: pointer,
                                  value: ptr pointer): HRESULT {.abi.}
  LoadFromStreamAsync*: proc(self: pointer,
                             a1IRandomAccessStreamReference: pointer,
                             value: ptr pointer): HRESULT {.abi.}
  LoadFromFilePath*: proc(self: pointer, a1: HSTRING, value: ptr pointer
                         ): HRESULT {.abi.}
  LoadFromStream*: proc(self: pointer,
                        a1IRandomAccessStreamReference: pointer,
                        value: ptr pointer): HRESULT {.abi.}
  LoadFromStorageFileAsync2*: proc(self: pointer, a1IStorageFile: pointer,
                                   a2ILearningModelOperatorProvider: pointer,
                                   value: ptr pointer): HRESULT {.abi.}
  LoadFromStreamAsync2*: proc(self: pointer,
                              a1IRandomAccessStreamReference: pointer,
                              a2ILearningModelOperatorProvider: pointer,
                              value: ptr pointer): HRESULT {.abi.}
  LoadFromFilePath2*: proc(self: pointer, a1: HSTRING,
                           a2ILearningModelOperatorProvider: pointer,
                           value: ptr pointer): HRESULT {.abi.}
  LoadFromStream2*: proc(self: pointer,
                         a1IRandomAccessStreamReference: pointer,
                         a2ILearningModelOperatorProvider: pointer,
                         value: ptr pointer): HRESULT {.abi.}

## Windows.AI.MachineLearning.IMapFeatureDescriptor
const IID_IMapFeatureDescriptor* = guid"530424BD-A257-436D-9E60-C2981F7CC5C4"
type IMapFeatureDescriptorVtbl* = object of IInspectableVtbl
  get_KeyKind*: proc(self: pointer, value: ptr TensorKind): HRESULT {.abi.}
  get_ValueDescriptor*: proc(self: pointer, value: ptr pointer
                            ): HRESULT {.abi.}

## Windows.AI.MachineLearning.ISequenceFeatureDescriptor
const IID_ISequenceFeatureDescriptor* = guid"84F6945A-562B-4D62-A851-739ACED96668"
type ISequenceFeatureDescriptorVtbl* = object of IInspectableVtbl
  get_ElementDescriptor*: proc(self: pointer, value: ptr pointer
                              ): HRESULT {.abi.}

## Windows.AI.MachineLearning.ITensor
const IID_ITensor* = guid"05489593-A305-4A25-AD09-440119B4B7F6"
type ITensorVtbl* = object of IInspectableVtbl
  get_TensorKind*: proc(self: pointer, value: ptr TensorKind): HRESULT {.abi.}
  get_Shape*: proc(self: pointer, value: ptr pointer): HRESULT {.abi.}

## Windows.AI.MachineLearning.ITensorBoolean
const IID_ITensorBoolean* = guid"50F311ED-29E9-4A5C-A44D-8FC512584EED"
type ITensorBooleanVtbl* = object of IInspectableVtbl
  GetAsVectorView*: proc(self: pointer, value: ptr pointer): HRESULT {.abi.}

## Windows.AI.MachineLearning.ITensorBooleanStatics
const IID_ITensorBooleanStatics* = guid"2796862C-2357-49A7-B476-D0AA3DFE6866"
type ITensorBooleanStaticsVtbl* = object of IInspectableVtbl
  Create*: proc(self: pointer, value: ptr pointer): HRESULT {.abi.}
  Create2*: proc(self: pointer, a1: pointer, value: ptr pointer
                ): HRESULT {.abi.}
  CreateFromArray*: proc(self: pointer, a1: pointer, a2Size: uint32,
                         a2: ptr bool, value: ptr pointer): HRESULT {.abi.}
  CreateFromIterable*: proc(self: pointer, a1: pointer, a2: pointer,
                            value: ptr pointer): HRESULT {.abi.}

## Windows.AI.MachineLearning.ITensorBooleanStatics2
const IID_ITensorBooleanStatics2* = guid"A3A4A501-6A2D-52D7-B04B-C435BAEE0115"
type ITensorBooleanStatics2Vtbl* = object of IInspectableVtbl
  CreateFromShapeArrayAndDataArray*: proc(self: pointer, a1Size: uint32,
                                          a1: ptr int64, a2Size: uint32,
                                          a2: ptr bool, value: ptr pointer
                                         ): HRESULT {.abi.}
  CreateFromBuffer*: proc(self: pointer, a1Size: uint32, a1: ptr int64,
                          a2IBuffer: pointer, value: ptr pointer
                         ): HRESULT {.abi.}

## Windows.AI.MachineLearning.ITensorDouble
const IID_ITensorDouble* = guid"91E41252-7A8F-4F0E-A28F-9637FFC8A3D0"
type ITensorDoubleVtbl* = object of IInspectableVtbl
  GetAsVectorView*: proc(self: pointer, value: ptr pointer): HRESULT {.abi.}

## Windows.AI.MachineLearning.ITensorDoubleStatics
const IID_ITensorDoubleStatics* = guid"A86693C5-9538-44E7-A3CA-5DF374A5A70C"
type ITensorDoubleStaticsVtbl* = object of IInspectableVtbl
  Create*: proc(self: pointer, value: ptr pointer): HRESULT {.abi.}
  Create2*: proc(self: pointer, a1: pointer, value: ptr pointer
                ): HRESULT {.abi.}
  CreateFromArray*: proc(self: pointer, a1: pointer, a2Size: uint32,
                         a2: ptr float64, value: ptr pointer): HRESULT {.abi.}
  CreateFromIterable*: proc(self: pointer, a1: pointer, a2: pointer,
                            value: ptr pointer): HRESULT {.abi.}

## Windows.AI.MachineLearning.ITensorDoubleStatics2
const IID_ITensorDoubleStatics2* = guid"93A570DE-5E9A-5094-85C8-592C655E68AC"
type ITensorDoubleStatics2Vtbl* = object of IInspectableVtbl
  CreateFromShapeArrayAndDataArray*: proc(self: pointer, a1Size: uint32,
                                          a1: ptr int64, a2Size: uint32,
                                          a2: ptr float64, value: ptr pointer
                                         ): HRESULT {.abi.}
  CreateFromBuffer*: proc(self: pointer, a1Size: uint32, a1: ptr int64,
                          a2IBuffer: pointer, value: ptr pointer
                         ): HRESULT {.abi.}

## Windows.AI.MachineLearning.ITensorFeatureDescriptor
const IID_ITensorFeatureDescriptor* = guid"74455C80-946A-4310-A19C-EE0AF028FCE4"
type ITensorFeatureDescriptorVtbl* = object of IInspectableVtbl
  get_TensorKind*: proc(self: pointer, value: ptr TensorKind): HRESULT {.abi.}
  get_Shape*: proc(self: pointer, value: ptr pointer): HRESULT {.abi.}

## Windows.AI.MachineLearning.ITensorFloat
const IID_ITensorFloat* = guid"F2282D82-AA02-42C8-A0C8-DF1EFC9676E1"
type ITensorFloatVtbl* = object of IInspectableVtbl
  GetAsVectorView*: proc(self: pointer, value: ptr pointer): HRESULT {.abi.}

## Windows.AI.MachineLearning.ITensorFloat16Bit
const IID_ITensorFloat16Bit* = guid"0AB994FC-5B89-4C3C-B5E4-5282A5316C0A"
type ITensorFloat16BitVtbl* = object of IInspectableVtbl
  GetAsVectorView*: proc(self: pointer, value: ptr pointer): HRESULT {.abi.}

## Windows.AI.MachineLearning.ITensorFloat16BitStatics
const IID_ITensorFloat16BitStatics* = guid"A52DB6F5-318A-44D4-820B-0CDC7054A84A"
type ITensorFloat16BitStaticsVtbl* = object of IInspectableVtbl
  Create*: proc(self: pointer, value: ptr pointer): HRESULT {.abi.}
  Create2*: proc(self: pointer, a1: pointer, value: ptr pointer
                ): HRESULT {.abi.}
  CreateFromArray*: proc(self: pointer, a1: pointer, a2Size: uint32,
                         a2: ptr float32, value: ptr pointer): HRESULT {.abi.}
  CreateFromIterable*: proc(self: pointer, a1: pointer, a2: pointer,
                            value: ptr pointer): HRESULT {.abi.}

## Windows.AI.MachineLearning.ITensorFloat16BitStatics2
const IID_ITensorFloat16BitStatics2* = guid"68545726-2DC7-51BF-B470-0B344CC2A1BC"
type ITensorFloat16BitStatics2Vtbl* = object of IInspectableVtbl
  CreateFromShapeArrayAndDataArray*: proc(self: pointer, a1Size: uint32,
                                          a1: ptr int64, a2Size: uint32,
                                          a2: ptr float32, value: ptr pointer
                                         ): HRESULT {.abi.}
  CreateFromBuffer*: proc(self: pointer, a1Size: uint32, a1: ptr int64,
                          a2IBuffer: pointer, value: ptr pointer
                         ): HRESULT {.abi.}

## Windows.AI.MachineLearning.ITensorFloatStatics
const IID_ITensorFloatStatics* = guid"DBCD395B-3BA3-452F-B10D-3C135E573FA9"
type ITensorFloatStaticsVtbl* = object of IInspectableVtbl
  Create*: proc(self: pointer, value: ptr pointer): HRESULT {.abi.}
  Create2*: proc(self: pointer, a1: pointer, value: ptr pointer
                ): HRESULT {.abi.}
  CreateFromArray*: proc(self: pointer, a1: pointer, a2Size: uint32,
                         a2: ptr float32, value: ptr pointer): HRESULT {.abi.}
  CreateFromIterable*: proc(self: pointer, a1: pointer, a2: pointer,
                            value: ptr pointer): HRESULT {.abi.}

## Windows.AI.MachineLearning.ITensorFloatStatics2
const IID_ITensorFloatStatics2* = guid"24610BC1-5E44-5713-B281-8F4AD4D555E8"
type ITensorFloatStatics2Vtbl* = object of IInspectableVtbl
  CreateFromShapeArrayAndDataArray*: proc(self: pointer, a1Size: uint32,
                                          a1: ptr int64, a2Size: uint32,
                                          a2: ptr float32, value: ptr pointer
                                         ): HRESULT {.abi.}
  CreateFromBuffer*: proc(self: pointer, a1Size: uint32, a1: ptr int64,
                          a2IBuffer: pointer, value: ptr pointer
                         ): HRESULT {.abi.}

## Windows.AI.MachineLearning.ITensorInt16Bit
const IID_ITensorInt16Bit* = guid"98A32D39-E6D6-44AF-8AFA-BAEBC44DC020"
type ITensorInt16BitVtbl* = object of IInspectableVtbl
  GetAsVectorView*: proc(self: pointer, value: ptr pointer): HRESULT {.abi.}

## Windows.AI.MachineLearning.ITensorInt16BitStatics
const IID_ITensorInt16BitStatics* = guid"98646293-266E-4B1A-821F-E60D70898B91"
type ITensorInt16BitStaticsVtbl* = object of IInspectableVtbl
  Create*: proc(self: pointer, value: ptr pointer): HRESULT {.abi.}
  Create2*: proc(self: pointer, a1: pointer, value: ptr pointer
                ): HRESULT {.abi.}
  CreateFromArray*: proc(self: pointer, a1: pointer, a2Size: uint32,
                         a2: ptr int16, value: ptr pointer): HRESULT {.abi.}
  CreateFromIterable*: proc(self: pointer, a1: pointer, a2: pointer,
                            value: ptr pointer): HRESULT {.abi.}

## Windows.AI.MachineLearning.ITensorInt16BitStatics2
const IID_ITensorInt16BitStatics2* = guid"0CD70CF4-696C-5E5F-95D8-5EBF9670148B"
type ITensorInt16BitStatics2Vtbl* = object of IInspectableVtbl
  CreateFromShapeArrayAndDataArray*: proc(self: pointer, a1Size: uint32,
                                          a1: ptr int64, a2Size: uint32,
                                          a2: ptr int16, value: ptr pointer
                                         ): HRESULT {.abi.}
  CreateFromBuffer*: proc(self: pointer, a1Size: uint32, a1: ptr int64,
                          a2IBuffer: pointer, value: ptr pointer
                         ): HRESULT {.abi.}

## Windows.AI.MachineLearning.ITensorInt32Bit
const IID_ITensorInt32Bit* = guid"2C0C28D3-207C-4486-A7D2-884522C5E589"
type ITensorInt32BitVtbl* = object of IInspectableVtbl
  GetAsVectorView*: proc(self: pointer, value: ptr pointer): HRESULT {.abi.}

## Windows.AI.MachineLearning.ITensorInt32BitStatics
const IID_ITensorInt32BitStatics* = guid"6539864B-52FA-4E35-907C-834CAC417B50"
type ITensorInt32BitStaticsVtbl* = object of IInspectableVtbl
  Create*: proc(self: pointer, value: ptr pointer): HRESULT {.abi.}
  Create2*: proc(self: pointer, a1: pointer, value: ptr pointer
                ): HRESULT {.abi.}
  CreateFromArray*: proc(self: pointer, a1: pointer, a2Size: uint32,
                         a2: ptr int32, value: ptr pointer): HRESULT {.abi.}
  CreateFromIterable*: proc(self: pointer, a1: pointer, a2: pointer,
                            value: ptr pointer): HRESULT {.abi.}

## Windows.AI.MachineLearning.ITensorInt32BitStatics2
const IID_ITensorInt32BitStatics2* = guid"7C4B079A-E956-5CE0-A3BD-157D9D79B5EC"
type ITensorInt32BitStatics2Vtbl* = object of IInspectableVtbl
  CreateFromShapeArrayAndDataArray*: proc(self: pointer, a1Size: uint32,
                                          a1: ptr int64, a2Size: uint32,
                                          a2: ptr int32, value: ptr pointer
                                         ): HRESULT {.abi.}
  CreateFromBuffer*: proc(self: pointer, a1Size: uint32, a1: ptr int64,
                          a2IBuffer: pointer, value: ptr pointer
                         ): HRESULT {.abi.}

## Windows.AI.MachineLearning.ITensorInt64Bit
const IID_ITensorInt64Bit* = guid"499665BA-1FA2-45AD-AF25-A0BD9BDA4C87"
type ITensorInt64BitVtbl* = object of IInspectableVtbl
  GetAsVectorView*: proc(self: pointer, value: ptr pointer): HRESULT {.abi.}

## Windows.AI.MachineLearning.ITensorInt64BitStatics
const IID_ITensorInt64BitStatics* = guid"9648AD9D-1198-4D74-9517-783AB62B9CC2"
type ITensorInt64BitStaticsVtbl* = object of IInspectableVtbl
  Create*: proc(self: pointer, value: ptr pointer): HRESULT {.abi.}
  Create2*: proc(self: pointer, a1: pointer, value: ptr pointer
                ): HRESULT {.abi.}
  CreateFromArray*: proc(self: pointer, a1: pointer, a2Size: uint32,
                         a2: ptr int64, value: ptr pointer): HRESULT {.abi.}
  CreateFromIterable*: proc(self: pointer, a1: pointer, a2: pointer,
                            value: ptr pointer): HRESULT {.abi.}

## Windows.AI.MachineLearning.ITensorInt64BitStatics2
const IID_ITensorInt64BitStatics2* = guid"6D3D9DCB-FF40-5EC2-89FE-084E2B6BC6DB"
type ITensorInt64BitStatics2Vtbl* = object of IInspectableVtbl
  CreateFromShapeArrayAndDataArray*: proc(self: pointer, a1Size: uint32,
                                          a1: ptr int64, a2Size: uint32,
                                          a2: ptr int64, value: ptr pointer
                                         ): HRESULT {.abi.}
  CreateFromBuffer*: proc(self: pointer, a1Size: uint32, a1: ptr int64,
                          a2IBuffer: pointer, value: ptr pointer
                         ): HRESULT {.abi.}

## Windows.AI.MachineLearning.ITensorInt8Bit
const IID_ITensorInt8Bit* = guid"CDDD97C5-FFD8-4FEF-AEFB-30E1A485B2EE"
type ITensorInt8BitVtbl* = object of IInspectableVtbl
  GetAsVectorView*: proc(self: pointer, value: ptr pointer): HRESULT {.abi.}

## Windows.AI.MachineLearning.ITensorInt8BitStatics
const IID_ITensorInt8BitStatics* = guid"B1A12284-095C-4C76-A661-AC4CEE1F3E8B"
type ITensorInt8BitStaticsVtbl* = object of IInspectableVtbl
  Create*: proc(self: pointer, value: ptr pointer): HRESULT {.abi.}
  Create2*: proc(self: pointer, a1: pointer, value: ptr pointer
                ): HRESULT {.abi.}
  CreateFromArray*: proc(self: pointer, a1: pointer, a2Size: uint32,
                         a2: ptr uint8, value: ptr pointer): HRESULT {.abi.}
  CreateFromIterable*: proc(self: pointer, a1: pointer, a2: pointer,
                            value: ptr pointer): HRESULT {.abi.}

## Windows.AI.MachineLearning.ITensorInt8BitStatics2
const IID_ITensorInt8BitStatics2* = guid"C0D59637-C468-56FB-9535-C052BDB93DC0"
type ITensorInt8BitStatics2Vtbl* = object of IInspectableVtbl
  CreateFromShapeArrayAndDataArray*: proc(self: pointer, a1Size: uint32,
                                          a1: ptr int64, a2Size: uint32,
                                          a2: ptr uint8, value: ptr pointer
                                         ): HRESULT {.abi.}
  CreateFromBuffer*: proc(self: pointer, a1Size: uint32, a1: ptr int64,
                          a2IBuffer: pointer, value: ptr pointer
                         ): HRESULT {.abi.}

## Windows.AI.MachineLearning.ITensorString
const IID_ITensorString* = guid"582335C8-BDB1-4610-BC75-35E9CBF009B7"
type ITensorStringVtbl* = object of IInspectableVtbl
  GetAsVectorView*: proc(self: pointer, value: ptr pointer): HRESULT {.abi.}

## Windows.AI.MachineLearning.ITensorStringStatics
const IID_ITensorStringStatics* = guid"83623324-CF26-4F17-A2D4-20EF8D097D53"
type ITensorStringStaticsVtbl* = object of IInspectableVtbl
  Create*: proc(self: pointer, value: ptr pointer): HRESULT {.abi.}
  Create2*: proc(self: pointer, a1: pointer, value: ptr pointer
                ): HRESULT {.abi.}
  CreateFromArray*: proc(self: pointer, a1: pointer, a2Size: uint32,
                         a2: ptr HSTRING, value: ptr pointer): HRESULT {.abi.}
  CreateFromIterable*: proc(self: pointer, a1: pointer, a2: pointer,
                            value: ptr pointer): HRESULT {.abi.}

## Windows.AI.MachineLearning.ITensorStringStatics2
const IID_ITensorStringStatics2* = guid"9E355ED0-C8E2-5254-9137-0193A3668FD8"
type ITensorStringStatics2Vtbl* = object of IInspectableVtbl
  CreateFromShapeArrayAndDataArray*: proc(self: pointer, a1Size: uint32,
                                          a1: ptr int64, a2Size: uint32,
                                          a2: ptr HSTRING, value: ptr pointer
                                         ): HRESULT {.abi.}

## Windows.AI.MachineLearning.ITensorUInt16Bit
const IID_ITensorUInt16Bit* = guid"68140F4B-23C0-42F3-81F6-A891C011BC3F"
type ITensorUInt16BitVtbl* = object of IInspectableVtbl
  GetAsVectorView*: proc(self: pointer, value: ptr pointer): HRESULT {.abi.}

## Windows.AI.MachineLearning.ITensorUInt16BitStatics
const IID_ITensorUInt16BitStatics* = guid"5DF745DD-028A-481A-A27C-C7E6435E52DD"
type ITensorUInt16BitStaticsVtbl* = object of IInspectableVtbl
  Create*: proc(self: pointer, value: ptr pointer): HRESULT {.abi.}
  Create2*: proc(self: pointer, a1: pointer, value: ptr pointer
                ): HRESULT {.abi.}
  CreateFromArray*: proc(self: pointer, a1: pointer, a2Size: uint32,
                         a2: ptr uint16, value: ptr pointer): HRESULT {.abi.}
  CreateFromIterable*: proc(self: pointer, a1: pointer, a2: pointer,
                            value: ptr pointer): HRESULT {.abi.}

## Windows.AI.MachineLearning.ITensorUInt16BitStatics2
const IID_ITensorUInt16BitStatics2* = guid"8AF40C64-D69F-5315-9348-490877BBD642"
type ITensorUInt16BitStatics2Vtbl* = object of IInspectableVtbl
  CreateFromShapeArrayAndDataArray*: proc(self: pointer, a1Size: uint32,
                                          a1: ptr int64, a2Size: uint32,
                                          a2: ptr uint16, value: ptr pointer
                                         ): HRESULT {.abi.}
  CreateFromBuffer*: proc(self: pointer, a1Size: uint32, a1: ptr int64,
                          a2IBuffer: pointer, value: ptr pointer
                         ): HRESULT {.abi.}

## Windows.AI.MachineLearning.ITensorUInt32Bit
const IID_ITensorUInt32Bit* = guid"D8C9C2FF-7511-45A3-BFAC-C38F370D2237"
type ITensorUInt32BitVtbl* = object of IInspectableVtbl
  GetAsVectorView*: proc(self: pointer, value: ptr pointer): HRESULT {.abi.}

## Windows.AI.MachineLearning.ITensorUInt32BitStatics
const IID_ITensorUInt32BitStatics* = guid"417C3837-E773-4378-8E7F-0CC33DBEA697"
type ITensorUInt32BitStaticsVtbl* = object of IInspectableVtbl
  Create*: proc(self: pointer, value: ptr pointer): HRESULT {.abi.}
  Create2*: proc(self: pointer, a1: pointer, value: ptr pointer
                ): HRESULT {.abi.}
  CreateFromArray*: proc(self: pointer, a1: pointer, a2Size: uint32,
                         a2: ptr uint32, value: ptr pointer): HRESULT {.abi.}
  CreateFromIterable*: proc(self: pointer, a1: pointer, a2: pointer,
                            value: ptr pointer): HRESULT {.abi.}

## Windows.AI.MachineLearning.ITensorUInt32BitStatics2
const IID_ITensorUInt32BitStatics2* = guid"EF1A1F1C-314E-569D-B496-5C8447D20CD2"
type ITensorUInt32BitStatics2Vtbl* = object of IInspectableVtbl
  CreateFromShapeArrayAndDataArray*: proc(self: pointer, a1Size: uint32,
                                          a1: ptr int64, a2Size: uint32,
                                          a2: ptr uint32, value: ptr pointer
                                         ): HRESULT {.abi.}
  CreateFromBuffer*: proc(self: pointer, a1Size: uint32, a1: ptr int64,
                          a2IBuffer: pointer, value: ptr pointer
                         ): HRESULT {.abi.}

## Windows.AI.MachineLearning.ITensorUInt64Bit
const IID_ITensorUInt64Bit* = guid"2E70FFAD-04BF-4825-839A-82BAEF8C7886"
type ITensorUInt64BitVtbl* = object of IInspectableVtbl
  GetAsVectorView*: proc(self: pointer, value: ptr pointer): HRESULT {.abi.}

## Windows.AI.MachineLearning.ITensorUInt64BitStatics
const IID_ITensorUInt64BitStatics* = guid"7A7E20EB-242F-47CB-A9C6-F602ECFBFEE4"
type ITensorUInt64BitStaticsVtbl* = object of IInspectableVtbl
  Create*: proc(self: pointer, value: ptr pointer): HRESULT {.abi.}
  Create2*: proc(self: pointer, a1: pointer, value: ptr pointer
                ): HRESULT {.abi.}
  CreateFromArray*: proc(self: pointer, a1: pointer, a2Size: uint32,
                         a2: ptr uint64, value: ptr pointer): HRESULT {.abi.}
  CreateFromIterable*: proc(self: pointer, a1: pointer, a2: pointer,
                            value: ptr pointer): HRESULT {.abi.}

## Windows.AI.MachineLearning.ITensorUInt64BitStatics2
const IID_ITensorUInt64BitStatics2* = guid"085A687D-67E1-5B1E-B232-4FABE9CA20B3"
type ITensorUInt64BitStatics2Vtbl* = object of IInspectableVtbl
  CreateFromShapeArrayAndDataArray*: proc(self: pointer, a1Size: uint32,
                                          a1: ptr int64, a2Size: uint32,
                                          a2: ptr uint64, value: ptr pointer
                                         ): HRESULT {.abi.}
  CreateFromBuffer*: proc(self: pointer, a1Size: uint32, a1: ptr int64,
                          a2IBuffer: pointer, value: ptr pointer
                         ): HRESULT {.abi.}

## Windows.AI.MachineLearning.ITensorUInt8Bit
const IID_ITensorUInt8Bit* = guid"58E1AE27-622B-48E3-BE22-D867AED1DAAC"
type ITensorUInt8BitVtbl* = object of IInspectableVtbl
  GetAsVectorView*: proc(self: pointer, value: ptr pointer): HRESULT {.abi.}

## Windows.AI.MachineLearning.ITensorUInt8BitStatics
const IID_ITensorUInt8BitStatics* = guid"05F67583-BC24-4220-8A41-2DCD8C5ED33C"
type ITensorUInt8BitStaticsVtbl* = object of IInspectableVtbl
  Create*: proc(self: pointer, value: ptr pointer): HRESULT {.abi.}
  Create2*: proc(self: pointer, a1: pointer, value: ptr pointer
                ): HRESULT {.abi.}
  CreateFromArray*: proc(self: pointer, a1: pointer, a2Size: uint32,
                         a2: ptr uint8, value: ptr pointer): HRESULT {.abi.}
  CreateFromIterable*: proc(self: pointer, a1: pointer, a2: pointer,
                            value: ptr pointer): HRESULT {.abi.}

## Windows.AI.MachineLearning.ITensorUInt8BitStatics2
const IID_ITensorUInt8BitStatics2* = guid"2BA042D6-373E-5A3A-A2FC-A6C41BD52789"
type ITensorUInt8BitStatics2Vtbl* = object of IInspectableVtbl
  CreateFromShapeArrayAndDataArray*: proc(self: pointer, a1Size: uint32,
                                          a1: ptr int64, a2Size: uint32,
                                          a2: ptr uint8, value: ptr pointer
                                         ): HRESULT {.abi.}
  CreateFromBuffer*: proc(self: pointer, a1Size: uint32, a1: ptr int64,
                          a2IBuffer: pointer, value: ptr pointer
                         ): HRESULT {.abi.}

## Windows.AI.MachineLearning.Preview.IImageVariableDescriptorPreview
const IID_IImageVariableDescriptorPreview* = guid"7AE1FA72-029E-4DC5-A2F8-5FB763154150"
type IImageVariableDescriptorPreviewVtbl* = object of IInspectableVtbl
  get_BitmapPixelFormat*: proc(self: pointer, value: ptr BitmapPixelFormat
                              ): HRESULT {.abi.}
  get_Width*: proc(self: pointer, value: ptr uint32): HRESULT {.abi.}
  get_Height*: proc(self: pointer, value: ptr uint32): HRESULT {.abi.}

## Windows.AI.MachineLearning.Preview.IInferencingOptionsPreview
const IID_IInferencingOptionsPreview* = guid"47BC8205-4D36-47A9-8F68-FFCB339DD0FC"
type IInferencingOptionsPreviewVtbl* = object of IInspectableVtbl
  get_PreferredDeviceKind*: proc(self: pointer,
                                 value: ptr LearningModelDeviceKindPreview
                                ): HRESULT {.abi.}
  put_PreferredDeviceKind*: proc(self: pointer,
                                 a1: LearningModelDeviceKindPreview
                                ): HRESULT {.abi.}
  get_IsTracingEnabled*: proc(self: pointer, value: ptr bool): HRESULT {.abi.}
  put_IsTracingEnabled*: proc(self: pointer, a1: bool): HRESULT {.abi.}
  get_MaxBatchSize*: proc(self: pointer, value: ptr int32): HRESULT {.abi.}
  put_MaxBatchSize*: proc(self: pointer, a1: int32): HRESULT {.abi.}
  get_MinimizeMemoryAllocation*: proc(self: pointer, value: ptr bool
                                     ): HRESULT {.abi.}
  put_MinimizeMemoryAllocation*: proc(self: pointer, a1: bool
                                     ): HRESULT {.abi.}
  get_ReclaimMemoryAfterEvaluation*: proc(self: pointer, value: ptr bool
                                         ): HRESULT {.abi.}
  put_ReclaimMemoryAfterEvaluation*: proc(self: pointer, a1: bool
                                         ): HRESULT {.abi.}

## Windows.AI.MachineLearning.Preview.ILearningModelBindingPreview
const IID_ILearningModelBindingPreview* = guid"93C901E8-6C78-4B4F-AEC1-A6BB9E691624"
type ILearningModelBindingPreviewVtbl* = object of IInspectableVtbl
  `Bind`*: proc(self: pointer, a1: HSTRING, a2: pointer): HRESULT {.abi.}
  Bind2*: proc(self: pointer, a1: HSTRING, a2: pointer,
               a3IPropertySet: pointer): HRESULT {.abi.}
  Clear*: proc(self: pointer): HRESULT {.abi.}

## Windows.AI.MachineLearning.Preview.ILearningModelBindingPreviewFactory
const IID_ILearningModelBindingPreviewFactory* = guid"48B8219F-1E51-4D77-AE50-3EC164AD3480"
type ILearningModelBindingPreviewFactoryVtbl* = object of IInspectableVtbl
  CreateFromModel*: proc(self: pointer, a1LearningModelPreview: pointer,
                         value: ptr pointer): HRESULT {.abi.}

## Windows.AI.MachineLearning.Preview.ILearningModelDescriptionPreview
const IID_ILearningModelDescriptionPreview* = guid"F52C09C6-8611-40AD-8E59-DE3FD7030A40"
type ILearningModelDescriptionPreviewVtbl* = object of IInspectableVtbl
  get_Author*: proc(self: pointer, value: ptr HSTRING): HRESULT {.abi.}
  get_Name*: proc(self: pointer, value: ptr HSTRING): HRESULT {.abi.}
  get_Domain*: proc(self: pointer, value: ptr HSTRING): HRESULT {.abi.}
  get_Description*: proc(self: pointer, value: ptr HSTRING): HRESULT {.abi.}
  get_Version*: proc(self: pointer, value: ptr int64): HRESULT {.abi.}
  get_Metadata*: proc(self: pointer, value: ptr pointer): HRESULT {.abi.}
  get_InputFeatures*: proc(self: pointer, value: ptr pointer): HRESULT {.abi.}
  get_OutputFeatures*: proc(self: pointer, value: ptr pointer
                           ): HRESULT {.abi.}

## Windows.AI.MachineLearning.Preview.ILearningModelEvaluationResultPreview
const IID_ILearningModelEvaluationResultPreview* = guid"DF25EA9F-9863-4088-8498-87A1F4686F92"
type ILearningModelEvaluationResultPreviewVtbl* = object of IInspectableVtbl
  get_CorrelationId*: proc(self: pointer, value: ptr HSTRING): HRESULT {.abi.}
  get_Outputs*: proc(self: pointer, value: ptr pointer): HRESULT {.abi.}

## Windows.AI.MachineLearning.Preview.ILearningModelPreview
const IID_ILearningModelPreview* = guid"049C266A-93B4-478C-AEB8-70157BF0FF94"
type ILearningModelPreviewVtbl* = object of IInspectableVtbl
  EvaluateAsync*: proc(self: pointer, a1LearningModelBindingPreview: pointer,
                       a2: HSTRING, value: ptr pointer): HRESULT {.abi.}
  EvaluateFeaturesAsync*: proc(self: pointer, a1: pointer, a2: HSTRING,
                               value: ptr pointer): HRESULT {.abi.}
  get_Description*: proc(self: pointer, value: ptr pointer): HRESULT {.abi.}
  get_InferencingOptions*: proc(self: pointer, value: ptr pointer
                               ): HRESULT {.abi.}
  put_InferencingOptions*: proc(self: pointer,
                                a1InferencingOptionsPreview: pointer
                               ): HRESULT {.abi.}

## Windows.AI.MachineLearning.Preview.ILearningModelPreviewStatics
const IID_ILearningModelPreviewStatics* = guid"164BBB60-8465-4786-8B93-2C16A89289D7"
type ILearningModelPreviewStaticsVtbl* = object of IInspectableVtbl
  LoadModelFromStorageFileAsync*: proc(self: pointer, a1IStorageFile: pointer,
                                       value: ptr pointer): HRESULT {.abi.}
  LoadModelFromStreamAsync*: proc(self: pointer,
                                  a1IRandomAccessStreamReference: pointer,
                                  value: ptr pointer): HRESULT {.abi.}

## Windows.AI.MachineLearning.Preview.ILearningModelVariableDescriptorPreview
const IID_ILearningModelVariableDescriptorPreview* = guid"B13DF682-FC30-492B-8EA0-ED1F53C0B038"
type ILearningModelVariableDescriptorPreviewVtbl* = object of IInspectableVtbl
  get_Name*: proc(self: pointer, value: ptr HSTRING): HRESULT {.abi.}
  get_Description*: proc(self: pointer, value: ptr HSTRING): HRESULT {.abi.}
  get_ModelFeatureKind*: proc(self: pointer,
                              value: ptr LearningModelFeatureKindPreview
                             ): HRESULT {.abi.}
  get_IsRequired*: proc(self: pointer, value: ptr bool): HRESULT {.abi.}

## Windows.AI.MachineLearning.Preview.IMapVariableDescriptorPreview
const IID_IMapVariableDescriptorPreview* = guid"3CB38370-C02B-4236-B3E8-6BDCA49C3129"
type IMapVariableDescriptorPreviewVtbl* = object of IInspectableVtbl
  get_KeyKind*: proc(self: pointer, value: ptr FeatureElementKindPreview
                    ): HRESULT {.abi.}
  get_ValidStringKeys*: proc(self: pointer, value: ptr pointer
                            ): HRESULT {.abi.}
  get_ValidIntegerKeys*: proc(self: pointer, value: ptr pointer
                             ): HRESULT {.abi.}
  get_Fields*: proc(self: pointer, value: ptr pointer): HRESULT {.abi.}

## Windows.AI.MachineLearning.Preview.ISequenceVariableDescriptorPreview
const IID_ISequenceVariableDescriptorPreview* = guid"9CD8F292-98B2-4530-A1B6-2DED5FECBC26"
type ISequenceVariableDescriptorPreviewVtbl* = object of IInspectableVtbl
  get_ElementType*: proc(self: pointer, value: ptr pointer): HRESULT {.abi.}

## Windows.AI.MachineLearning.Preview.ITensorVariableDescriptorPreview
const IID_ITensorVariableDescriptorPreview* = guid"A80F501A-9AAC-4233-9784-ACEAF92510B5"
type ITensorVariableDescriptorPreviewVtbl* = object of IInspectableVtbl
  get_DataType*: proc(self: pointer, value: ptr FeatureElementKindPreview
                     ): HRESULT {.abi.}
  get_Shape*: proc(self: pointer, value: ptr pointer): HRESULT {.abi.}

