## Generated by tools/generate.nim - do not edit.
##
## Source: Windows.winmd
## Namespace: Windows.Foundation
##
## Each interface is its vtable: an object whose fields are the methods in
## declaration order, after IInspectable's six (IUnknown's three for a
## delegate). Every method returns HRESULT and its declared return type
## becomes a trailing out-parameter. `IID_X`, beside it, is its IID.

import ../com
import ./types
export com, types
include ../abidef

## Windows.Foundation.AsyncActionCompletedHandler  (delegate)
const IID_AsyncActionCompletedHandler* = guid"A4ED5C81-76C9-40BD-8BE6-B1D90FB20AE7"
type AsyncActionCompletedHandlerVtbl* = object of IUnknownVtbl
  Invoke*: proc(self: pointer, a1IAsyncAction: pointer, a2: AsyncStatus
               ): HRESULT {.abi.}

## Windows.Foundation.Collections.IPropertySet
const IID_IPropertySet* = guid"8A43ED9F-F4E6-4421-ACF9-1DAB2986820C"
type IPropertySetVtbl* = object of IInspectableVtbl

## Windows.Foundation.Collections.IVectorChangedEventArgs
const IID_IVectorChangedEventArgs* = guid"575933DF-34FE-4480-AF15-07691F3D5D9B"
type IVectorChangedEventArgsVtbl* = object of IInspectableVtbl
  get_CollectionChange*: proc(self: pointer, value: ptr CollectionChange
                             ): HRESULT {.abi.}
  get_Index*: proc(self: pointer, value: ptr uint32): HRESULT {.abi.}

## Windows.Foundation.DeferralCompletedHandler  (delegate)
const IID_DeferralCompletedHandler* = guid"ED32A372-F3C8-4FAA-9CFB-470148DA3888"
type DeferralCompletedHandlerVtbl* = object of IUnknownVtbl
  Invoke*: proc(self: pointer): HRESULT {.abi.}

## Windows.Foundation.Diagnostics.IAsyncCausalityTracerStatics
const IID_IAsyncCausalityTracerStatics* = guid"50850B26-267E-451B-A890-AB6A370245EE"
type IAsyncCausalityTracerStaticsVtbl* = object of IInspectableVtbl
  TraceOperationCreation*: proc(self: pointer, a1: CausalityTraceLevel,
                                a2: CausalitySource, a3: GUID, a4: uint64,
                                a5: HSTRING, a6: uint64): HRESULT {.abi.}
  TraceOperationCompletion*: proc(self: pointer, a1: CausalityTraceLevel,
                                  a2: CausalitySource, a3: GUID, a4: uint64,
                                  a5: AsyncStatus): HRESULT {.abi.}
  TraceOperationRelation*: proc(self: pointer, a1: CausalityTraceLevel,
                                a2: CausalitySource, a3: GUID, a4: uint64,
                                a5: CausalityRelation): HRESULT {.abi.}
  TraceSynchronousWorkStart*: proc(self: pointer, a1: CausalityTraceLevel,
                                   a2: CausalitySource, a3: GUID, a4: uint64,
                                   a5: CausalitySynchronousWork
                                  ): HRESULT {.abi.}
  TraceSynchronousWorkCompletion*: proc(self: pointer,
                                        a1: CausalityTraceLevel,
                                        a2: CausalitySource,
                                        a3: CausalitySynchronousWork
                                       ): HRESULT {.abi.}
  add_TracingStatusChanged*: proc(self: pointer, a1: pointer,
                                  value: ptr EventRegistrationToken
                                 ): HRESULT {.abi.}
  remove_TracingStatusChanged*: proc(self: pointer, a1: EventRegistrationToken
                                    ): HRESULT {.abi.}

## Windows.Foundation.Diagnostics.IErrorDetails
const IID_IErrorDetails* = guid"378CBB01-2CC9-428F-8C55-2C990D463E8F"
type IErrorDetailsVtbl* = object of IInspectableVtbl
  get_Description*: proc(self: pointer, value: ptr HSTRING): HRESULT {.abi.}
  get_LongDescription*: proc(self: pointer, value: ptr HSTRING
                            ): HRESULT {.abi.}
  get_HelpUri*: proc(self: pointer, value: ptr pointer): HRESULT {.abi.}

## Windows.Foundation.Diagnostics.IErrorDetailsStatics
const IID_IErrorDetailsStatics* = guid"B7703750-0B1D-46C8-AA0E-4B8178E4FCE9"
type IErrorDetailsStaticsVtbl* = object of IInspectableVtbl
  CreateFromHResultAsync*: proc(self: pointer, a1: int32, value: ptr pointer
                               ): HRESULT {.abi.}

## Windows.Foundation.Diagnostics.IErrorReportingSettings
const IID_IErrorReportingSettings* = guid"16369792-B03E-4BA1-8BB8-D28F4AB4D2C0"
type IErrorReportingSettingsVtbl* = object of IInspectableVtbl
  SetErrorOptions*: proc(self: pointer, a1: ErrorOptions): HRESULT {.abi.}
  GetErrorOptions*: proc(self: pointer, value: ptr ErrorOptions
                        ): HRESULT {.abi.}

## Windows.Foundation.Diagnostics.IFileLoggingSession
const IID_IFileLoggingSession* = guid"24C74216-FED2-404C-895F-1F9699CB02F7"
type IFileLoggingSessionVtbl* = object of IInspectableVtbl
  get_Name*: proc(self: pointer, value: ptr HSTRING): HRESULT {.abi.}
  AddLoggingChannel*: proc(self: pointer, a1ILoggingChannel: pointer
                          ): HRESULT {.abi.}
  AddLoggingChannel2*: proc(self: pointer, a1ILoggingChannel: pointer,
                            a2: LoggingLevel): HRESULT {.abi.}
  RemoveLoggingChannel*: proc(self: pointer, a1ILoggingChannel: pointer
                             ): HRESULT {.abi.}
  CloseAndSaveToFileAsync*: proc(self: pointer, value: ptr pointer
                                ): HRESULT {.abi.}
  add_LogFileGenerated*: proc(self: pointer, a1: pointer,
                              value: ptr EventRegistrationToken
                             ): HRESULT {.abi.}
  remove_LogFileGenerated*: proc(self: pointer, a1: EventRegistrationToken
                                ): HRESULT {.abi.}

## Windows.Foundation.Diagnostics.IFileLoggingSessionFactory
const IID_IFileLoggingSessionFactory* = guid"EEA08DCE-8447-4DAA-9133-12EB46F697D4"
type IFileLoggingSessionFactoryVtbl* = object of IInspectableVtbl
  Create*: proc(self: pointer, a1: HSTRING, value: ptr pointer
               ): HRESULT {.abi.}

## Windows.Foundation.Diagnostics.ILogFileGeneratedEventArgs
const IID_ILogFileGeneratedEventArgs* = guid"269E976F-0D38-4C1A-B53F-B395D881DF84"
type ILogFileGeneratedEventArgsVtbl* = object of IInspectableVtbl
  get_File*: proc(self: pointer, value: ptr pointer): HRESULT {.abi.}

## Windows.Foundation.Diagnostics.ILoggingActivity
const IID_ILoggingActivity* = guid"BC032941-B766-4CB5-9848-97AC6BA6D60C"
type ILoggingActivityVtbl* = object of IInspectableVtbl
  get_Name*: proc(self: pointer, value: ptr HSTRING): HRESULT {.abi.}
  get_Id*: proc(self: pointer, value: ptr GUID): HRESULT {.abi.}

## Windows.Foundation.Diagnostics.ILoggingActivity2
const IID_ILoggingActivity2* = guid"26C29808-6322-456A-AF82-80C8642F178B"
type ILoggingActivity2Vtbl* = object of IInspectableVtbl
  get_Channel*: proc(self: pointer, value: ptr pointer): HRESULT {.abi.}
  StopActivity*: proc(self: pointer, a1: HSTRING): HRESULT {.abi.}
  StopActivity2*: proc(self: pointer, a1: HSTRING, a2LoggingFields: pointer
                      ): HRESULT {.abi.}
  StopActivity3*: proc(self: pointer, a1: HSTRING, a2LoggingFields: pointer,
                       a3LoggingOptions: pointer): HRESULT {.abi.}

## Windows.Foundation.Diagnostics.ILoggingActivityFactory
const IID_ILoggingActivityFactory* = guid"6B33B483-E10A-4C58-97D5-10FB451074FB"
type ILoggingActivityFactoryVtbl* = object of IInspectableVtbl
  CreateLoggingActivity*: proc(self: pointer, a1: HSTRING,
                               a2ILoggingChannel: pointer, value: ptr pointer
                              ): HRESULT {.abi.}
  CreateLoggingActivityWithLevel*: proc(self: pointer, a1: HSTRING,
                                        a2ILoggingChannel: pointer,
                                        a3: LoggingLevel, value: ptr pointer
                                       ): HRESULT {.abi.}

## Windows.Foundation.Diagnostics.ILoggingChannel
const IID_ILoggingChannel* = guid"E9A50343-11D7-4F01-B5CA-CF495278C0A8"
type ILoggingChannelVtbl* = object of IInspectableVtbl
  get_Name*: proc(self: pointer, value: ptr HSTRING): HRESULT {.abi.}
  get_Enabled*: proc(self: pointer, value: ptr bool): HRESULT {.abi.}
  get_Level*: proc(self: pointer, value: ptr LoggingLevel): HRESULT {.abi.}
  LogMessage*: proc(self: pointer, a1: HSTRING): HRESULT {.abi.}
  LogMessage2*: proc(self: pointer, a1: HSTRING, a2: LoggingLevel
                    ): HRESULT {.abi.}
  LogValuePair*: proc(self: pointer, a1: HSTRING, a2: int32): HRESULT {.abi.}
  LogValuePair2*: proc(self: pointer, a1: HSTRING, a2: int32, a3: LoggingLevel
                      ): HRESULT {.abi.}
  add_LoggingEnabled*: proc(self: pointer, a1: pointer,
                            value: ptr EventRegistrationToken
                           ): HRESULT {.abi.}
  remove_LoggingEnabled*: proc(self: pointer, a1: EventRegistrationToken
                              ): HRESULT {.abi.}

## Windows.Foundation.Diagnostics.ILoggingChannel2
const IID_ILoggingChannel2* = guid"9F4C3CF3-0BAC-45A5-9E33-BAF3F3A246A5"
type ILoggingChannel2Vtbl* = object of IInspectableVtbl
  get_Id*: proc(self: pointer, value: ptr GUID): HRESULT {.abi.}

## Windows.Foundation.Diagnostics.ILoggingChannelFactory
const IID_ILoggingChannelFactory* = guid"4EDC5B9C-AF80-4A9B-B0DC-398F9AE5207B"
type ILoggingChannelFactoryVtbl* = object of IInspectableVtbl
  Create*: proc(self: pointer, a1: HSTRING, value: ptr pointer
               ): HRESULT {.abi.}

## Windows.Foundation.Diagnostics.ILoggingChannelFactory2
const IID_ILoggingChannelFactory2* = guid"4C6EF5DD-3B27-4DC9-99F0-299C6E4603A1"
type ILoggingChannelFactory2Vtbl* = object of IInspectableVtbl
  CreateWithOptions*: proc(self: pointer, a1: HSTRING,
                           a2LoggingChannelOptions: pointer,
                           value: ptr pointer): HRESULT {.abi.}
  CreateWithOptionsAndId*: proc(self: pointer, a1: HSTRING,
                                a2LoggingChannelOptions: pointer, a3: GUID,
                                value: ptr pointer): HRESULT {.abi.}

## Windows.Foundation.Diagnostics.ILoggingChannelOptions
const IID_ILoggingChannelOptions* = guid"C3E847FF-0EBB-4A53-8C54-DEC24926CB2C"
type ILoggingChannelOptionsVtbl* = object of IInspectableVtbl
  get_Group*: proc(self: pointer, value: ptr GUID): HRESULT {.abi.}
  put_Group*: proc(self: pointer, a1: GUID): HRESULT {.abi.}

## Windows.Foundation.Diagnostics.ILoggingChannelOptionsFactory
const IID_ILoggingChannelOptionsFactory* = guid"A93151DA-7FAF-4191-8755-5E86DC65D896"
type ILoggingChannelOptionsFactoryVtbl* = object of IInspectableVtbl
  Create*: proc(self: pointer, a1: GUID, value: ptr pointer): HRESULT {.abi.}

## Windows.Foundation.Diagnostics.ILoggingFields
const IID_ILoggingFields* = guid"D7F6B7AF-762D-4579-83BD-52C23BC333BC"
type ILoggingFieldsVtbl* = object of IInspectableVtbl
  Clear*: proc(self: pointer): HRESULT {.abi.}
  BeginStruct*: proc(self: pointer, a1: HSTRING): HRESULT {.abi.}
  BeginStruct2*: proc(self: pointer, a1: HSTRING, a2: int32): HRESULT {.abi.}
  EndStruct*: proc(self: pointer): HRESULT {.abi.}
  AddEmpty*: proc(self: pointer, a1: HSTRING): HRESULT {.abi.}
  AddEmpty2*: proc(self: pointer, a1: HSTRING, a2: LoggingFieldFormat
                  ): HRESULT {.abi.}
  AddEmpty3*: proc(self: pointer, a1: HSTRING, a2: LoggingFieldFormat,
                   a3: int32): HRESULT {.abi.}
  AddUInt8*: proc(self: pointer, a1: HSTRING, a2: uint8): HRESULT {.abi.}
  AddUInt82*: proc(self: pointer, a1: HSTRING, a2: uint8,
                   a3: LoggingFieldFormat): HRESULT {.abi.}
  AddUInt83*: proc(self: pointer, a1: HSTRING, a2: uint8,
                   a3: LoggingFieldFormat, a4: int32): HRESULT {.abi.}
  AddUInt8Array*: proc(self: pointer, a1: HSTRING, a2Size: uint32,
                       a2: ptr uint8): HRESULT {.abi.}
  AddUInt8Array2*: proc(self: pointer, a1: HSTRING, a2Size: uint32,
                        a2: ptr uint8, a3: LoggingFieldFormat
                       ): HRESULT {.abi.}
  AddUInt8Array3*: proc(self: pointer, a1: HSTRING, a2Size: uint32,
                        a2: ptr uint8, a3: LoggingFieldFormat, a4: int32
                       ): HRESULT {.abi.}
  AddInt16*: proc(self: pointer, a1: HSTRING, a2: int16): HRESULT {.abi.}
  AddInt162*: proc(self: pointer, a1: HSTRING, a2: int16,
                   a3: LoggingFieldFormat): HRESULT {.abi.}
  AddInt163*: proc(self: pointer, a1: HSTRING, a2: int16,
                   a3: LoggingFieldFormat, a4: int32): HRESULT {.abi.}
  AddInt16Array*: proc(self: pointer, a1: HSTRING, a2Size: uint32,
                       a2: ptr int16): HRESULT {.abi.}
  AddInt16Array2*: proc(self: pointer, a1: HSTRING, a2Size: uint32,
                        a2: ptr int16, a3: LoggingFieldFormat
                       ): HRESULT {.abi.}
  AddInt16Array3*: proc(self: pointer, a1: HSTRING, a2Size: uint32,
                        a2: ptr int16, a3: LoggingFieldFormat, a4: int32
                       ): HRESULT {.abi.}
  AddUInt16*: proc(self: pointer, a1: HSTRING, a2: uint16): HRESULT {.abi.}
  AddUInt162*: proc(self: pointer, a1: HSTRING, a2: uint16,
                    a3: LoggingFieldFormat): HRESULT {.abi.}
  AddUInt163*: proc(self: pointer, a1: HSTRING, a2: uint16,
                    a3: LoggingFieldFormat, a4: int32): HRESULT {.abi.}
  AddUInt16Array*: proc(self: pointer, a1: HSTRING, a2Size: uint32,
                        a2: ptr uint16): HRESULT {.abi.}
  AddUInt16Array2*: proc(self: pointer, a1: HSTRING, a2Size: uint32,
                         a2: ptr uint16, a3: LoggingFieldFormat
                        ): HRESULT {.abi.}
  AddUInt16Array3*: proc(self: pointer, a1: HSTRING, a2Size: uint32,
                         a2: ptr uint16, a3: LoggingFieldFormat, a4: int32
                        ): HRESULT {.abi.}
  AddInt32*: proc(self: pointer, a1: HSTRING, a2: int32): HRESULT {.abi.}
  AddInt322*: proc(self: pointer, a1: HSTRING, a2: int32,
                   a3: LoggingFieldFormat): HRESULT {.abi.}
  AddInt323*: proc(self: pointer, a1: HSTRING, a2: int32,
                   a3: LoggingFieldFormat, a4: int32): HRESULT {.abi.}
  AddInt32Array*: proc(self: pointer, a1: HSTRING, a2Size: uint32,
                       a2: ptr int32): HRESULT {.abi.}
  AddInt32Array2*: proc(self: pointer, a1: HSTRING, a2Size: uint32,
                        a2: ptr int32, a3: LoggingFieldFormat
                       ): HRESULT {.abi.}
  AddInt32Array3*: proc(self: pointer, a1: HSTRING, a2Size: uint32,
                        a2: ptr int32, a3: LoggingFieldFormat, a4: int32
                       ): HRESULT {.abi.}
  AddUInt32*: proc(self: pointer, a1: HSTRING, a2: uint32): HRESULT {.abi.}
  AddUInt322*: proc(self: pointer, a1: HSTRING, a2: uint32,
                    a3: LoggingFieldFormat): HRESULT {.abi.}
  AddUInt323*: proc(self: pointer, a1: HSTRING, a2: uint32,
                    a3: LoggingFieldFormat, a4: int32): HRESULT {.abi.}
  AddUInt32Array*: proc(self: pointer, a1: HSTRING, a2Size: uint32,
                        a2: ptr uint32): HRESULT {.abi.}
  AddUInt32Array2*: proc(self: pointer, a1: HSTRING, a2Size: uint32,
                         a2: ptr uint32, a3: LoggingFieldFormat
                        ): HRESULT {.abi.}
  AddUInt32Array3*: proc(self: pointer, a1: HSTRING, a2Size: uint32,
                         a2: ptr uint32, a3: LoggingFieldFormat, a4: int32
                        ): HRESULT {.abi.}
  AddInt64*: proc(self: pointer, a1: HSTRING, a2: int64): HRESULT {.abi.}
  AddInt642*: proc(self: pointer, a1: HSTRING, a2: int64,
                   a3: LoggingFieldFormat): HRESULT {.abi.}
  AddInt643*: proc(self: pointer, a1: HSTRING, a2: int64,
                   a3: LoggingFieldFormat, a4: int32): HRESULT {.abi.}
  AddInt64Array*: proc(self: pointer, a1: HSTRING, a2Size: uint32,
                       a2: ptr int64): HRESULT {.abi.}
  AddInt64Array2*: proc(self: pointer, a1: HSTRING, a2Size: uint32,
                        a2: ptr int64, a3: LoggingFieldFormat
                       ): HRESULT {.abi.}
  AddInt64Array3*: proc(self: pointer, a1: HSTRING, a2Size: uint32,
                        a2: ptr int64, a3: LoggingFieldFormat, a4: int32
                       ): HRESULT {.abi.}
  AddUInt64*: proc(self: pointer, a1: HSTRING, a2: uint64): HRESULT {.abi.}
  AddUInt642*: proc(self: pointer, a1: HSTRING, a2: uint64,
                    a3: LoggingFieldFormat): HRESULT {.abi.}
  AddUInt643*: proc(self: pointer, a1: HSTRING, a2: uint64,
                    a3: LoggingFieldFormat, a4: int32): HRESULT {.abi.}
  AddUInt64Array*: proc(self: pointer, a1: HSTRING, a2Size: uint32,
                        a2: ptr uint64): HRESULT {.abi.}
  AddUInt64Array2*: proc(self: pointer, a1: HSTRING, a2Size: uint32,
                         a2: ptr uint64, a3: LoggingFieldFormat
                        ): HRESULT {.abi.}
  AddUInt64Array3*: proc(self: pointer, a1: HSTRING, a2Size: uint32,
                         a2: ptr uint64, a3: LoggingFieldFormat, a4: int32
                        ): HRESULT {.abi.}
  AddSingle*: proc(self: pointer, a1: HSTRING, a2: float32): HRESULT {.abi.}
  AddSingle2*: proc(self: pointer, a1: HSTRING, a2: float32,
                    a3: LoggingFieldFormat): HRESULT {.abi.}
  AddSingle3*: proc(self: pointer, a1: HSTRING, a2: float32,
                    a3: LoggingFieldFormat, a4: int32): HRESULT {.abi.}
  AddSingleArray*: proc(self: pointer, a1: HSTRING, a2Size: uint32,
                        a2: ptr float32): HRESULT {.abi.}
  AddSingleArray2*: proc(self: pointer, a1: HSTRING, a2Size: uint32,
                         a2: ptr float32, a3: LoggingFieldFormat
                        ): HRESULT {.abi.}
  AddSingleArray3*: proc(self: pointer, a1: HSTRING, a2Size: uint32,
                         a2: ptr float32, a3: LoggingFieldFormat, a4: int32
                        ): HRESULT {.abi.}
  AddDouble*: proc(self: pointer, a1: HSTRING, a2: float64): HRESULT {.abi.}
  AddDouble2*: proc(self: pointer, a1: HSTRING, a2: float64,
                    a3: LoggingFieldFormat): HRESULT {.abi.}
  AddDouble3*: proc(self: pointer, a1: HSTRING, a2: float64,
                    a3: LoggingFieldFormat, a4: int32): HRESULT {.abi.}
  AddDoubleArray*: proc(self: pointer, a1: HSTRING, a2Size: uint32,
                        a2: ptr float64): HRESULT {.abi.}
  AddDoubleArray2*: proc(self: pointer, a1: HSTRING, a2Size: uint32,
                         a2: ptr float64, a3: LoggingFieldFormat
                        ): HRESULT {.abi.}
  AddDoubleArray3*: proc(self: pointer, a1: HSTRING, a2Size: uint32,
                         a2: ptr float64, a3: LoggingFieldFormat, a4: int32
                        ): HRESULT {.abi.}
  AddChar16*: proc(self: pointer, a1: HSTRING, a2: Char16): HRESULT {.abi.}
  AddChar162*: proc(self: pointer, a1: HSTRING, a2: Char16,
                    a3: LoggingFieldFormat): HRESULT {.abi.}
  AddChar163*: proc(self: pointer, a1: HSTRING, a2: Char16,
                    a3: LoggingFieldFormat, a4: int32): HRESULT {.abi.}
  AddChar16Array*: proc(self: pointer, a1: HSTRING, a2Size: uint32,
                        a2: ptr Char16): HRESULT {.abi.}
  AddChar16Array2*: proc(self: pointer, a1: HSTRING, a2Size: uint32,
                         a2: ptr Char16, a3: LoggingFieldFormat
                        ): HRESULT {.abi.}
  AddChar16Array3*: proc(self: pointer, a1: HSTRING, a2Size: uint32,
                         a2: ptr Char16, a3: LoggingFieldFormat, a4: int32
                        ): HRESULT {.abi.}
  AddBoolean*: proc(self: pointer, a1: HSTRING, a2: bool): HRESULT {.abi.}
  AddBoolean2*: proc(self: pointer, a1: HSTRING, a2: bool,
                     a3: LoggingFieldFormat): HRESULT {.abi.}
  AddBoolean3*: proc(self: pointer, a1: HSTRING, a2: bool,
                     a3: LoggingFieldFormat, a4: int32): HRESULT {.abi.}
  AddBooleanArray*: proc(self: pointer, a1: HSTRING, a2Size: uint32,
                         a2: ptr bool): HRESULT {.abi.}
  AddBooleanArray2*: proc(self: pointer, a1: HSTRING, a2Size: uint32,
                          a2: ptr bool, a3: LoggingFieldFormat
                         ): HRESULT {.abi.}
  AddBooleanArray3*: proc(self: pointer, a1: HSTRING, a2Size: uint32,
                          a2: ptr bool, a3: LoggingFieldFormat, a4: int32
                         ): HRESULT {.abi.}
  AddString*: proc(self: pointer, a1: HSTRING, a2: HSTRING): HRESULT {.abi.}
  AddString2*: proc(self: pointer, a1: HSTRING, a2: HSTRING,
                    a3: LoggingFieldFormat): HRESULT {.abi.}
  AddString3*: proc(self: pointer, a1: HSTRING, a2: HSTRING,
                    a3: LoggingFieldFormat, a4: int32): HRESULT {.abi.}
  AddStringArray*: proc(self: pointer, a1: HSTRING, a2Size: uint32,
                        a2: ptr HSTRING): HRESULT {.abi.}
  AddStringArray2*: proc(self: pointer, a1: HSTRING, a2Size: uint32,
                         a2: ptr HSTRING, a3: LoggingFieldFormat
                        ): HRESULT {.abi.}
  AddStringArray3*: proc(self: pointer, a1: HSTRING, a2Size: uint32,
                         a2: ptr HSTRING, a3: LoggingFieldFormat, a4: int32
                        ): HRESULT {.abi.}
  AddGuid*: proc(self: pointer, a1: HSTRING, a2: GUID): HRESULT {.abi.}
  AddGuid2*: proc(self: pointer, a1: HSTRING, a2: GUID, a3: LoggingFieldFormat
                 ): HRESULT {.abi.}
  AddGuid3*: proc(self: pointer, a1: HSTRING, a2: GUID,
                  a3: LoggingFieldFormat, a4: int32): HRESULT {.abi.}
  AddGuidArray*: proc(self: pointer, a1: HSTRING, a2Size: uint32, a2: ptr GUID
                     ): HRESULT {.abi.}
  AddGuidArray2*: proc(self: pointer, a1: HSTRING, a2Size: uint32,
                       a2: ptr GUID, a3: LoggingFieldFormat): HRESULT {.abi.}
  AddGuidArray3*: proc(self: pointer, a1: HSTRING, a2Size: uint32,
                       a2: ptr GUID, a3: LoggingFieldFormat, a4: int32
                      ): HRESULT {.abi.}
  AddDateTime*: proc(self: pointer, a1: HSTRING, a2: DateTime
                    ): HRESULT {.abi.}
  AddDateTime2*: proc(self: pointer, a1: HSTRING, a2: DateTime,
                      a3: LoggingFieldFormat): HRESULT {.abi.}
  AddDateTime3*: proc(self: pointer, a1: HSTRING, a2: DateTime,
                      a3: LoggingFieldFormat, a4: int32): HRESULT {.abi.}
  AddDateTimeArray*: proc(self: pointer, a1: HSTRING, a2Size: uint32,
                          a2: ptr DateTime): HRESULT {.abi.}
  AddDateTimeArray2*: proc(self: pointer, a1: HSTRING, a2Size: uint32,
                           a2: ptr DateTime, a3: LoggingFieldFormat
                          ): HRESULT {.abi.}
  AddDateTimeArray3*: proc(self: pointer, a1: HSTRING, a2Size: uint32,
                           a2: ptr DateTime, a3: LoggingFieldFormat, a4: int32
                          ): HRESULT {.abi.}
  AddTimeSpan*: proc(self: pointer, a1: HSTRING, a2: TimeSpan
                    ): HRESULT {.abi.}
  AddTimeSpan2*: proc(self: pointer, a1: HSTRING, a2: TimeSpan,
                      a3: LoggingFieldFormat): HRESULT {.abi.}
  AddTimeSpan3*: proc(self: pointer, a1: HSTRING, a2: TimeSpan,
                      a3: LoggingFieldFormat, a4: int32): HRESULT {.abi.}
  AddTimeSpanArray*: proc(self: pointer, a1: HSTRING, a2Size: uint32,
                          a2: ptr TimeSpan): HRESULT {.abi.}
  AddTimeSpanArray2*: proc(self: pointer, a1: HSTRING, a2Size: uint32,
                           a2: ptr TimeSpan, a3: LoggingFieldFormat
                          ): HRESULT {.abi.}
  AddTimeSpanArray3*: proc(self: pointer, a1: HSTRING, a2Size: uint32,
                           a2: ptr TimeSpan, a3: LoggingFieldFormat, a4: int32
                          ): HRESULT {.abi.}
  AddPoint*: proc(self: pointer, a1: HSTRING, a2: Point): HRESULT {.abi.}
  AddPoint2*: proc(self: pointer, a1: HSTRING, a2: Point,
                   a3: LoggingFieldFormat): HRESULT {.abi.}
  AddPoint3*: proc(self: pointer, a1: HSTRING, a2: Point,
                   a3: LoggingFieldFormat, a4: int32): HRESULT {.abi.}
  AddPointArray*: proc(self: pointer, a1: HSTRING, a2Size: uint32,
                       a2: ptr Point): HRESULT {.abi.}
  AddPointArray2*: proc(self: pointer, a1: HSTRING, a2Size: uint32,
                        a2: ptr Point, a3: LoggingFieldFormat
                       ): HRESULT {.abi.}
  AddPointArray3*: proc(self: pointer, a1: HSTRING, a2Size: uint32,
                        a2: ptr Point, a3: LoggingFieldFormat, a4: int32
                       ): HRESULT {.abi.}
  AddSize*: proc(self: pointer, a1: HSTRING, a2: Size): HRESULT {.abi.}
  AddSize2*: proc(self: pointer, a1: HSTRING, a2: Size, a3: LoggingFieldFormat
                 ): HRESULT {.abi.}
  AddSize3*: proc(self: pointer, a1: HSTRING, a2: Size,
                  a3: LoggingFieldFormat, a4: int32): HRESULT {.abi.}
  AddSizeArray*: proc(self: pointer, a1: HSTRING, a2Size: uint32, a2: ptr Size
                     ): HRESULT {.abi.}
  AddSizeArray2*: proc(self: pointer, a1: HSTRING, a2Size: uint32,
                       a2: ptr Size, a3: LoggingFieldFormat): HRESULT {.abi.}
  AddSizeArray3*: proc(self: pointer, a1: HSTRING, a2Size: uint32,
                       a2: ptr Size, a3: LoggingFieldFormat, a4: int32
                      ): HRESULT {.abi.}
  AddRect*: proc(self: pointer, a1: HSTRING, a2: Rect): HRESULT {.abi.}
  AddRect2*: proc(self: pointer, a1: HSTRING, a2: Rect, a3: LoggingFieldFormat
                 ): HRESULT {.abi.}
  AddRect3*: proc(self: pointer, a1: HSTRING, a2: Rect,
                  a3: LoggingFieldFormat, a4: int32): HRESULT {.abi.}
  AddRectArray*: proc(self: pointer, a1: HSTRING, a2Size: uint32, a2: ptr Rect
                     ): HRESULT {.abi.}
  AddRectArray2*: proc(self: pointer, a1: HSTRING, a2Size: uint32,
                       a2: ptr Rect, a3: LoggingFieldFormat): HRESULT {.abi.}
  AddRectArray3*: proc(self: pointer, a1: HSTRING, a2Size: uint32,
                       a2: ptr Rect, a3: LoggingFieldFormat, a4: int32
                      ): HRESULT {.abi.}

## Windows.Foundation.Diagnostics.ILoggingOptions
const IID_ILoggingOptions* = guid"90BC7850-0192-4F5D-AC26-006ADACA12D8"
type ILoggingOptionsVtbl* = object of IInspectableVtbl
  get_Keywords*: proc(self: pointer, value: ptr int64): HRESULT {.abi.}
  put_Keywords*: proc(self: pointer, a1: int64): HRESULT {.abi.}
  get_Tags*: proc(self: pointer, value: ptr int32): HRESULT {.abi.}
  put_Tags*: proc(self: pointer, a1: int32): HRESULT {.abi.}
  get_Task*: proc(self: pointer, value: ptr int16): HRESULT {.abi.}
  put_Task*: proc(self: pointer, a1: int16): HRESULT {.abi.}
  get_Opcode*: proc(self: pointer, value: ptr LoggingOpcode): HRESULT {.abi.}
  put_Opcode*: proc(self: pointer, a1: LoggingOpcode): HRESULT {.abi.}
  get_ActivityId*: proc(self: pointer, value: ptr GUID): HRESULT {.abi.}
  put_ActivityId*: proc(self: pointer, a1: GUID): HRESULT {.abi.}
  get_RelatedActivityId*: proc(self: pointer, value: ptr GUID
                              ): HRESULT {.abi.}
  put_RelatedActivityId*: proc(self: pointer, a1: GUID): HRESULT {.abi.}

## Windows.Foundation.Diagnostics.ILoggingOptionsFactory
const IID_ILoggingOptionsFactory* = guid"D713C6CB-98AB-464B-9F22-A3268478368A"
type ILoggingOptionsFactoryVtbl* = object of IInspectableVtbl
  CreateWithKeywords*: proc(self: pointer, a1: int64, value: ptr pointer
                           ): HRESULT {.abi.}

## Windows.Foundation.Diagnostics.ILoggingSession
const IID_ILoggingSession* = guid"6221F306-9380-4AD7-BAF5-41EA9310D768"
type ILoggingSessionVtbl* = object of IInspectableVtbl
  get_Name*: proc(self: pointer, value: ptr HSTRING): HRESULT {.abi.}
  SaveToFileAsync*: proc(self: pointer, a1IStorageFolder: pointer,
                         a2: HSTRING, value: ptr pointer): HRESULT {.abi.}
  AddLoggingChannel*: proc(self: pointer, a1ILoggingChannel: pointer
                          ): HRESULT {.abi.}
  AddLoggingChannel2*: proc(self: pointer, a1ILoggingChannel: pointer,
                            a2: LoggingLevel): HRESULT {.abi.}
  RemoveLoggingChannel*: proc(self: pointer, a1ILoggingChannel: pointer
                             ): HRESULT {.abi.}

## Windows.Foundation.Diagnostics.ILoggingSessionFactory
const IID_ILoggingSessionFactory* = guid"4E937EE5-58FD-45E0-8C2F-A132EFF95C1E"
type ILoggingSessionFactoryVtbl* = object of IInspectableVtbl
  Create*: proc(self: pointer, a1: HSTRING, value: ptr pointer
               ): HRESULT {.abi.}

## Windows.Foundation.Diagnostics.ILoggingTarget
const IID_ILoggingTarget* = guid"65F16C35-E388-4E26-B17A-F51CD3A83916"
type ILoggingTargetVtbl* = object of IInspectableVtbl
  IsEnabled*: proc(self: pointer, value: ptr bool): HRESULT {.abi.}
  IsEnabled2*: proc(self: pointer, a1: LoggingLevel, value: ptr bool
                   ): HRESULT {.abi.}
  IsEnabled3*: proc(self: pointer, a1: LoggingLevel, a2: int64,
                    value: ptr bool): HRESULT {.abi.}
  LogEvent*: proc(self: pointer, a1: HSTRING): HRESULT {.abi.}
  LogEvent2*: proc(self: pointer, a1: HSTRING, a2LoggingFields: pointer
                  ): HRESULT {.abi.}
  LogEvent3*: proc(self: pointer, a1: HSTRING, a2LoggingFields: pointer,
                   a3: LoggingLevel): HRESULT {.abi.}
  LogEvent4*: proc(self: pointer, a1: HSTRING, a2LoggingFields: pointer,
                   a3: LoggingLevel, a4LoggingOptions: pointer
                  ): HRESULT {.abi.}
  StartActivity*: proc(self: pointer, a1: HSTRING, value: ptr pointer
                      ): HRESULT {.abi.}
  StartActivity2*: proc(self: pointer, a1: HSTRING, a2LoggingFields: pointer,
                        value: ptr pointer): HRESULT {.abi.}
  StartActivity3*: proc(self: pointer, a1: HSTRING, a2LoggingFields: pointer,
                        a3: LoggingLevel, value: ptr pointer): HRESULT {.abi.}
  StartActivity4*: proc(self: pointer, a1: HSTRING, a2LoggingFields: pointer,
                        a3: LoggingLevel, a4LoggingOptions: pointer,
                        value: ptr pointer): HRESULT {.abi.}

## Windows.Foundation.Diagnostics.ITracingStatusChangedEventArgs
const IID_ITracingStatusChangedEventArgs* = guid"410B7711-FF3B-477F-9C9A-D2EFDA302DC3"
type ITracingStatusChangedEventArgsVtbl* = object of IInspectableVtbl
  get_Enabled*: proc(self: pointer, value: ptr bool): HRESULT {.abi.}
  get_TraceLevel*: proc(self: pointer, value: ptr CausalityTraceLevel
                       ): HRESULT {.abi.}

## Windows.Foundation.IAsyncAction
const IID_IAsyncAction* = guid"5A648006-843A-4DA9-865B-9D26E5DFAD7B"
type IAsyncActionVtbl* = object of IInspectableVtbl
  put_Completed*: proc(self: pointer, a1AsyncActionCompletedHandler: pointer
                      ): HRESULT {.abi.}
  get_Completed*: proc(self: pointer, value: ptr pointer): HRESULT {.abi.}
  GetResults*: proc(self: pointer): HRESULT {.abi.}

## Windows.Foundation.IAsyncInfo
const IID_IAsyncInfo* = guid"00000036-0000-0000-C000-000000000046"
type IAsyncInfoVtbl* = object of IInspectableVtbl
  get_Id*: proc(self: pointer, value: ptr uint32): HRESULT {.abi.}
  get_Status*: proc(self: pointer, value: ptr AsyncStatus): HRESULT {.abi.}
  get_ErrorCode*: proc(self: pointer, value: ptr HRESULT): HRESULT {.abi.}
  Cancel*: proc(self: pointer): HRESULT {.abi.}
  Close*: proc(self: pointer): HRESULT {.abi.}

## Windows.Foundation.IClosable
const IID_IClosable* = guid"30D5A829-7FA4-4026-83BB-D75BAE4EA99E"
type IClosableVtbl* = object of IInspectableVtbl
  Close*: proc(self: pointer): HRESULT {.abi.}

## Windows.Foundation.IDeferral
const IID_IDeferral* = guid"D6269732-3B7F-46A7-B40B-4FDCA2A2C693"
type IDeferralVtbl* = object of IInspectableVtbl
  Complete*: proc(self: pointer): HRESULT {.abi.}

## Windows.Foundation.IDeferralFactory
const IID_IDeferralFactory* = guid"65A1ECC5-3FB5-4832-8CA9-F061B281D13A"
type IDeferralFactoryVtbl* = object of IInspectableVtbl
  Create*: proc(self: pointer, a1DeferralCompletedHandler: pointer,
                value: ptr pointer): HRESULT {.abi.}

## Windows.Foundation.IGetActivationFactory
const IID_IGetActivationFactory* = guid"4EDB8EE2-96DD-49A7-94F7-4607DDAB8E3C"
type IGetActivationFactoryVtbl* = object of IInspectableVtbl
  GetActivationFactory*: proc(self: pointer, a1: HSTRING, value: ptr pointer
                             ): HRESULT {.abi.}

## Windows.Foundation.IGuidHelperStatics
const IID_IGuidHelperStatics* = guid"59C7966B-AE52-5283-AD7F-A1B9E9678ADD"
type IGuidHelperStaticsVtbl* = object of IInspectableVtbl
  CreateNewGuid*: proc(self: pointer, value: ptr GUID): HRESULT {.abi.}
  get_Empty*: proc(self: pointer, value: ptr GUID): HRESULT {.abi.}
  Equals*: proc(self: pointer, a1: ptr GUID, a2: ptr GUID, value: ptr bool
               ): HRESULT {.abi.}

## Windows.Foundation.IMemoryBuffer
const IID_IMemoryBuffer* = guid"FBC4DD2A-245B-11E4-AF98-689423260CF8"
type IMemoryBufferVtbl* = object of IInspectableVtbl
  CreateReference*: proc(self: pointer, value: ptr pointer): HRESULT {.abi.}

## Windows.Foundation.IMemoryBufferFactory
const IID_IMemoryBufferFactory* = guid"FBC4DD2B-245B-11E4-AF98-689423260CF8"
type IMemoryBufferFactoryVtbl* = object of IInspectableVtbl
  Create*: proc(self: pointer, a1: uint32, value: ptr pointer
               ): HRESULT {.abi.}

## Windows.Foundation.IMemoryBufferReference
const IID_IMemoryBufferReference* = guid"FBC4DD29-245B-11E4-AF98-689423260CF8"
type IMemoryBufferReferenceVtbl* = object of IInspectableVtbl
  get_Capacity*: proc(self: pointer, value: ptr uint32): HRESULT {.abi.}
  add_Closed*: proc(self: pointer, a1: pointer,
                    value: ptr EventRegistrationToken): HRESULT {.abi.}
  remove_Closed*: proc(self: pointer, a1: EventRegistrationToken
                      ): HRESULT {.abi.}

## Windows.Foundation.IPropertyValue
const IID_IPropertyValue* = guid"4BD682DD-7554-40E9-9A9B-82654EDE7E62"
type IPropertyValueVtbl* = object of IInspectableVtbl
  get_Type*: proc(self: pointer, value: ptr PropertyType): HRESULT {.abi.}
  get_IsNumericScalar*: proc(self: pointer, value: ptr bool): HRESULT {.abi.}
  GetUInt8*: proc(self: pointer, value: ptr uint8): HRESULT {.abi.}
  GetInt16*: proc(self: pointer, value: ptr int16): HRESULT {.abi.}
  GetUInt16*: proc(self: pointer, value: ptr uint16): HRESULT {.abi.}
  GetInt32*: proc(self: pointer, value: ptr int32): HRESULT {.abi.}
  GetUInt32*: proc(self: pointer, value: ptr uint32): HRESULT {.abi.}
  GetInt64*: proc(self: pointer, value: ptr int64): HRESULT {.abi.}
  GetUInt64*: proc(self: pointer, value: ptr uint64): HRESULT {.abi.}
  GetSingle*: proc(self: pointer, value: ptr float32): HRESULT {.abi.}
  GetDouble*: proc(self: pointer, value: ptr float64): HRESULT {.abi.}
  GetChar16*: proc(self: pointer, value: ptr Char16): HRESULT {.abi.}
  GetBoolean*: proc(self: pointer, value: ptr bool): HRESULT {.abi.}
  GetString*: proc(self: pointer, value: ptr HSTRING): HRESULT {.abi.}
  GetGuid*: proc(self: pointer, value: ptr GUID): HRESULT {.abi.}
  GetDateTime*: proc(self: pointer, value: ptr DateTime): HRESULT {.abi.}
  GetTimeSpan*: proc(self: pointer, value: ptr TimeSpan): HRESULT {.abi.}
  GetPoint*: proc(self: pointer, value: ptr Point): HRESULT {.abi.}
  GetSize*: proc(self: pointer, value: ptr Size): HRESULT {.abi.}
  GetRect*: proc(self: pointer, value: ptr Rect): HRESULT {.abi.}
  GetUInt8Array*: proc(self: pointer, a1Size: ptr uint32, a1: ptr ptr uint8
                      ): HRESULT {.abi.}
  GetInt16Array*: proc(self: pointer, a1Size: ptr uint32, a1: ptr ptr int16
                      ): HRESULT {.abi.}
  GetUInt16Array*: proc(self: pointer, a1Size: ptr uint32, a1: ptr ptr uint16
                       ): HRESULT {.abi.}
  GetInt32Array*: proc(self: pointer, a1Size: ptr uint32, a1: ptr ptr int32
                      ): HRESULT {.abi.}
  GetUInt32Array*: proc(self: pointer, a1Size: ptr uint32, a1: ptr ptr uint32
                       ): HRESULT {.abi.}
  GetInt64Array*: proc(self: pointer, a1Size: ptr uint32, a1: ptr ptr int64
                      ): HRESULT {.abi.}
  GetUInt64Array*: proc(self: pointer, a1Size: ptr uint32, a1: ptr ptr uint64
                       ): HRESULT {.abi.}
  GetSingleArray*: proc(self: pointer, a1Size: ptr uint32, a1: ptr ptr float32
                       ): HRESULT {.abi.}
  GetDoubleArray*: proc(self: pointer, a1Size: ptr uint32, a1: ptr ptr float64
                       ): HRESULT {.abi.}
  GetChar16Array*: proc(self: pointer, a1Size: ptr uint32, a1: ptr ptr Char16
                       ): HRESULT {.abi.}
  GetBooleanArray*: proc(self: pointer, a1Size: ptr uint32, a1: ptr ptr bool
                        ): HRESULT {.abi.}
  GetStringArray*: proc(self: pointer, a1Size: ptr uint32, a1: ptr ptr HSTRING
                       ): HRESULT {.abi.}
  GetInspectableArray*: proc(self: pointer, a1Size: ptr uint32,
                             a1: ptr ptr pointer): HRESULT {.abi.}
  GetGuidArray*: proc(self: pointer, a1Size: ptr uint32, a1: ptr ptr GUID
                     ): HRESULT {.abi.}
  GetDateTimeArray*: proc(self: pointer, a1Size: ptr uint32,
                          a1: ptr ptr DateTime): HRESULT {.abi.}
  GetTimeSpanArray*: proc(self: pointer, a1Size: ptr uint32,
                          a1: ptr ptr TimeSpan): HRESULT {.abi.}
  GetPointArray*: proc(self: pointer, a1Size: ptr uint32, a1: ptr ptr Point
                      ): HRESULT {.abi.}
  GetSizeArray*: proc(self: pointer, a1Size: ptr uint32, a1: ptr ptr Size
                     ): HRESULT {.abi.}
  GetRectArray*: proc(self: pointer, a1Size: ptr uint32, a1: ptr ptr Rect
                     ): HRESULT {.abi.}

## Windows.Foundation.IPropertyValueStatics
const IID_IPropertyValueStatics* = guid"629BDBC8-D932-4FF4-96B9-8D96C5C1E858"
type IPropertyValueStaticsVtbl* = object of IInspectableVtbl
  CreateEmpty*: proc(self: pointer, value: ptr pointer): HRESULT {.abi.}
  CreateUInt8*: proc(self: pointer, a1: uint8, value: ptr pointer
                    ): HRESULT {.abi.}
  CreateInt16*: proc(self: pointer, a1: int16, value: ptr pointer
                    ): HRESULT {.abi.}
  CreateUInt16*: proc(self: pointer, a1: uint16, value: ptr pointer
                     ): HRESULT {.abi.}
  CreateInt32*: proc(self: pointer, a1: int32, value: ptr pointer
                    ): HRESULT {.abi.}
  CreateUInt32*: proc(self: pointer, a1: uint32, value: ptr pointer
                     ): HRESULT {.abi.}
  CreateInt64*: proc(self: pointer, a1: int64, value: ptr pointer
                    ): HRESULT {.abi.}
  CreateUInt64*: proc(self: pointer, a1: uint64, value: ptr pointer
                     ): HRESULT {.abi.}
  CreateSingle*: proc(self: pointer, a1: float32, value: ptr pointer
                     ): HRESULT {.abi.}
  CreateDouble*: proc(self: pointer, a1: float64, value: ptr pointer
                     ): HRESULT {.abi.}
  CreateChar16*: proc(self: pointer, a1: Char16, value: ptr pointer
                     ): HRESULT {.abi.}
  CreateBoolean*: proc(self: pointer, a1: bool, value: ptr pointer
                      ): HRESULT {.abi.}
  CreateString*: proc(self: pointer, a1: HSTRING, value: ptr pointer
                     ): HRESULT {.abi.}
  CreateInspectable*: proc(self: pointer, a1: pointer, value: ptr pointer
                          ): HRESULT {.abi.}
  CreateGuid*: proc(self: pointer, a1: GUID, value: ptr pointer
                   ): HRESULT {.abi.}
  CreateDateTime*: proc(self: pointer, a1: DateTime, value: ptr pointer
                       ): HRESULT {.abi.}
  CreateTimeSpan*: proc(self: pointer, a1: TimeSpan, value: ptr pointer
                       ): HRESULT {.abi.}
  CreatePoint*: proc(self: pointer, a1: Point, value: ptr pointer
                    ): HRESULT {.abi.}
  CreateSize*: proc(self: pointer, a1: Size, value: ptr pointer
                   ): HRESULT {.abi.}
  CreateRect*: proc(self: pointer, a1: Rect, value: ptr pointer
                   ): HRESULT {.abi.}
  CreateUInt8Array*: proc(self: pointer, a1Size: uint32, a1: ptr uint8,
                          value: ptr pointer): HRESULT {.abi.}
  CreateInt16Array*: proc(self: pointer, a1Size: uint32, a1: ptr int16,
                          value: ptr pointer): HRESULT {.abi.}
  CreateUInt16Array*: proc(self: pointer, a1Size: uint32, a1: ptr uint16,
                           value: ptr pointer): HRESULT {.abi.}
  CreateInt32Array*: proc(self: pointer, a1Size: uint32, a1: ptr int32,
                          value: ptr pointer): HRESULT {.abi.}
  CreateUInt32Array*: proc(self: pointer, a1Size: uint32, a1: ptr uint32,
                           value: ptr pointer): HRESULT {.abi.}
  CreateInt64Array*: proc(self: pointer, a1Size: uint32, a1: ptr int64,
                          value: ptr pointer): HRESULT {.abi.}
  CreateUInt64Array*: proc(self: pointer, a1Size: uint32, a1: ptr uint64,
                           value: ptr pointer): HRESULT {.abi.}
  CreateSingleArray*: proc(self: pointer, a1Size: uint32, a1: ptr float32,
                           value: ptr pointer): HRESULT {.abi.}
  CreateDoubleArray*: proc(self: pointer, a1Size: uint32, a1: ptr float64,
                           value: ptr pointer): HRESULT {.abi.}
  CreateChar16Array*: proc(self: pointer, a1Size: uint32, a1: ptr Char16,
                           value: ptr pointer): HRESULT {.abi.}
  CreateBooleanArray*: proc(self: pointer, a1Size: uint32, a1: ptr bool,
                            value: ptr pointer): HRESULT {.abi.}
  CreateStringArray*: proc(self: pointer, a1Size: uint32, a1: ptr HSTRING,
                           value: ptr pointer): HRESULT {.abi.}
  CreateInspectableArray*: proc(self: pointer, a1Size: uint32,
                                a1: ptr pointer, value: ptr pointer
                               ): HRESULT {.abi.}
  CreateGuidArray*: proc(self: pointer, a1Size: uint32, a1: ptr GUID,
                         value: ptr pointer): HRESULT {.abi.}
  CreateDateTimeArray*: proc(self: pointer, a1Size: uint32, a1: ptr DateTime,
                             value: ptr pointer): HRESULT {.abi.}
  CreateTimeSpanArray*: proc(self: pointer, a1Size: uint32, a1: ptr TimeSpan,
                             value: ptr pointer): HRESULT {.abi.}
  CreatePointArray*: proc(self: pointer, a1Size: uint32, a1: ptr Point,
                          value: ptr pointer): HRESULT {.abi.}
  CreateSizeArray*: proc(self: pointer, a1Size: uint32, a1: ptr Size,
                         value: ptr pointer): HRESULT {.abi.}
  CreateRectArray*: proc(self: pointer, a1Size: uint32, a1: ptr Rect,
                         value: ptr pointer): HRESULT {.abi.}

## Windows.Foundation.IStringable
const IID_IStringable* = guid"96369F54-8EB6-48F0-ABCE-C1B211E627C3"
type IStringableVtbl* = object of IInspectableVtbl
  ToString*: proc(self: pointer, value: ptr HSTRING): HRESULT {.abi.}

## Windows.Foundation.IUriEscapeStatics
const IID_IUriEscapeStatics* = guid"C1D432BA-C824-4452-A7FD-512BC3BBE9A1"
type IUriEscapeStaticsVtbl* = object of IInspectableVtbl
  UnescapeComponent*: proc(self: pointer, a1: HSTRING, value: ptr HSTRING
                          ): HRESULT {.abi.}
  EscapeComponent*: proc(self: pointer, a1: HSTRING, value: ptr HSTRING
                        ): HRESULT {.abi.}

## Windows.Foundation.IUriRuntimeClass
const IID_IUriRuntimeClass* = guid"9E365E57-48B2-4160-956F-C7385120BBFC"
type IUriRuntimeClassVtbl* = object of IInspectableVtbl
  get_AbsoluteUri*: proc(self: pointer, value: ptr HSTRING): HRESULT {.abi.}
  get_DisplayUri*: proc(self: pointer, value: ptr HSTRING): HRESULT {.abi.}
  get_Domain*: proc(self: pointer, value: ptr HSTRING): HRESULT {.abi.}
  get_Extension*: proc(self: pointer, value: ptr HSTRING): HRESULT {.abi.}
  get_Fragment*: proc(self: pointer, value: ptr HSTRING): HRESULT {.abi.}
  get_Host*: proc(self: pointer, value: ptr HSTRING): HRESULT {.abi.}
  get_Password*: proc(self: pointer, value: ptr HSTRING): HRESULT {.abi.}
  get_Path*: proc(self: pointer, value: ptr HSTRING): HRESULT {.abi.}
  get_Query*: proc(self: pointer, value: ptr HSTRING): HRESULT {.abi.}
  get_QueryParsed*: proc(self: pointer, value: ptr pointer): HRESULT {.abi.}
  get_RawUri*: proc(self: pointer, value: ptr HSTRING): HRESULT {.abi.}
  get_SchemeName*: proc(self: pointer, value: ptr HSTRING): HRESULT {.abi.}
  get_UserName*: proc(self: pointer, value: ptr HSTRING): HRESULT {.abi.}
  get_Port*: proc(self: pointer, value: ptr int32): HRESULT {.abi.}
  get_Suspicious*: proc(self: pointer, value: ptr bool): HRESULT {.abi.}
  Equals*: proc(self: pointer, a1Uri: pointer, value: ptr bool
               ): HRESULT {.abi.}
  CombineUri*: proc(self: pointer, a1: HSTRING, value: ptr pointer
                   ): HRESULT {.abi.}

## Windows.Foundation.IUriRuntimeClassFactory
const IID_IUriRuntimeClassFactory* = guid"44A9796F-723E-4FDF-A218-033E75B0C084"
type IUriRuntimeClassFactoryVtbl* = object of IInspectableVtbl
  CreateUri*: proc(self: pointer, a1: HSTRING, value: ptr pointer
                  ): HRESULT {.abi.}
  CreateWithRelativeUri*: proc(self: pointer, a1: HSTRING, a2: HSTRING,
                               value: ptr pointer): HRESULT {.abi.}

## Windows.Foundation.IUriRuntimeClassWithAbsoluteCanonicalUri
const IID_IUriRuntimeClassWithAbsoluteCanonicalUri* = guid"758D9661-221C-480F-A339-50656673F46F"
type IUriRuntimeClassWithAbsoluteCanonicalUriVtbl* = object of IInspectableVtbl
  get_AbsoluteCanonicalUri*: proc(self: pointer, value: ptr HSTRING
                                 ): HRESULT {.abi.}
  get_DisplayIri*: proc(self: pointer, value: ptr HSTRING): HRESULT {.abi.}

## Windows.Foundation.IWwwFormUrlDecoderEntry
const IID_IWwwFormUrlDecoderEntry* = guid"125E7431-F678-4E8E-B670-20A9B06C512D"
type IWwwFormUrlDecoderEntryVtbl* = object of IInspectableVtbl
  get_Name*: proc(self: pointer, value: ptr HSTRING): HRESULT {.abi.}
  get_Value*: proc(self: pointer, value: ptr HSTRING): HRESULT {.abi.}

## Windows.Foundation.IWwwFormUrlDecoderRuntimeClass
const IID_IWwwFormUrlDecoderRuntimeClass* = guid"D45A0451-F225-4542-9296-0E1DF5D254DF"
type IWwwFormUrlDecoderRuntimeClassVtbl* = object of IInspectableVtbl
  GetFirstValueByName*: proc(self: pointer, a1: HSTRING, value: ptr HSTRING
                            ): HRESULT {.abi.}

## Windows.Foundation.IWwwFormUrlDecoderRuntimeClassFactory
const IID_IWwwFormUrlDecoderRuntimeClassFactory* = guid"5B8C6B3D-24AE-41B5-A1BF-F0C3D544845B"
type IWwwFormUrlDecoderRuntimeClassFactoryVtbl* = object of IInspectableVtbl
  CreateWwwFormUrlDecoder*: proc(self: pointer, a1: HSTRING,
                                 value: ptr pointer): HRESULT {.abi.}

## Windows.Foundation.Metadata.IApiInformationStatics
const IID_IApiInformationStatics* = guid"997439FE-F681-4A11-B416-C13A47E8BA36"
type IApiInformationStaticsVtbl* = object of IInspectableVtbl
  IsTypePresent*: proc(self: pointer, a1: HSTRING, value: ptr bool
                      ): HRESULT {.abi.}
  IsMethodPresent*: proc(self: pointer, a1: HSTRING, a2: HSTRING,
                         value: ptr bool): HRESULT {.abi.}
  IsMethodPresent2*: proc(self: pointer, a1: HSTRING, a2: HSTRING, a3: uint32,
                          value: ptr bool): HRESULT {.abi.}
  IsEventPresent*: proc(self: pointer, a1: HSTRING, a2: HSTRING,
                        value: ptr bool): HRESULT {.abi.}
  IsPropertyPresent*: proc(self: pointer, a1: HSTRING, a2: HSTRING,
                           value: ptr bool): HRESULT {.abi.}
  IsReadOnlyPropertyPresent*: proc(self: pointer, a1: HSTRING, a2: HSTRING,
                                   value: ptr bool): HRESULT {.abi.}
  IsWriteablePropertyPresent*: proc(self: pointer, a1: HSTRING, a2: HSTRING,
                                    value: ptr bool): HRESULT {.abi.}
  IsEnumNamedValuePresent*: proc(self: pointer, a1: HSTRING, a2: HSTRING,
                                 value: ptr bool): HRESULT {.abi.}
  IsApiContractPresent*: proc(self: pointer, a1: HSTRING, a2: uint16,
                              value: ptr bool): HRESULT {.abi.}
  IsApiContractPresent2*: proc(self: pointer, a1: HSTRING, a2: uint16,
                               a3: uint16, value: ptr bool): HRESULT {.abi.}

