## Generated by tools/wrappers.nim - do not edit.
##
## Source:    Windows.winmd
## Namespace: Windows.Perception
##
## Each class is a Nim object in a real inheritance chain, so an
## inherited method resolves without being emitted again for every
## subclass, and a derived value passes where a base is expected.

import ./core
import ./abi/[types, foundation, perception, storage, system]
import ./[classes, delegate, asyncops, seqview, mapview]
export core, types, foundation, perception, storage, system, classes, asyncops

# IIDs of parameterised interfaces, computed from a signature
# string rather than read from metadata - see tools/piid.nim.
const IID_IReference_1_SpatialRay* = guid"44DD686B-C7D8-582C-91C2-D98E604DCFD4"
const IID_AsyncOperationCompletedHandler_1_GazeInputAccessStatus* = guid"27A0F2C4-461F-50AB-AF8F-D9D99F30B67D"
const IID_IAsyncOperation_1_GazeInputAccessStatus* = guid"5764EB43-DB4F-5FEA-9BC5-AF0158F26929"
const IID_TypedEventHandler_2_SpatialAnchor_SpatialAnchorRawCoordinateSystemAdjustedEventArgs* = guid"FA43F9E4-3558-59C8-9A77-6E8B765ADCC8"
const IID_AsyncOperationCompletedHandler_1_SpatialAnchorExportSufficiency* = guid"4B6593D2-11A8-513E-838D-4226FB1E3C1F"
const IID_IAsyncOperation_1_SpatialAnchorExportSufficiency* = guid"260957B8-5B76-5159-8DC5-E03D74AA5F3D"
const IID_AsyncOperationCompletedHandler_1_Bool* = guid"C1D3D1A2-AE17-5A5F-B5A2-BDCC8844889A"
const IID_IAsyncOperation_1_Bool* = guid"CDB5EFB3-5788-509D-9BE1-71CCB8A3362A"
const IID_AsyncOperationCompletedHandler_1_SpatialPerceptionAccessStatus* = guid"6CED54C8-7689-525A-80E1-956A9D85CD83"
const IID_IAsyncOperation_1_SpatialPerceptionAccessStatus* = guid"B425D126-1069-563F-A863-44A30A8F071D"
const IID_AsyncOperationCompletedHandler_1_SpatialAnchorStore* = guid"84C21A3A-037A-503F-8006-AB577B7F6F66"
const IID_IAsyncOperation_1_SpatialAnchorStore* = guid"1CD05E51-1457-5023-8F5D-FE5E5A953423"
const IID_IKeyValuePair_2_String_SpatialAnchor* = guid"627298E7-068D-53F6-9154-D7D8D8091463"
const IID_IIterable_1_IKeyValuePair_2* = guid"55F0FA8A-AFD4-5541-A1C3-36F12147D606"
const IID_AsyncOperationCompletedHandler_1_IMapView_2* = guid"3A950AA3-9C65-586E-AF75-1ACF07190E90"
const IID_IAsyncOperation_1_IMapView_2* = guid"BBE07728-DA33-52C5-AAE0-A5E74CDF0471"
const IID_IIterator_1_IKeyValuePair_2* = guid"67A5F318-0232-5900-AC7E-5C647D731CBC"
const IID_IMapView_2_String_SpatialAnchor* = guid"2D344564-21B1-5470-B013-488CDDE45C48"
const IID_IMap_2_String_SpatialAnchor* = guid"25298593-9BAF-5A73-A1B6-CD5E40A5E834"
const IID_IReference_1_Matrix4x4* = guid"DACBFFDC-68EF-5FD0-B657-782D0AC9807E"
const IID_TypedEventHandler_2_SpatialEntityWatcher_SpatialEntityAddedEventArgs* = guid"F8EDAE01-6A30-52CC-B543-8ABDB26529B4"
const IID_TypedEventHandler_2_SpatialEntityWatcher_SpatialEntityUpdatedEventArgs* = guid"A15FD0C0-8A0A-5A7D-897A-F206CC509190"
const IID_TypedEventHandler_2_SpatialEntityWatcher_SpatialEntityRemovedEventArgs* = guid"36F982AD-EAA2-5263-861E-2ACF030C9E17"
const IID_TypedEventHandler_2_SpatialEntityWatcher_Object* = guid"50171823-30A9-5938-9F3B-358D86169F2E"
const IID_TypedEventHandler_2_SpatialLocator_Object* = guid"DBB08AB5-6B40-55FB-83D3-50D5373A3B20"
const IID_TypedEventHandler_2_SpatialLocator_SpatialLocatorPositionalTrackingDeactivatingEventArgs* = guid"34BF236C-E5D6-501F-8693-BC1D8D431D7E"
const IID_IReference_1_F8* = guid"2F2D6C29-5473-5F3E-92E7-96572BB990E2"
const IID_EventHandler_1_Object* = guid"C50898F6-C536-5F47-8583-8B2C2438A13B"
const IID_AsyncOperationCompletedHandler_1_SpatialStageFrameOfReference* = guid"FBB7E9FB-E49A-54E1-8C83-D1A87E4D2304"
const IID_IAsyncOperation_1_SpatialStageFrameOfReference* = guid"B4D8B1BF-1D66-5458-A5DF-3F4F6C366C58"
const IID_IReference_1_SpatialBoundingOrientedBox* = guid"09F88309-9F81-5207-BDB2-ABEF926DB18F"
const IID_AsyncOperationCompletedHandler_1_SpatialSurfaceMesh* = guid"4680F7F6-44C5-5FC6-8D51-D6962915FA23"
const IID_IAsyncOperation_1_SpatialSurfaceMesh* = guid"F5938FAD-A8A1-5F7E-9440-BDB781AD26B6"
const IID_IVectorView_1_DirectXPixelFormat* = guid"1EDDA1C2-0F6E-516C-80B8-7687DCD1280E"
const IID_IKeyValuePair_2_Guid_SpatialSurfaceInfo* = guid"A6BDF94A-2697-5FF2-89DC-A17CECDCDA6C"
const IID_IIterable_1_IKeyValuePair_22* = guid"868757D1-BE21-51D9-8DEE-A958B9DEEC71"
const IID_IIterable_1_SpatialBoundingVolume* = guid"89E8F1EE-3A2A-5B69-A786-CDDCF7456A3A"
const IID_IVectorView_1_SpatialBoundingVolume* = guid"471D0048-3CD1-5B72-A118-8D5A48BFE0DF"
const IID_IIterator_1_SpatialBoundingVolume* = guid"EB8385C5-0775-5415-8F76-327E6E388AC5"
const IID_TypedEventHandler_2_SpatialSurfaceObserver_Object* = guid"8B31274A-7693-52BE-9014-B0F5F65A3539"


proc setActivationFactoryProvider*(_: typedesc[CorePerceptionAutomation],
                                   provider: WinRtObject) =
  ## Windows.Perception.Automation.Core.CorePerceptionAutomation.SetActivationFactoryProvider
  withStatics("Windows.Perception.Automation.Core.CorePerceptionAutomation",
              ICorePerceptionAutomationStatics, it):
    withIface(provider.p, IGetActivationFactory, p0):
      it.call(ICorePerceptionAutomationStatics_SetActivationFactoryProvider, p0)

proc isCalibrationValid*(self: EyesPose): bool =
  ## Windows.Perception.People.EyesPose.get_IsCalibrationValid
  withIface(self.p, IEyesPose, it):
    var tmp: bool
    it.call(IEyesPose_get_IsCalibrationValid, tmp.addr)
    result = tmp

proc gaze*(self: EyesPose): Option[SpatialRay] =
  ## Windows.Perception.People.EyesPose.get_Gaze
  withIface(self.p, IEyesPose, it):
    var tmp: pointer
    it.call(IEyesPose_get_Gaze, tmp.addr)
    result = readReference[SpatialRay](tmp, IID_IReference_1_SpatialRay,
                                       "EyesPose.get_Gaze")
    release(tmp)

proc updateTimestamp*(self: EyesPose): PerceptionTimestamp =
  ## Windows.Perception.People.EyesPose.get_UpdateTimestamp
  withIface(self.p, IEyesPose, it):
    var tmp: pointer
    it.call(IEyesPose_get_UpdateTimestamp, tmp.addr)
    result = adopt[PerceptionTimestamp](tmp)

proc isSupported*(_: typedesc[EyesPose]): bool =
  ## Windows.Perception.People.EyesPose.IsSupported
  withStatics("Windows.Perception.People.EyesPose", IEyesPoseStatics, it):
    var tmp: bool
    it.call(IEyesPoseStatics_IsSupported, tmp.addr)
    result = tmp

proc requestAccessAsync*(_: typedesc[EyesPose]): Future[GazeInputAccessStatus] {.async.} =
  ## Windows.Perception.People.EyesPose.RequestAccessAsync
  var op: pointer
  withStatics("Windows.Perception.People.EyesPose", IEyesPoseStatics, it):
    it.call(IEyesPoseStatics_RequestAccessAsync, op.addr)
  result = await awaitValue[GazeInputAccessStatus](op,
                                                   IID_IAsyncOperation_1_GazeInputAccessStatus,
                                                   IID_AsyncOperationCompletedHandler_1_GazeInputAccessStatus,
                                                   alPlain,
                                                   "EyesPose.RequestAccessAsync")

proc source*(self: HandMeshObserver): SpatialInteractionSource =
  ## Windows.Perception.People.HandMeshObserver.get_Source
  withIface(self.p, IHandMeshObserver, it):
    var tmp: pointer
    it.call(IHandMeshObserver_get_Source, tmp.addr)
    result = adopt[SpatialInteractionSource](tmp)

proc triangleIndexCount*(self: HandMeshObserver): uint32 =
  ## Windows.Perception.People.HandMeshObserver.get_TriangleIndexCount
  withIface(self.p, IHandMeshObserver, it):
    var tmp: uint32
    it.call(IHandMeshObserver_get_TriangleIndexCount, tmp.addr)
    result = tmp

proc vertexCount*(self: HandMeshObserver): uint32 =
  ## Windows.Perception.People.HandMeshObserver.get_VertexCount
  withIface(self.p, IHandMeshObserver, it):
    var tmp: uint32
    it.call(IHandMeshObserver_get_VertexCount, tmp.addr)
    result = tmp

proc getTriangleIndices*(self: HandMeshObserver, indices: openArray[uint16]) =
  ## Windows.Perception.People.HandMeshObserver.GetTriangleIndices
  withIface(self.p, IHandMeshObserver, it):
    let n0 = uint32(indices.len)
    let d0 = if indices.len > 0: indices[0].unsafeAddr else: nil
    it.call(IHandMeshObserver_GetTriangleIndices, n0, d0)

proc getVertexStateForPose*(self: HandMeshObserver, handPose: HandPose): HandMeshVertexState =
  ## Windows.Perception.People.HandMeshObserver.GetVertexStateForPose
  withIface(self.p, IHandMeshObserver, it):
    withIface(handPose.p, IHandPose, p0):
      var tmp: pointer
      it.call(IHandMeshObserver_GetVertexStateForPose, p0, tmp.addr)
      result = adopt[HandMeshVertexState](tmp)

proc neutralPose*(self: HandMeshObserver): HandPose =
  ## Windows.Perception.People.HandMeshObserver.get_NeutralPose
  withIface(self.p, IHandMeshObserver, it):
    var tmp: pointer
    it.call(IHandMeshObserver_get_NeutralPose, tmp.addr)
    result = adopt[HandPose](tmp)

proc neutralPoseVersion*(self: HandMeshObserver): int32 =
  ## Windows.Perception.People.HandMeshObserver.get_NeutralPoseVersion
  withIface(self.p, IHandMeshObserver, it):
    var tmp: int32
    it.call(IHandMeshObserver_get_NeutralPoseVersion, tmp.addr)
    result = tmp

proc modelId*(self: HandMeshObserver): int32 =
  ## Windows.Perception.People.HandMeshObserver.get_ModelId
  withIface(self.p, IHandMeshObserver, it):
    var tmp: int32
    it.call(IHandMeshObserver_get_ModelId, tmp.addr)
    result = tmp

proc coordinateSystem*(self: HandMeshVertexState): SpatialCoordinateSystem =
  ## Windows.Perception.People.HandMeshVertexState.get_CoordinateSystem
  withIface(self.p, IHandMeshVertexState, it):
    var tmp: pointer
    it.call(IHandMeshVertexState_get_CoordinateSystem, tmp.addr)
    result = adopt[SpatialCoordinateSystem](tmp)

proc getVertices*(self: HandMeshVertexState, vertices: openArray[HandMeshVertex]) =
  ## Windows.Perception.People.HandMeshVertexState.GetVertices
  withIface(self.p, IHandMeshVertexState, it):
    let n0 = uint32(vertices.len)
    let d0 = if vertices.len > 0: vertices[0].unsafeAddr else: nil
    it.call(IHandMeshVertexState_GetVertices, n0, d0)

proc updateTimestamp*(self: HandMeshVertexState): PerceptionTimestamp =
  ## Windows.Perception.People.HandMeshVertexState.get_UpdateTimestamp
  withIface(self.p, IHandMeshVertexState, it):
    var tmp: pointer
    it.call(IHandMeshVertexState_get_UpdateTimestamp, tmp.addr)
    result = adopt[PerceptionTimestamp](tmp)

proc tryGetJoint*(self: HandPose, coordinateSystem: SpatialCoordinateSystem,
                  joint: HandJointKind): tuple[value: bool, jointPose: JointPose] =
  ## Windows.Perception.People.HandPose.TryGetJoint
  withIface(self.p, IHandPose, it):
    withIface(coordinateSystem.p, ISpatialCoordinateSystem, p0):
      var jointPose: JointPose
      var ret: bool
      var tmp: bool
      it.call(IHandPose_TryGetJoint, p0, joint, jointPose.addr, tmp.addr)
      ret = tmp
      result = (value: ret, jointPose: jointPose)

proc tryGetJoints*(self: HandPose, coordinateSystem: SpatialCoordinateSystem,
                   joints: openArray[HandJointKind],
                   jointPoses: openArray[JointPose]): bool =
  ## Windows.Perception.People.HandPose.TryGetJoints
  withIface(self.p, IHandPose, it):
    withIface(coordinateSystem.p, ISpatialCoordinateSystem, p0):
      let n1 = uint32(joints.len)
      let d1 = if joints.len > 0: joints[0].unsafeAddr else: nil
      let n2 = uint32(jointPoses.len)
      let d2 = if jointPoses.len > 0: jointPoses[0].unsafeAddr else: nil
      var tmp: bool
      it.call(IHandPose_TryGetJoints, p0, n1, d1, n2, d2, tmp.addr)
      result = tmp

proc getRelativeJoint*(self: HandPose, joint: HandJointKind,
                       referenceJoint: HandJointKind): JointPose =
  ## Windows.Perception.People.HandPose.GetRelativeJoint
  withIface(self.p, IHandPose, it):
    var tmp: JointPose
    it.call(IHandPose_GetRelativeJoint, joint, referenceJoint, tmp.addr)
    result = tmp

proc getRelativeJoints*(self: HandPose, joints: openArray[HandJointKind],
                        referenceJoints: openArray[HandJointKind],
                        jointPoses: openArray[JointPose]) =
  ## Windows.Perception.People.HandPose.GetRelativeJoints
  withIface(self.p, IHandPose, it):
    let n0 = uint32(joints.len)
    let d0 = if joints.len > 0: joints[0].unsafeAddr else: nil
    let n1 = uint32(referenceJoints.len)
    let d1 = if referenceJoints.len > 0: referenceJoints[0].unsafeAddr else: nil
    let n2 = uint32(jointPoses.len)
    let d2 = if jointPoses.len > 0: jointPoses[0].unsafeAddr else: nil
    it.call(IHandPose_GetRelativeJoints, n0, d0, n1, d1, n2, d2)

proc position*(self: HeadPose): Vector3 =
  ## Windows.Perception.People.HeadPose.get_Position
  withIface(self.p, IHeadPose, it):
    var tmp: Vector3
    it.call(IHeadPose_get_Position, tmp.addr)
    result = tmp

proc forwardDirection*(self: HeadPose): Vector3 =
  ## Windows.Perception.People.HeadPose.get_ForwardDirection
  withIface(self.p, IHeadPose, it):
    var tmp: Vector3
    it.call(IHeadPose_get_ForwardDirection, tmp.addr)
    result = tmp

proc upDirection*(self: HeadPose): Vector3 =
  ## Windows.Perception.People.HeadPose.get_UpDirection
  withIface(self.p, IHeadPose, it):
    var tmp: Vector3
    it.call(IHeadPose_get_UpDirection, tmp.addr)
    result = tmp

proc targetTime*(self: PerceptionTimestamp): DateTime =
  ## Windows.Perception.PerceptionTimestamp.get_TargetTime
  withIface(self.p, IPerceptionTimestamp, it):
    var tmp: DateTime
    it.call(IPerceptionTimestamp_get_TargetTime, tmp.addr)
    result = tmp

proc predictionAmount*(self: PerceptionTimestamp): TimeSpan =
  ## Windows.Perception.PerceptionTimestamp.get_PredictionAmount
  withIface(self.p, IPerceptionTimestamp, it):
    var tmp: TimeSpan
    it.call(IPerceptionTimestamp_get_PredictionAmount, tmp.addr)
    result = tmp

proc systemRelativeTargetTime*(self: PerceptionTimestamp): TimeSpan =
  ## Windows.Perception.PerceptionTimestamp.get_SystemRelativeTargetTime
  withIface(self.p, IPerceptionTimestamp2, it):
    var tmp: TimeSpan
    it.call(IPerceptionTimestamp2_get_SystemRelativeTargetTime, tmp.addr)
    result = tmp

proc fromHistoricalTargetTime*(_: typedesc[PerceptionTimestampHelper],
                               targetTime: DateTime): PerceptionTimestamp =
  ## Windows.Perception.PerceptionTimestampHelper.FromHistoricalTargetTime
  withStatics("Windows.Perception.PerceptionTimestampHelper",
              IPerceptionTimestampHelperStatics, it):
    var tmp: pointer
    it.call(IPerceptionTimestampHelperStatics_FromHistoricalTargetTime,
            targetTime, tmp.addr)
    result = adopt[PerceptionTimestamp](tmp)

proc fromSystemRelativeTargetTime*(_: typedesc[PerceptionTimestampHelper],
                                   targetTime: TimeSpan): PerceptionTimestamp =
  ## Windows.Perception.PerceptionTimestampHelper.FromSystemRelativeTargetTime
  withStatics("Windows.Perception.PerceptionTimestampHelper",
              IPerceptionTimestampHelperStatics2, it):
    var tmp: pointer
    it.call(IPerceptionTimestampHelperStatics2_FromSystemRelativeTargetTime,
            targetTime, tmp.addr)
    result = adopt[PerceptionTimestamp](tmp)

proc coordinateSystem*(self: SpatialGraphInteropFrameOfReferencePreview): SpatialCoordinateSystem =
  ## Windows.Perception.Spatial.Preview.SpatialGraphInteropFrameOfReferencePreview.get_CoordinateSystem
  withIface(self.p, ISpatialGraphInteropFrameOfReferencePreview, it):
    var tmp: pointer
    it.call(ISpatialGraphInteropFrameOfReferencePreview_get_CoordinateSystem,
            tmp.addr)
    result = adopt[SpatialCoordinateSystem](tmp)

proc nodeId*(self: SpatialGraphInteropFrameOfReferencePreview): GUID =
  ## Windows.Perception.Spatial.Preview.SpatialGraphInteropFrameOfReferencePreview.get_NodeId
  withIface(self.p, ISpatialGraphInteropFrameOfReferencePreview, it):
    var tmp: GUID
    it.call(ISpatialGraphInteropFrameOfReferencePreview_get_NodeId, tmp.addr)
    result = tmp

proc coordinateSystemToNodeTransform*(self: SpatialGraphInteropFrameOfReferencePreview): Matrix4x4 =
  ## Windows.Perception.Spatial.Preview.SpatialGraphInteropFrameOfReferencePreview.get_CoordinateSystemToNodeTransform
  withIface(self.p, ISpatialGraphInteropFrameOfReferencePreview, it):
    var tmp: Matrix4x4
    it.call(ISpatialGraphInteropFrameOfReferencePreview_get_CoordinateSystemToNodeTransform,
            tmp.addr)
    result = tmp

proc createCoordinateSystemForNode*(_: typedesc[SpatialGraphInteropPreview],
                                    nodeId: GUID): SpatialCoordinateSystem =
  ## Windows.Perception.Spatial.Preview.SpatialGraphInteropPreview.CreateCoordinateSystemForNode
  withStatics("Windows.Perception.Spatial.Preview.SpatialGraphInteropPreview",
              ISpatialGraphInteropPreviewStatics, it):
    var tmp: pointer
    it.call(ISpatialGraphInteropPreviewStatics_CreateCoordinateSystemForNode,
            nodeId, tmp.addr)
    result = adopt[SpatialCoordinateSystem](tmp)

proc createCoordinateSystemForNode*(_: typedesc[SpatialGraphInteropPreview],
                                    nodeId: GUID, relativePosition: Vector3): SpatialCoordinateSystem =
  ## Windows.Perception.Spatial.Preview.SpatialGraphInteropPreview.CreateCoordinateSystemForNode
  withStatics("Windows.Perception.Spatial.Preview.SpatialGraphInteropPreview",
              ISpatialGraphInteropPreviewStatics, it):
    var tmp: pointer
    it.call(ISpatialGraphInteropPreviewStatics_CreateCoordinateSystemForNode2,
            nodeId, relativePosition, tmp.addr)
    result = adopt[SpatialCoordinateSystem](tmp)

proc createCoordinateSystemForNode*(_: typedesc[SpatialGraphInteropPreview],
                                    nodeId: GUID, relativePosition: Vector3,
                                    relativeOrientation: Quaternion): SpatialCoordinateSystem =
  ## Windows.Perception.Spatial.Preview.SpatialGraphInteropPreview.CreateCoordinateSystemForNode
  withStatics("Windows.Perception.Spatial.Preview.SpatialGraphInteropPreview",
              ISpatialGraphInteropPreviewStatics, it):
    var tmp: pointer
    it.call(ISpatialGraphInteropPreviewStatics_CreateCoordinateSystemForNode3,
            nodeId, relativePosition, relativeOrientation, tmp.addr)
    result = adopt[SpatialCoordinateSystem](tmp)

proc createLocatorForNode*(_: typedesc[SpatialGraphInteropPreview], nodeId: GUID): SpatialLocator =
  ## Windows.Perception.Spatial.Preview.SpatialGraphInteropPreview.CreateLocatorForNode
  withStatics("Windows.Perception.Spatial.Preview.SpatialGraphInteropPreview",
              ISpatialGraphInteropPreviewStatics, it):
    var tmp: pointer
    it.call(ISpatialGraphInteropPreviewStatics_CreateLocatorForNode, nodeId,
            tmp.addr)
    result = adopt[SpatialLocator](tmp)

proc tryCreateFrameOfReference*(_: typedesc[SpatialGraphInteropPreview],
                                coordinateSystem: SpatialCoordinateSystem): SpatialGraphInteropFrameOfReferencePreview =
  ## Windows.Perception.Spatial.Preview.SpatialGraphInteropPreview.TryCreateFrameOfReference
  withStatics("Windows.Perception.Spatial.Preview.SpatialGraphInteropPreview",
              ISpatialGraphInteropPreviewStatics2, it):
    withIface(coordinateSystem.p, ISpatialCoordinateSystem, p0):
      var tmp: pointer
      it.call(ISpatialGraphInteropPreviewStatics2_TryCreateFrameOfReference, p0,
              tmp.addr)
      result = adopt[SpatialGraphInteropFrameOfReferencePreview](tmp)

proc tryCreateFrameOfReference*(_: typedesc[SpatialGraphInteropPreview],
                                coordinateSystem: SpatialCoordinateSystem,
                                relativePosition: Vector3): SpatialGraphInteropFrameOfReferencePreview =
  ## Windows.Perception.Spatial.Preview.SpatialGraphInteropPreview.TryCreateFrameOfReference
  withStatics("Windows.Perception.Spatial.Preview.SpatialGraphInteropPreview",
              ISpatialGraphInteropPreviewStatics2, it):
    withIface(coordinateSystem.p, ISpatialCoordinateSystem, p0):
      var tmp: pointer
      it.call(ISpatialGraphInteropPreviewStatics2_TryCreateFrameOfReference2,
              p0, relativePosition, tmp.addr)
      result = adopt[SpatialGraphInteropFrameOfReferencePreview](tmp)

proc tryCreateFrameOfReference*(_: typedesc[SpatialGraphInteropPreview],
                                coordinateSystem: SpatialCoordinateSystem,
                                relativePosition: Vector3,
                                relativeOrientation: Quaternion): SpatialGraphInteropFrameOfReferencePreview =
  ## Windows.Perception.Spatial.Preview.SpatialGraphInteropPreview.TryCreateFrameOfReference
  withStatics("Windows.Perception.Spatial.Preview.SpatialGraphInteropPreview",
              ISpatialGraphInteropPreviewStatics2, it):
    withIface(coordinateSystem.p, ISpatialCoordinateSystem, p0):
      var tmp: pointer
      it.call(ISpatialGraphInteropPreviewStatics2_TryCreateFrameOfReference3,
              p0, relativePosition, relativeOrientation, tmp.addr)
      result = adopt[SpatialGraphInteropFrameOfReferencePreview](tmp)

proc coordinateSystem*(self: SpatialAnchor): SpatialCoordinateSystem =
  ## Windows.Perception.Spatial.SpatialAnchor.get_CoordinateSystem
  withIface(self.p, ISpatialAnchor, it):
    var tmp: pointer
    it.call(ISpatialAnchor_get_CoordinateSystem, tmp.addr)
    result = adopt[SpatialCoordinateSystem](tmp)

proc rawCoordinateSystem*(self: SpatialAnchor): SpatialCoordinateSystem =
  ## Windows.Perception.Spatial.SpatialAnchor.get_RawCoordinateSystem
  withIface(self.p, ISpatialAnchor, it):
    var tmp: pointer
    it.call(ISpatialAnchor_get_RawCoordinateSystem, tmp.addr)
    result = adopt[SpatialCoordinateSystem](tmp)

proc onRawCoordinateSystemAdjusted*(self: SpatialAnchor,
                                    handler: EventHandler[SpatialAnchor, SpatialAnchorRawCoordinateSystemAdjustedEventArgs]): EventRegistrationToken {.discardable.} =
  ## Windows.Perception.Spatial.SpatialAnchor.add_RawCoordinateSystemAdjusted
  ## The token is what `removeRawCoordinateSystemAdjusted` takes.
  withIface(self.p, ISpatialAnchor, it):
    proc shim(a0: pointer, a1: pointer) =
      handler(borrow[SpatialAnchor](a0),
              borrow[SpatialAnchorRawCoordinateSystemAdjustedEventArgs](a1))
    let cb = newDelegate(IID_TypedEventHandler_2_SpatialAnchor_SpatialAnchorRawCoordinateSystemAdjustedEventArgs, shim, event = true)
    try:
      it.call(ISpatialAnchor_add_RawCoordinateSystemAdjusted, cb, result.addr)
    finally:
      release(cb)

proc removeRawCoordinateSystemAdjusted*(self: SpatialAnchor, token: EventRegistrationToken) =
  withIface(self.p, ISpatialAnchor, it):
    it.call(ISpatialAnchor_remove_RawCoordinateSystemAdjusted, token)

proc removedByUser*(self: SpatialAnchor): bool =
  ## Windows.Perception.Spatial.SpatialAnchor.get_RemovedByUser
  withIface(self.p, ISpatialAnchor2, it):
    var tmp: bool
    it.call(ISpatialAnchor2_get_RemovedByUser, tmp.addr)
    result = tmp

proc tryCreateRelativeTo*(_: typedesc[SpatialAnchor],
                          coordinateSystem: SpatialCoordinateSystem): SpatialAnchor =
  ## Windows.Perception.Spatial.SpatialAnchor.TryCreateRelativeTo
  withStatics("Windows.Perception.Spatial.SpatialAnchor", ISpatialAnchorStatics,
              it):
    withIface(coordinateSystem.p, ISpatialCoordinateSystem, p0):
      var tmp: pointer
      it.call(ISpatialAnchorStatics_TryCreateRelativeTo, p0, tmp.addr)
      result = adopt[SpatialAnchor](tmp)

proc tryCreateRelativeTo*(_: typedesc[SpatialAnchor],
                          coordinateSystem: SpatialCoordinateSystem,
                          position: Vector3): SpatialAnchor =
  ## Windows.Perception.Spatial.SpatialAnchor.TryCreateRelativeTo
  withStatics("Windows.Perception.Spatial.SpatialAnchor", ISpatialAnchorStatics,
              it):
    withIface(coordinateSystem.p, ISpatialCoordinateSystem, p0):
      var tmp: pointer
      it.call(ISpatialAnchorStatics_TryCreateRelativeTo2, p0, position, tmp.addr)
      result = adopt[SpatialAnchor](tmp)

proc tryCreateRelativeTo*(_: typedesc[SpatialAnchor],
                          coordinateSystem: SpatialCoordinateSystem,
                          position: Vector3, orientation: Quaternion): SpatialAnchor =
  ## Windows.Perception.Spatial.SpatialAnchor.TryCreateRelativeTo
  withStatics("Windows.Perception.Spatial.SpatialAnchor", ISpatialAnchorStatics,
              it):
    withIface(coordinateSystem.p, ISpatialCoordinateSystem, p0):
      var tmp: pointer
      it.call(ISpatialAnchorStatics_TryCreateRelativeTo3, p0, position,
              orientation, tmp.addr)
      result = adopt[SpatialAnchor](tmp)

proc isMinimallySufficient*(self: SpatialAnchorExportSufficiency): bool =
  ## Windows.Perception.Spatial.SpatialAnchorExportSufficiency.get_IsMinimallySufficient
  withIface(self.p, ISpatialAnchorExportSufficiency, it):
    var tmp: bool
    it.call(ISpatialAnchorExportSufficiency_get_IsMinimallySufficient, tmp.addr)
    result = tmp

proc sufficiencyLevel*(self: SpatialAnchorExportSufficiency): float64 =
  ## Windows.Perception.Spatial.SpatialAnchorExportSufficiency.get_SufficiencyLevel
  withIface(self.p, ISpatialAnchorExportSufficiency, it):
    var tmp: float64
    it.call(ISpatialAnchorExportSufficiency_get_SufficiencyLevel, tmp.addr)
    result = tmp

proc recommendedSufficiencyLevel*(self: SpatialAnchorExportSufficiency): float64 =
  ## Windows.Perception.Spatial.SpatialAnchorExportSufficiency.get_RecommendedSufficiencyLevel
  withIface(self.p, ISpatialAnchorExportSufficiency, it):
    var tmp: float64
    it.call(ISpatialAnchorExportSufficiency_get_RecommendedSufficiencyLevel,
            tmp.addr)
    result = tmp

proc getAnchorExportSufficiencyAsync*(self: SpatialAnchorExporter,
                                      anchor: SpatialAnchor,
                                      purpose: SpatialAnchorExportPurpose): Future[SpatialAnchorExportSufficiency] {.async.} =
  ## Windows.Perception.Spatial.SpatialAnchorExporter.GetAnchorExportSufficiencyAsync
  var op: pointer
  withIface(self.p, ISpatialAnchorExporter, it):
    withIface(anchor.p, ISpatialAnchor, p0):
      it.call(ISpatialAnchorExporter_GetAnchorExportSufficiencyAsync, p0,
              purpose, op.addr)
  result = adopt[SpatialAnchorExportSufficiency](await awaitObject(op,
                                                                   IID_IAsyncOperation_1_SpatialAnchorExportSufficiency,
                                                                   IID_AsyncOperationCompletedHandler_1_SpatialAnchorExportSufficiency,
                                                                   alPlain,
                                                                   "SpatialAnchorExporter.GetAnchorExportSufficiencyAsync"))

proc tryExportAnchorAsync*(self: SpatialAnchorExporter, anchor: SpatialAnchor,
                           purpose: SpatialAnchorExportPurpose,
                           stream: WinRtObject): Future[bool] {.async.} =
  ## Windows.Perception.Spatial.SpatialAnchorExporter.TryExportAnchorAsync
  var op: pointer
  withIface(self.p, ISpatialAnchorExporter, it):
    withIface(anchor.p, ISpatialAnchor, p0):
      withIface(stream.p, IOutputStream, p2):
        it.call(ISpatialAnchorExporter_TryExportAnchorAsync, p0, purpose, p2,
                op.addr)
  result = await awaitValue[bool](op, IID_IAsyncOperation_1_Bool,
                                  IID_AsyncOperationCompletedHandler_1_Bool,
                                  alPlain,
                                  "SpatialAnchorExporter.TryExportAnchorAsync")

proc getDefault*(_: typedesc[SpatialAnchorExporter]): SpatialAnchorExporter =
  ## Windows.Perception.Spatial.SpatialAnchorExporter.GetDefault
  withStatics("Windows.Perception.Spatial.SpatialAnchorExporter",
              ISpatialAnchorExporterStatics, it):
    var tmp: pointer
    it.call(ISpatialAnchorExporterStatics_GetDefault, tmp.addr)
    result = adopt[SpatialAnchorExporter](tmp)

proc requestAccessAsync*(_: typedesc[SpatialAnchorExporter]): Future[SpatialPerceptionAccessStatus] {.async.} =
  ## Windows.Perception.Spatial.SpatialAnchorExporter.RequestAccessAsync
  var op: pointer
  withStatics("Windows.Perception.Spatial.SpatialAnchorExporter",
              ISpatialAnchorExporterStatics, it):
    it.call(ISpatialAnchorExporterStatics_RequestAccessAsync, op.addr)
  result = await awaitValue[SpatialPerceptionAccessStatus](op,
                                                           IID_IAsyncOperation_1_SpatialPerceptionAccessStatus,
                                                           IID_AsyncOperationCompletedHandler_1_SpatialPerceptionAccessStatus,
                                                           alPlain,
                                                           "SpatialAnchorExporter.RequestAccessAsync")

proc requestStoreAsync*(_: typedesc[SpatialAnchorManager]): Future[SpatialAnchorStore] {.async.} =
  ## Windows.Perception.Spatial.SpatialAnchorManager.RequestStoreAsync
  var op: pointer
  withStatics("Windows.Perception.Spatial.SpatialAnchorManager",
              ISpatialAnchorManagerStatics, it):
    it.call(ISpatialAnchorManagerStatics_RequestStoreAsync, op.addr)
  result = adopt[SpatialAnchorStore](await awaitObject(op,
                                                       IID_IAsyncOperation_1_SpatialAnchorStore,
                                                       IID_AsyncOperationCompletedHandler_1_SpatialAnchorStore,
                                                       alPlain,
                                                       "SpatialAnchorManager.RequestStoreAsync"))

proc oldRawCoordinateSystemToNewRawCoordinateSystemTransform*(self: SpatialAnchorRawCoordinateSystemAdjustedEventArgs): Matrix4x4 =
  ## Windows.Perception.Spatial.SpatialAnchorRawCoordinateSystemAdjustedEventArgs.get_OldRawCoordinateSystemToNewRawCoordinateSystemTransform
  withIface(self.p, ISpatialAnchorRawCoordinateSystemAdjustedEventArgs, it):
    var tmp: Matrix4x4
    it.call(ISpatialAnchorRawCoordinateSystemAdjustedEventArgs_get_OldRawCoordinateSystemToNewRawCoordinateSystemTransform,
            tmp.addr)
    result = tmp

proc getAllSavedAnchors*(self: SpatialAnchorStore): Table[string, SpatialAnchor] =
  ## Windows.Perception.Spatial.SpatialAnchorStore.GetAllSavedAnchors
  withIface(self.p, ISpatialAnchorStore, it):
    var tmp: pointer
    it.call(ISpatialAnchorStore_GetAllSavedAnchors, tmp.addr)
    result = toTable[string, SpatialAnchor](tmp,
                                            IID_IIterable_1_IKeyValuePair_2,
                                            IID_IKeyValuePair_2_String_SpatialAnchor)
    release(tmp)

proc trySave*(self: SpatialAnchorStore, id: string, anchor: SpatialAnchor): bool =
  ## Windows.Perception.Spatial.SpatialAnchorStore.TrySave
  withIface(self.p, ISpatialAnchorStore, it):
    withHString(id, h0):
      withIface(anchor.p, ISpatialAnchor, p1):
        var tmp: bool
        it.call(ISpatialAnchorStore_TrySave, h0, p1, tmp.addr)
        result = tmp

proc remove*(self: SpatialAnchorStore, id: string) =
  ## Windows.Perception.Spatial.SpatialAnchorStore.Remove
  withIface(self.p, ISpatialAnchorStore, it):
    withHString(id, h0):
      it.call(ISpatialAnchorStore_Remove, h0)

proc clear*(self: SpatialAnchorStore) =
  ## Windows.Perception.Spatial.SpatialAnchorStore.Clear
  withIface(self.p, ISpatialAnchorStore, it):
    it.call(ISpatialAnchorStore_Clear)

proc tryImportAnchorsAsync*(_: typedesc[SpatialAnchorTransferManager],
                            stream: WinRtObject): Future[Table[string, SpatialAnchor]] {.async.} =
  ## Windows.Perception.Spatial.SpatialAnchorTransferManager.TryImportAnchorsAsync
  var op: pointer
  withStatics("Windows.Perception.Spatial.SpatialAnchorTransferManager",
              ISpatialAnchorTransferManagerStatics, it):
    withIface(stream.p, IInputStream, p0):
      it.call(ISpatialAnchorTransferManagerStatics_TryImportAnchorsAsync, p0,
              op.addr)
  let coll = await awaitObject(op, IID_IAsyncOperation_1_IMapView_2,
                               IID_AsyncOperationCompletedHandler_1_IMapView_2,
                               alPlain,
                               "SpatialAnchorTransferManager.TryImportAnchorsAsync")
  result = toTable[string, SpatialAnchor](coll, IID_IIterable_1_IKeyValuePair_2,
                                          IID_IKeyValuePair_2_String_SpatialAnchor)
  discard release(coll)

proc tryExportAnchorsAsync*(_: typedesc[SpatialAnchorTransferManager],
                            anchors: Table[string, SpatialAnchor],
                            stream: WinRtObject): Future[bool] {.async.} =
  ## Windows.Perception.Spatial.SpatialAnchorTransferManager.TryExportAnchorsAsync
  var op: pointer
  withStatics("Windows.Perception.Spatial.SpatialAnchorTransferManager",
              ISpatialAnchorTransferManagerStatics, it):
    let p0 = asMap(anchors, MapIids(iterable: IID_IIterable_1_IKeyValuePair_2,
                                    cursor: IID_IIterator_1_IKeyValuePair_2,
                                    pair: IID_IKeyValuePair_2_String_SpatialAnchor,
                                    view: IID_IMapView_2_String_SpatialAnchor,
                                    map: IID_IMap_2_String_SpatialAnchor))
    defer: discard release(p0)
    withIface(stream.p, IOutputStream, p1):
      it.call(ISpatialAnchorTransferManagerStatics_TryExportAnchorsAsync, p0,
              p1, op.addr)
  result = await awaitValue[bool](op, IID_IAsyncOperation_1_Bool,
                                  IID_AsyncOperationCompletedHandler_1_Bool,
                                  alPlain,
                                  "SpatialAnchorTransferManager.TryExportAnchorsAsync")

proc requestAccessAsync*(_: typedesc[SpatialAnchorTransferManager]): Future[SpatialPerceptionAccessStatus] {.async.} =
  ## Windows.Perception.Spatial.SpatialAnchorTransferManager.RequestAccessAsync
  var op: pointer
  withStatics("Windows.Perception.Spatial.SpatialAnchorTransferManager",
              ISpatialAnchorTransferManagerStatics, it):
    it.call(ISpatialAnchorTransferManagerStatics_RequestAccessAsync, op.addr)
  result = await awaitValue[SpatialPerceptionAccessStatus](op,
                                                           IID_IAsyncOperation_1_SpatialPerceptionAccessStatus,
                                                           IID_AsyncOperationCompletedHandler_1_SpatialPerceptionAccessStatus,
                                                           alPlain,
                                                           "SpatialAnchorTransferManager.RequestAccessAsync")

proc fromBox*(_: typedesc[SpatialBoundingVolume],
              coordinateSystem: SpatialCoordinateSystem, box: SpatialBoundingBox): SpatialBoundingVolume =
  ## Windows.Perception.Spatial.SpatialBoundingVolume.FromBox
  withStatics("Windows.Perception.Spatial.SpatialBoundingVolume",
              ISpatialBoundingVolumeStatics, it):
    withIface(coordinateSystem.p, ISpatialCoordinateSystem, p0):
      var tmp: pointer
      it.call(ISpatialBoundingVolumeStatics_FromBox, p0, box, tmp.addr)
      result = adopt[SpatialBoundingVolume](tmp)

proc fromOrientedBox*(_: typedesc[SpatialBoundingVolume],
                      coordinateSystem: SpatialCoordinateSystem,
                      box: SpatialBoundingOrientedBox): SpatialBoundingVolume =
  ## Windows.Perception.Spatial.SpatialBoundingVolume.FromOrientedBox
  withStatics("Windows.Perception.Spatial.SpatialBoundingVolume",
              ISpatialBoundingVolumeStatics, it):
    withIface(coordinateSystem.p, ISpatialCoordinateSystem, p0):
      var tmp: pointer
      it.call(ISpatialBoundingVolumeStatics_FromOrientedBox, p0, box, tmp.addr)
      result = adopt[SpatialBoundingVolume](tmp)

proc fromSphere*(_: typedesc[SpatialBoundingVolume],
                 coordinateSystem: SpatialCoordinateSystem,
                 sphere: SpatialBoundingSphere): SpatialBoundingVolume =
  ## Windows.Perception.Spatial.SpatialBoundingVolume.FromSphere
  withStatics("Windows.Perception.Spatial.SpatialBoundingVolume",
              ISpatialBoundingVolumeStatics, it):
    withIface(coordinateSystem.p, ISpatialCoordinateSystem, p0):
      var tmp: pointer
      it.call(ISpatialBoundingVolumeStatics_FromSphere, p0, sphere, tmp.addr)
      result = adopt[SpatialBoundingVolume](tmp)

proc fromFrustum*(_: typedesc[SpatialBoundingVolume],
                  coordinateSystem: SpatialCoordinateSystem,
                  frustum: SpatialBoundingFrustum): SpatialBoundingVolume =
  ## Windows.Perception.Spatial.SpatialBoundingVolume.FromFrustum
  withStatics("Windows.Perception.Spatial.SpatialBoundingVolume",
              ISpatialBoundingVolumeStatics, it):
    withIface(coordinateSystem.p, ISpatialCoordinateSystem, p0):
      var tmp: pointer
      it.call(ISpatialBoundingVolumeStatics_FromFrustum, p0, frustum, tmp.addr)
      result = adopt[SpatialBoundingVolume](tmp)

proc tryGetTransformTo*(self: SpatialCoordinateSystem,
                        target: SpatialCoordinateSystem): Option[Matrix4x4] =
  ## Windows.Perception.Spatial.SpatialCoordinateSystem.TryGetTransformTo
  withIface(self.p, ISpatialCoordinateSystem, it):
    withIface(target.p, ISpatialCoordinateSystem, p0):
      var tmp: pointer
      it.call(ISpatialCoordinateSystem_TryGetTransformTo, p0, tmp.addr)
      result = readReference[Matrix4x4](tmp, IID_IReference_1_Matrix4x4,
                                        "SpatialCoordinateSystem.TryGetTransformTo")
      release(tmp)

proc id*(self: SpatialEntity): string =
  ## Windows.Perception.Spatial.SpatialEntity.get_Id
  withIface(self.p, ISpatialEntity, it):
    var tmp: HSTRING
    it.call(ISpatialEntity_get_Id, tmp.addr)
    result = takeString(tmp)

proc anchor*(self: SpatialEntity): SpatialAnchor =
  ## Windows.Perception.Spatial.SpatialEntity.get_Anchor
  withIface(self.p, ISpatialEntity, it):
    var tmp: pointer
    it.call(ISpatialEntity_get_Anchor, tmp.addr)
    result = adopt[SpatialAnchor](tmp)

proc properties*(self: SpatialEntity): ValueSet =
  ## Windows.Perception.Spatial.SpatialEntity.get_Properties
  withIface(self.p, ISpatialEntity, it):
    var tmp: pointer
    it.call(ISpatialEntity_get_Properties, tmp.addr)
    result = adopt[ValueSet](tmp)

proc createWithSpatialAnchor*(_: typedesc[SpatialEntity],
                              spatialAnchor: SpatialAnchor): SpatialEntity =
  ## Windows.Perception.Spatial.SpatialEntity.CreateWithSpatialAnchor
  withStatics("Windows.Perception.Spatial.SpatialEntity", ISpatialEntityFactory,
              it):
    withIface(spatialAnchor.p, ISpatialAnchor, p0):
      var tmp: pointer
      it.call(ISpatialEntityFactory_CreateWithSpatialAnchor, p0, tmp.addr)
      result = adopt[SpatialEntity](tmp)

proc createWithSpatialAnchorAndProperties*(_: typedesc[SpatialEntity],
                                           spatialAnchor: SpatialAnchor,
                                           propertySet: ValueSet): SpatialEntity =
  ## Windows.Perception.Spatial.SpatialEntity.CreateWithSpatialAnchorAndProperties
  withStatics("Windows.Perception.Spatial.SpatialEntity", ISpatialEntityFactory,
              it):
    withIface(spatialAnchor.p, ISpatialAnchor, p0):
      withIface(propertySet.p, IPropertySet, p1):
        var tmp: pointer
        it.call(ISpatialEntityFactory_CreateWithSpatialAnchorAndProperties, p0,
                p1, tmp.addr)
        result = adopt[SpatialEntity](tmp)

proc entity*(self: SpatialEntityAddedEventArgs): SpatialEntity =
  ## Windows.Perception.Spatial.SpatialEntityAddedEventArgs.get_Entity
  withIface(self.p, ISpatialEntityAddedEventArgs, it):
    var tmp: pointer
    it.call(ISpatialEntityAddedEventArgs_get_Entity, tmp.addr)
    result = adopt[SpatialEntity](tmp)

proc entity*(self: SpatialEntityRemovedEventArgs): SpatialEntity =
  ## Windows.Perception.Spatial.SpatialEntityRemovedEventArgs.get_Entity
  withIface(self.p, ISpatialEntityRemovedEventArgs, it):
    var tmp: pointer
    it.call(ISpatialEntityRemovedEventArgs_get_Entity, tmp.addr)
    result = adopt[SpatialEntity](tmp)

proc saveAsync*(self: SpatialEntityStore, entity: SpatialEntity) {.async.} =
  ## Windows.Perception.Spatial.SpatialEntityStore.SaveAsync
  var op: pointer
  withIface(self.p, ISpatialEntityStore, it):
    withIface(entity.p, ISpatialEntity, p0):
      it.call(ISpatialEntityStore_SaveAsync, p0, op.addr)
  await awaitVoid(op, IID_AsyncActionCompletedHandler, alPlain,
                  "SpatialEntityStore.SaveAsync")

proc removeAsync*(self: SpatialEntityStore, entity: SpatialEntity) {.async.} =
  ## Windows.Perception.Spatial.SpatialEntityStore.RemoveAsync
  var op: pointer
  withIface(self.p, ISpatialEntityStore, it):
    withIface(entity.p, ISpatialEntity, p0):
      it.call(ISpatialEntityStore_RemoveAsync, p0, op.addr)
  await awaitVoid(op, IID_AsyncActionCompletedHandler, alPlain,
                  "SpatialEntityStore.RemoveAsync")

proc createEntityWatcher*(self: SpatialEntityStore): SpatialEntityWatcher =
  ## Windows.Perception.Spatial.SpatialEntityStore.CreateEntityWatcher
  withIface(self.p, ISpatialEntityStore, it):
    var tmp: pointer
    it.call(ISpatialEntityStore_CreateEntityWatcher, tmp.addr)
    result = adopt[SpatialEntityWatcher](tmp)

proc isSupported*(_: typedesc[SpatialEntityStore]): bool =
  ## Windows.Perception.Spatial.SpatialEntityStore.get_IsSupported
  withStatics("Windows.Perception.Spatial.SpatialEntityStore",
              ISpatialEntityStoreStatics, it):
    var tmp: bool
    it.call(ISpatialEntityStoreStatics_get_IsSupported, tmp.addr)
    result = tmp

proc tryGet*(_: typedesc[SpatialEntityStore], session: RemoteSystemSession): SpatialEntityStore =
  ## Windows.Perception.Spatial.SpatialEntityStore.TryGet
  withStatics("Windows.Perception.Spatial.SpatialEntityStore",
              ISpatialEntityStoreStatics, it):
    withIface(session.p, IRemoteSystemSession, p0):
      var tmp: pointer
      it.call(ISpatialEntityStoreStatics_TryGet, p0, tmp.addr)
      result = adopt[SpatialEntityStore](tmp)

proc entity*(self: SpatialEntityUpdatedEventArgs): SpatialEntity =
  ## Windows.Perception.Spatial.SpatialEntityUpdatedEventArgs.get_Entity
  withIface(self.p, ISpatialEntityUpdatedEventArgs, it):
    var tmp: pointer
    it.call(ISpatialEntityUpdatedEventArgs_get_Entity, tmp.addr)
    result = adopt[SpatialEntity](tmp)

proc status*(self: SpatialEntityWatcher): SpatialEntityWatcherStatus =
  ## Windows.Perception.Spatial.SpatialEntityWatcher.get_Status
  withIface(self.p, ISpatialEntityWatcher, it):
    var tmp: SpatialEntityWatcherStatus
    it.call(ISpatialEntityWatcher_get_Status, tmp.addr)
    result = tmp

proc onAdded*(self: SpatialEntityWatcher,
              handler: EventHandler[SpatialEntityWatcher, SpatialEntityAddedEventArgs]): EventRegistrationToken {.discardable.} =
  ## Windows.Perception.Spatial.SpatialEntityWatcher.add_Added
  ## The token is what `removeAdded` takes.
  withIface(self.p, ISpatialEntityWatcher, it):
    proc shim(a0: pointer, a1: pointer) =
      handler(borrow[SpatialEntityWatcher](a0),
              borrow[SpatialEntityAddedEventArgs](a1))
    let cb = newDelegate(IID_TypedEventHandler_2_SpatialEntityWatcher_SpatialEntityAddedEventArgs, shim, event = true)
    try:
      it.call(ISpatialEntityWatcher_add_Added, cb, result.addr)
    finally:
      release(cb)

proc removeAdded*(self: SpatialEntityWatcher, token: EventRegistrationToken) =
  withIface(self.p, ISpatialEntityWatcher, it):
    it.call(ISpatialEntityWatcher_remove_Added, token)

proc onUpdated*(self: SpatialEntityWatcher,
                handler: EventHandler[SpatialEntityWatcher, SpatialEntityUpdatedEventArgs]): EventRegistrationToken {.discardable.} =
  ## Windows.Perception.Spatial.SpatialEntityWatcher.add_Updated
  ## The token is what `removeUpdated` takes.
  withIface(self.p, ISpatialEntityWatcher, it):
    proc shim(a0: pointer, a1: pointer) =
      handler(borrow[SpatialEntityWatcher](a0),
              borrow[SpatialEntityUpdatedEventArgs](a1))
    let cb = newDelegate(IID_TypedEventHandler_2_SpatialEntityWatcher_SpatialEntityUpdatedEventArgs, shim, event = true)
    try:
      it.call(ISpatialEntityWatcher_add_Updated, cb, result.addr)
    finally:
      release(cb)

proc removeUpdated*(self: SpatialEntityWatcher, token: EventRegistrationToken) =
  withIface(self.p, ISpatialEntityWatcher, it):
    it.call(ISpatialEntityWatcher_remove_Updated, token)

proc onRemoved*(self: SpatialEntityWatcher,
                handler: EventHandler[SpatialEntityWatcher, SpatialEntityRemovedEventArgs]): EventRegistrationToken {.discardable.} =
  ## Windows.Perception.Spatial.SpatialEntityWatcher.add_Removed
  ## The token is what `removeRemoved` takes.
  withIface(self.p, ISpatialEntityWatcher, it):
    proc shim(a0: pointer, a1: pointer) =
      handler(borrow[SpatialEntityWatcher](a0),
              borrow[SpatialEntityRemovedEventArgs](a1))
    let cb = newDelegate(IID_TypedEventHandler_2_SpatialEntityWatcher_SpatialEntityRemovedEventArgs, shim, event = true)
    try:
      it.call(ISpatialEntityWatcher_add_Removed, cb, result.addr)
    finally:
      release(cb)

proc removeRemoved*(self: SpatialEntityWatcher, token: EventRegistrationToken) =
  withIface(self.p, ISpatialEntityWatcher, it):
    it.call(ISpatialEntityWatcher_remove_Removed, token)

proc onEnumerationCompleted*(self: SpatialEntityWatcher,
                             handler: EventHandler[SpatialEntityWatcher, WinRtObject]): EventRegistrationToken {.discardable.} =
  ## Windows.Perception.Spatial.SpatialEntityWatcher.add_EnumerationCompleted
  ## The token is what `removeEnumerationCompleted` takes.
  withIface(self.p, ISpatialEntityWatcher, it):
    proc shim(a0: pointer, a1: pointer) =
      handler(borrow[SpatialEntityWatcher](a0), borrow[WinRtObject](a1))
    let cb = newDelegate(IID_TypedEventHandler_2_SpatialEntityWatcher_Object, shim, event = true)
    try:
      it.call(ISpatialEntityWatcher_add_EnumerationCompleted, cb, result.addr)
    finally:
      release(cb)

proc removeEnumerationCompleted*(self: SpatialEntityWatcher, token: EventRegistrationToken) =
  withIface(self.p, ISpatialEntityWatcher, it):
    it.call(ISpatialEntityWatcher_remove_EnumerationCompleted, token)

proc start*(self: SpatialEntityWatcher) =
  ## Windows.Perception.Spatial.SpatialEntityWatcher.Start
  withIface(self.p, ISpatialEntityWatcher, it):
    it.call(ISpatialEntityWatcher_Start)

proc stop*(self: SpatialEntityWatcher) =
  ## Windows.Perception.Spatial.SpatialEntityWatcher.Stop
  withIface(self.p, ISpatialEntityWatcher, it):
    it.call(ISpatialEntityWatcher_Stop)

proc position*(self: SpatialLocation): Vector3 =
  ## Windows.Perception.Spatial.SpatialLocation.get_Position
  withIface(self.p, ISpatialLocation, it):
    var tmp: Vector3
    it.call(ISpatialLocation_get_Position, tmp.addr)
    result = tmp

proc orientation*(self: SpatialLocation): Quaternion =
  ## Windows.Perception.Spatial.SpatialLocation.get_Orientation
  withIface(self.p, ISpatialLocation, it):
    var tmp: Quaternion
    it.call(ISpatialLocation_get_Orientation, tmp.addr)
    result = tmp

proc absoluteLinearVelocity*(self: SpatialLocation): Vector3 =
  ## Windows.Perception.Spatial.SpatialLocation.get_AbsoluteLinearVelocity
  withIface(self.p, ISpatialLocation, it):
    var tmp: Vector3
    it.call(ISpatialLocation_get_AbsoluteLinearVelocity, tmp.addr)
    result = tmp

proc absoluteLinearAcceleration*(self: SpatialLocation): Vector3 =
  ## Windows.Perception.Spatial.SpatialLocation.get_AbsoluteLinearAcceleration
  withIface(self.p, ISpatialLocation, it):
    var tmp: Vector3
    it.call(ISpatialLocation_get_AbsoluteLinearAcceleration, tmp.addr)
    result = tmp

proc absoluteAngularVelocity*(self: SpatialLocation): Quaternion =
  ## Windows.Perception.Spatial.SpatialLocation.get_AbsoluteAngularVelocity
  withIface(self.p, ISpatialLocation, it):
    var tmp: Quaternion
    it.call(ISpatialLocation_get_AbsoluteAngularVelocity, tmp.addr)
    result = tmp

proc absoluteAngularAcceleration*(self: SpatialLocation): Quaternion =
  ## Windows.Perception.Spatial.SpatialLocation.get_AbsoluteAngularAcceleration
  withIface(self.p, ISpatialLocation, it):
    var tmp: Quaternion
    it.call(ISpatialLocation_get_AbsoluteAngularAcceleration, tmp.addr)
    result = tmp

proc absoluteAngularVelocityAxisAngle*(self: SpatialLocation): Vector3 =
  ## Windows.Perception.Spatial.SpatialLocation.get_AbsoluteAngularVelocityAxisAngle
  withIface(self.p, ISpatialLocation2, it):
    var tmp: Vector3
    it.call(ISpatialLocation2_get_AbsoluteAngularVelocityAxisAngle, tmp.addr)
    result = tmp

proc absoluteAngularAccelerationAxisAngle*(self: SpatialLocation): Vector3 =
  ## Windows.Perception.Spatial.SpatialLocation.get_AbsoluteAngularAccelerationAxisAngle
  withIface(self.p, ISpatialLocation2, it):
    var tmp: Vector3
    it.call(ISpatialLocation2_get_AbsoluteAngularAccelerationAxisAngle, tmp.addr)
    result = tmp

proc locatability*(self: SpatialLocator): SpatialLocatability =
  ## Windows.Perception.Spatial.SpatialLocator.get_Locatability
  withIface(self.p, ISpatialLocator, it):
    var tmp: SpatialLocatability
    it.call(ISpatialLocator_get_Locatability, tmp.addr)
    result = tmp

proc onLocatabilityChanged*(self: SpatialLocator,
                            handler: EventHandler[SpatialLocator, WinRtObject]): EventRegistrationToken {.discardable.} =
  ## Windows.Perception.Spatial.SpatialLocator.add_LocatabilityChanged
  ## The token is what `removeLocatabilityChanged` takes.
  withIface(self.p, ISpatialLocator, it):
    proc shim(a0: pointer, a1: pointer) =
      handler(borrow[SpatialLocator](a0), borrow[WinRtObject](a1))
    let cb = newDelegate(IID_TypedEventHandler_2_SpatialLocator_Object, shim, event = true)
    try:
      it.call(ISpatialLocator_add_LocatabilityChanged, cb, result.addr)
    finally:
      release(cb)

proc removeLocatabilityChanged*(self: SpatialLocator, token: EventRegistrationToken) =
  withIface(self.p, ISpatialLocator, it):
    it.call(ISpatialLocator_remove_LocatabilityChanged, token)

proc onPositionalTrackingDeactivating*(self: SpatialLocator,
                                       handler: EventHandler[SpatialLocator, SpatialLocatorPositionalTrackingDeactivatingEventArgs]): EventRegistrationToken {.discardable.} =
  ## Windows.Perception.Spatial.SpatialLocator.add_PositionalTrackingDeactivating
  ## The token is what `removePositionalTrackingDeactivating` takes.
  withIface(self.p, ISpatialLocator, it):
    proc shim(a0: pointer, a1: pointer) =
      handler(borrow[SpatialLocator](a0),
              borrow[SpatialLocatorPositionalTrackingDeactivatingEventArgs](a1))
    let cb = newDelegate(IID_TypedEventHandler_2_SpatialLocator_SpatialLocatorPositionalTrackingDeactivatingEventArgs, shim, event = true)
    try:
      it.call(ISpatialLocator_add_PositionalTrackingDeactivating, cb, result.addr)
    finally:
      release(cb)

proc removePositionalTrackingDeactivating*(self: SpatialLocator, token: EventRegistrationToken) =
  withIface(self.p, ISpatialLocator, it):
    it.call(ISpatialLocator_remove_PositionalTrackingDeactivating, token)

proc tryLocateAtTimestamp*(self: SpatialLocator, timestamp: PerceptionTimestamp,
                           coordinateSystem: SpatialCoordinateSystem): SpatialLocation =
  ## Windows.Perception.Spatial.SpatialLocator.TryLocateAtTimestamp
  withIface(self.p, ISpatialLocator, it):
    withIface(timestamp.p, IPerceptionTimestamp, p0):
      withIface(coordinateSystem.p, ISpatialCoordinateSystem, p1):
        var tmp: pointer
        it.call(ISpatialLocator_TryLocateAtTimestamp, p0, p1, tmp.addr)
        result = adopt[SpatialLocation](tmp)

proc createAttachedFrameOfReferenceAtCurrentHeading*(self: SpatialLocator): SpatialLocatorAttachedFrameOfReference =
  ## Windows.Perception.Spatial.SpatialLocator.CreateAttachedFrameOfReferenceAtCurrentHeading
  withIface(self.p, ISpatialLocator, it):
    var tmp: pointer
    it.call(ISpatialLocator_CreateAttachedFrameOfReferenceAtCurrentHeading,
            tmp.addr)
    result = adopt[SpatialLocatorAttachedFrameOfReference](tmp)

proc createAttachedFrameOfReferenceAtCurrentHeading*(self: SpatialLocator,
                                                     relativePosition: Vector3): SpatialLocatorAttachedFrameOfReference =
  ## Windows.Perception.Spatial.SpatialLocator.CreateAttachedFrameOfReferenceAtCurrentHeading
  withIface(self.p, ISpatialLocator, it):
    var tmp: pointer
    it.call(ISpatialLocator_CreateAttachedFrameOfReferenceAtCurrentHeading2,
            relativePosition, tmp.addr)
    result = adopt[SpatialLocatorAttachedFrameOfReference](tmp)

proc createAttachedFrameOfReferenceAtCurrentHeading*(self: SpatialLocator,
                                                     relativePosition: Vector3,
                                                     relativeOrientation: Quaternion): SpatialLocatorAttachedFrameOfReference =
  ## Windows.Perception.Spatial.SpatialLocator.CreateAttachedFrameOfReferenceAtCurrentHeading
  withIface(self.p, ISpatialLocator, it):
    var tmp: pointer
    it.call(ISpatialLocator_CreateAttachedFrameOfReferenceAtCurrentHeading3,
            relativePosition, relativeOrientation, tmp.addr)
    result = adopt[SpatialLocatorAttachedFrameOfReference](tmp)

proc createAttachedFrameOfReferenceAtCurrentHeading*(self: SpatialLocator,
                                                     relativePosition: Vector3,
                                                     relativeOrientation: Quaternion,
                                                     relativeHeadingInRadians: float64): SpatialLocatorAttachedFrameOfReference =
  ## Windows.Perception.Spatial.SpatialLocator.CreateAttachedFrameOfReferenceAtCurrentHeading
  withIface(self.p, ISpatialLocator, it):
    var tmp: pointer
    it.call(ISpatialLocator_CreateAttachedFrameOfReferenceAtCurrentHeading4,
            relativePosition, relativeOrientation, relativeHeadingInRadians,
            tmp.addr)
    result = adopt[SpatialLocatorAttachedFrameOfReference](tmp)

proc createStationaryFrameOfReferenceAtCurrentLocation*(self: SpatialLocator): SpatialStationaryFrameOfReference =
  ## Windows.Perception.Spatial.SpatialLocator.CreateStationaryFrameOfReferenceAtCurrentLocation
  withIface(self.p, ISpatialLocator, it):
    var tmp: pointer
    it.call(ISpatialLocator_CreateStationaryFrameOfReferenceAtCurrentLocation,
            tmp.addr)
    result = adopt[SpatialStationaryFrameOfReference](tmp)

proc createStationaryFrameOfReferenceAtCurrentLocation*(self: SpatialLocator,
                                                        relativePosition: Vector3): SpatialStationaryFrameOfReference =
  ## Windows.Perception.Spatial.SpatialLocator.CreateStationaryFrameOfReferenceAtCurrentLocation
  withIface(self.p, ISpatialLocator, it):
    var tmp: pointer
    it.call(ISpatialLocator_CreateStationaryFrameOfReferenceAtCurrentLocation2,
            relativePosition, tmp.addr)
    result = adopt[SpatialStationaryFrameOfReference](tmp)

proc createStationaryFrameOfReferenceAtCurrentLocation*(self: SpatialLocator,
                                                        relativePosition: Vector3,
                                                        relativeOrientation: Quaternion): SpatialStationaryFrameOfReference =
  ## Windows.Perception.Spatial.SpatialLocator.CreateStationaryFrameOfReferenceAtCurrentLocation
  withIface(self.p, ISpatialLocator, it):
    var tmp: pointer
    it.call(ISpatialLocator_CreateStationaryFrameOfReferenceAtCurrentLocation3,
            relativePosition, relativeOrientation, tmp.addr)
    result = adopt[SpatialStationaryFrameOfReference](tmp)

proc createStationaryFrameOfReferenceAtCurrentLocation*(self: SpatialLocator,
                                                        relativePosition: Vector3,
                                                        relativeOrientation: Quaternion,
                                                        relativeHeadingInRadians: float64): SpatialStationaryFrameOfReference =
  ## Windows.Perception.Spatial.SpatialLocator.CreateStationaryFrameOfReferenceAtCurrentLocation
  withIface(self.p, ISpatialLocator, it):
    var tmp: pointer
    it.call(ISpatialLocator_CreateStationaryFrameOfReferenceAtCurrentLocation4,
            relativePosition, relativeOrientation, relativeHeadingInRadians,
            tmp.addr)
    result = adopt[SpatialStationaryFrameOfReference](tmp)

proc getDefault*(_: typedesc[SpatialLocator]): SpatialLocator =
  ## Windows.Perception.Spatial.SpatialLocator.GetDefault
  withStatics("Windows.Perception.Spatial.SpatialLocator",
              ISpatialLocatorStatics, it):
    var tmp: pointer
    it.call(ISpatialLocatorStatics_GetDefault, tmp.addr)
    result = adopt[SpatialLocator](tmp)

proc relativePosition*(self: SpatialLocatorAttachedFrameOfReference): Vector3 =
  ## Windows.Perception.Spatial.SpatialLocatorAttachedFrameOfReference.get_RelativePosition
  withIface(self.p, ISpatialLocatorAttachedFrameOfReference, it):
    var tmp: Vector3
    it.call(ISpatialLocatorAttachedFrameOfReference_get_RelativePosition,
            tmp.addr)
    result = tmp

proc `relativePosition=`*(self: SpatialLocatorAttachedFrameOfReference,
                          value: Vector3) =
  ## Windows.Perception.Spatial.SpatialLocatorAttachedFrameOfReference.put_RelativePosition
  withIface(self.p, ISpatialLocatorAttachedFrameOfReference, it):
    it.call(ISpatialLocatorAttachedFrameOfReference_put_RelativePosition, value)

proc relativeOrientation*(self: SpatialLocatorAttachedFrameOfReference): Quaternion =
  ## Windows.Perception.Spatial.SpatialLocatorAttachedFrameOfReference.get_RelativeOrientation
  withIface(self.p, ISpatialLocatorAttachedFrameOfReference, it):
    var tmp: Quaternion
    it.call(ISpatialLocatorAttachedFrameOfReference_get_RelativeOrientation,
            tmp.addr)
    result = tmp

proc `relativeOrientation=`*(self: SpatialLocatorAttachedFrameOfReference,
                             value: Quaternion) =
  ## Windows.Perception.Spatial.SpatialLocatorAttachedFrameOfReference.put_RelativeOrientation
  withIface(self.p, ISpatialLocatorAttachedFrameOfReference, it):
    it.call(ISpatialLocatorAttachedFrameOfReference_put_RelativeOrientation,
            value)

proc adjustHeading*(self: SpatialLocatorAttachedFrameOfReference,
                    headingOffsetInRadians: float64) =
  ## Windows.Perception.Spatial.SpatialLocatorAttachedFrameOfReference.AdjustHeading
  withIface(self.p, ISpatialLocatorAttachedFrameOfReference, it):
    it.call(ISpatialLocatorAttachedFrameOfReference_AdjustHeading,
            headingOffsetInRadians)

proc getStationaryCoordinateSystemAtTimestamp*(self: SpatialLocatorAttachedFrameOfReference,
                                               timestamp: PerceptionTimestamp): SpatialCoordinateSystem =
  ## Windows.Perception.Spatial.SpatialLocatorAttachedFrameOfReference.GetStationaryCoordinateSystemAtTimestamp
  withIface(self.p, ISpatialLocatorAttachedFrameOfReference, it):
    withIface(timestamp.p, IPerceptionTimestamp, p0):
      var tmp: pointer
      it.call(ISpatialLocatorAttachedFrameOfReference_GetStationaryCoordinateSystemAtTimestamp,
              p0, tmp.addr)
      result = adopt[SpatialCoordinateSystem](tmp)

proc tryGetRelativeHeadingAtTimestamp*(self: SpatialLocatorAttachedFrameOfReference,
                                       timestamp: PerceptionTimestamp): Option[float64] =
  ## Windows.Perception.Spatial.SpatialLocatorAttachedFrameOfReference.TryGetRelativeHeadingAtTimestamp
  withIface(self.p, ISpatialLocatorAttachedFrameOfReference, it):
    withIface(timestamp.p, IPerceptionTimestamp, p0):
      var tmp: pointer
      it.call(ISpatialLocatorAttachedFrameOfReference_TryGetRelativeHeadingAtTimestamp,
              p0, tmp.addr)
      result = readReference[float64](tmp, IID_IReference_1_F8,
                                      "SpatialLocatorAttachedFrameOfReference.TryGetRelativeHeadingAtTimestamp")
      release(tmp)

proc canceled*(self: SpatialLocatorPositionalTrackingDeactivatingEventArgs): bool =
  ## Windows.Perception.Spatial.SpatialLocatorPositionalTrackingDeactivatingEventArgs.get_Canceled
  withIface(self.p, ISpatialLocatorPositionalTrackingDeactivatingEventArgs, it):
    var tmp: bool
    it.call(ISpatialLocatorPositionalTrackingDeactivatingEventArgs_get_Canceled,
            tmp.addr)
    result = tmp

proc `canceled=`*(self: SpatialLocatorPositionalTrackingDeactivatingEventArgs,
                  value: bool) =
  ## Windows.Perception.Spatial.SpatialLocatorPositionalTrackingDeactivatingEventArgs.put_Canceled
  withIface(self.p, ISpatialLocatorPositionalTrackingDeactivatingEventArgs, it):
    it.call(ISpatialLocatorPositionalTrackingDeactivatingEventArgs_put_Canceled,
            value)

proc coordinateSystem*(self: SpatialStageFrameOfReference): SpatialCoordinateSystem =
  ## Windows.Perception.Spatial.SpatialStageFrameOfReference.get_CoordinateSystem
  withIface(self.p, ISpatialStageFrameOfReference, it):
    var tmp: pointer
    it.call(ISpatialStageFrameOfReference_get_CoordinateSystem, tmp.addr)
    result = adopt[SpatialCoordinateSystem](tmp)

proc movementRange*(self: SpatialStageFrameOfReference): SpatialMovementRange =
  ## Windows.Perception.Spatial.SpatialStageFrameOfReference.get_MovementRange
  withIface(self.p, ISpatialStageFrameOfReference, it):
    var tmp: SpatialMovementRange
    it.call(ISpatialStageFrameOfReference_get_MovementRange, tmp.addr)
    result = tmp

proc lookDirectionRange*(self: SpatialStageFrameOfReference): SpatialLookDirectionRange =
  ## Windows.Perception.Spatial.SpatialStageFrameOfReference.get_LookDirectionRange
  withIface(self.p, ISpatialStageFrameOfReference, it):
    var tmp: SpatialLookDirectionRange
    it.call(ISpatialStageFrameOfReference_get_LookDirectionRange, tmp.addr)
    result = tmp

proc getCoordinateSystemAtCurrentLocation*(self: SpatialStageFrameOfReference,
                                           locator: SpatialLocator): SpatialCoordinateSystem =
  ## Windows.Perception.Spatial.SpatialStageFrameOfReference.GetCoordinateSystemAtCurrentLocation
  withIface(self.p, ISpatialStageFrameOfReference, it):
    withIface(locator.p, ISpatialLocator, p0):
      var tmp: pointer
      it.call(ISpatialStageFrameOfReference_GetCoordinateSystemAtCurrentLocation,
              p0, tmp.addr)
      result = adopt[SpatialCoordinateSystem](tmp)

proc tryGetMovementBounds*(self: SpatialStageFrameOfReference,
                           coordinateSystem: SpatialCoordinateSystem): seq[Vector3] =
  ## Windows.Perception.Spatial.SpatialStageFrameOfReference.TryGetMovementBounds
  withIface(self.p, ISpatialStageFrameOfReference, it):
    withIface(coordinateSystem.p, ISpatialCoordinateSystem, p0):
      var tmpSize: uint32
      var tmp: ptr Vector3
      it.call(ISpatialStageFrameOfReference_TryGetMovementBounds, p0,
              tmpSize.addr, tmp.addr)
      result = takeArray(tmpSize, tmp)

proc current*(_: typedesc[SpatialStageFrameOfReference]): SpatialStageFrameOfReference =
  ## Windows.Perception.Spatial.SpatialStageFrameOfReference.get_Current
  withStatics("Windows.Perception.Spatial.SpatialStageFrameOfReference",
              ISpatialStageFrameOfReferenceStatics, it):
    var tmp: pointer
    it.call(ISpatialStageFrameOfReferenceStatics_get_Current, tmp.addr)
    result = adopt[SpatialStageFrameOfReference](tmp)

proc onCurrentChanged*(_: typedesc[SpatialStageFrameOfReference],
                       handler: EventHandler[WinRtObject, WinRtObject]): EventRegistrationToken {.discardable.} =
  ## Windows.Perception.Spatial.SpatialStageFrameOfReference.add_CurrentChanged
  ## The token is what `removeCurrentChanged` takes.
  withStatics("Windows.Perception.Spatial.SpatialStageFrameOfReference",
              ISpatialStageFrameOfReferenceStatics, it):
    proc shim(a0: pointer, a1: pointer) =
      handler(borrow[WinRtObject](a0), borrow[WinRtObject](a1))
    let cb = newDelegate(IID_EventHandler_1_Object, shim, event = true)
    try:
      it.call(ISpatialStageFrameOfReferenceStatics_add_CurrentChanged, cb, result.addr)
    finally:
      release(cb)

proc removeCurrentChanged*(_: typedesc[SpatialStageFrameOfReference], token: EventRegistrationToken) =
  withStatics("Windows.Perception.Spatial.SpatialStageFrameOfReference",
              ISpatialStageFrameOfReferenceStatics, it):
    it.call(ISpatialStageFrameOfReferenceStatics_remove_CurrentChanged, token)

proc requestNewStageAsync*(_: typedesc[SpatialStageFrameOfReference]): Future[SpatialStageFrameOfReference] {.async.} =
  ## Windows.Perception.Spatial.SpatialStageFrameOfReference.RequestNewStageAsync
  var op: pointer
  withStatics("Windows.Perception.Spatial.SpatialStageFrameOfReference",
              ISpatialStageFrameOfReferenceStatics, it):
    it.call(ISpatialStageFrameOfReferenceStatics_RequestNewStageAsync, op.addr)
  result = adopt[SpatialStageFrameOfReference](await awaitObject(op,
                                                                 IID_IAsyncOperation_1_SpatialStageFrameOfReference,
                                                                 IID_AsyncOperationCompletedHandler_1_SpatialStageFrameOfReference,
                                                                 alPlain,
                                                                 "SpatialStageFrameOfReference.RequestNewStageAsync"))

proc coordinateSystem*(self: SpatialStationaryFrameOfReference): SpatialCoordinateSystem =
  ## Windows.Perception.Spatial.SpatialStationaryFrameOfReference.get_CoordinateSystem
  withIface(self.p, ISpatialStationaryFrameOfReference, it):
    var tmp: pointer
    it.call(ISpatialStationaryFrameOfReference_get_CoordinateSystem, tmp.addr)
    result = adopt[SpatialCoordinateSystem](tmp)

proc id*(self: SpatialSurfaceInfo): GUID =
  ## Windows.Perception.Spatial.Surfaces.SpatialSurfaceInfo.get_Id
  withIface(self.p, ISpatialSurfaceInfo, it):
    var tmp: GUID
    it.call(ISpatialSurfaceInfo_get_Id, tmp.addr)
    result = tmp

proc updateTime*(self: SpatialSurfaceInfo): DateTime =
  ## Windows.Perception.Spatial.Surfaces.SpatialSurfaceInfo.get_UpdateTime
  withIface(self.p, ISpatialSurfaceInfo, it):
    var tmp: DateTime
    it.call(ISpatialSurfaceInfo_get_UpdateTime, tmp.addr)
    result = tmp

proc tryGetBounds*(self: SpatialSurfaceInfo,
                   coordinateSystem: SpatialCoordinateSystem): Option[SpatialBoundingOrientedBox] =
  ## Windows.Perception.Spatial.Surfaces.SpatialSurfaceInfo.TryGetBounds
  withIface(self.p, ISpatialSurfaceInfo, it):
    withIface(coordinateSystem.p, ISpatialCoordinateSystem, p0):
      var tmp: pointer
      it.call(ISpatialSurfaceInfo_TryGetBounds, p0, tmp.addr)
      result = readReference[SpatialBoundingOrientedBox](tmp,
                                                         IID_IReference_1_SpatialBoundingOrientedBox,
                                                         "SpatialSurfaceInfo.TryGetBounds")
      release(tmp)

proc tryComputeLatestMeshAsync*(self: SpatialSurfaceInfo,
                                maxTrianglesPerCubicMeter: float64): Future[SpatialSurfaceMesh] {.async.} =
  ## Windows.Perception.Spatial.Surfaces.SpatialSurfaceInfo.TryComputeLatestMeshAsync
  var op: pointer
  withIface(self.p, ISpatialSurfaceInfo, it):
    it.call(ISpatialSurfaceInfo_TryComputeLatestMeshAsync,
            maxTrianglesPerCubicMeter, op.addr)
  result = adopt[SpatialSurfaceMesh](await awaitObject(op,
                                                       IID_IAsyncOperation_1_SpatialSurfaceMesh,
                                                       IID_AsyncOperationCompletedHandler_1_SpatialSurfaceMesh,
                                                       alPlain,
                                                       "SpatialSurfaceInfo.TryComputeLatestMeshAsync"))

proc tryComputeLatestMeshAsync*(self: SpatialSurfaceInfo,
                                maxTrianglesPerCubicMeter: float64,
                                options: SpatialSurfaceMeshOptions): Future[SpatialSurfaceMesh] {.async.} =
  ## Windows.Perception.Spatial.Surfaces.SpatialSurfaceInfo.TryComputeLatestMeshAsync
  var op: pointer
  withIface(self.p, ISpatialSurfaceInfo, it):
    withIface(options.p, ISpatialSurfaceMeshOptions, p1):
      it.call(ISpatialSurfaceInfo_TryComputeLatestMeshAsync2,
              maxTrianglesPerCubicMeter, p1, op.addr)
  result = adopt[SpatialSurfaceMesh](await awaitObject(op,
                                                       IID_IAsyncOperation_1_SpatialSurfaceMesh,
                                                       IID_AsyncOperationCompletedHandler_1_SpatialSurfaceMesh,
                                                       alPlain,
                                                       "SpatialSurfaceInfo.TryComputeLatestMeshAsync"))

proc surfaceInfo*(self: SpatialSurfaceMesh): SpatialSurfaceInfo =
  ## Windows.Perception.Spatial.Surfaces.SpatialSurfaceMesh.get_SurfaceInfo
  withIface(self.p, ISpatialSurfaceMesh, it):
    var tmp: pointer
    it.call(ISpatialSurfaceMesh_get_SurfaceInfo, tmp.addr)
    result = adopt[SpatialSurfaceInfo](tmp)

proc coordinateSystem*(self: SpatialSurfaceMesh): SpatialCoordinateSystem =
  ## Windows.Perception.Spatial.Surfaces.SpatialSurfaceMesh.get_CoordinateSystem
  withIface(self.p, ISpatialSurfaceMesh, it):
    var tmp: pointer
    it.call(ISpatialSurfaceMesh_get_CoordinateSystem, tmp.addr)
    result = adopt[SpatialCoordinateSystem](tmp)

proc triangleIndices*(self: SpatialSurfaceMesh): SpatialSurfaceMeshBuffer =
  ## Windows.Perception.Spatial.Surfaces.SpatialSurfaceMesh.get_TriangleIndices
  withIface(self.p, ISpatialSurfaceMesh, it):
    var tmp: pointer
    it.call(ISpatialSurfaceMesh_get_TriangleIndices, tmp.addr)
    result = adopt[SpatialSurfaceMeshBuffer](tmp)

proc vertexPositions*(self: SpatialSurfaceMesh): SpatialSurfaceMeshBuffer =
  ## Windows.Perception.Spatial.Surfaces.SpatialSurfaceMesh.get_VertexPositions
  withIface(self.p, ISpatialSurfaceMesh, it):
    var tmp: pointer
    it.call(ISpatialSurfaceMesh_get_VertexPositions, tmp.addr)
    result = adopt[SpatialSurfaceMeshBuffer](tmp)

proc vertexPositionScale*(self: SpatialSurfaceMesh): Vector3 =
  ## Windows.Perception.Spatial.Surfaces.SpatialSurfaceMesh.get_VertexPositionScale
  withIface(self.p, ISpatialSurfaceMesh, it):
    var tmp: Vector3
    it.call(ISpatialSurfaceMesh_get_VertexPositionScale, tmp.addr)
    result = tmp

proc vertexNormals*(self: SpatialSurfaceMesh): SpatialSurfaceMeshBuffer =
  ## Windows.Perception.Spatial.Surfaces.SpatialSurfaceMesh.get_VertexNormals
  withIface(self.p, ISpatialSurfaceMesh, it):
    var tmp: pointer
    it.call(ISpatialSurfaceMesh_get_VertexNormals, tmp.addr)
    result = adopt[SpatialSurfaceMeshBuffer](tmp)

proc format*(self: SpatialSurfaceMeshBuffer): DirectXPixelFormat =
  ## Windows.Perception.Spatial.Surfaces.SpatialSurfaceMeshBuffer.get_Format
  withIface(self.p, ISpatialSurfaceMeshBuffer, it):
    var tmp: DirectXPixelFormat
    it.call(ISpatialSurfaceMeshBuffer_get_Format, tmp.addr)
    result = tmp

proc stride*(self: SpatialSurfaceMeshBuffer): uint32 =
  ## Windows.Perception.Spatial.Surfaces.SpatialSurfaceMeshBuffer.get_Stride
  withIface(self.p, ISpatialSurfaceMeshBuffer, it):
    var tmp: uint32
    it.call(ISpatialSurfaceMeshBuffer_get_Stride, tmp.addr)
    result = tmp

proc elementCount*(self: SpatialSurfaceMeshBuffer): uint32 =
  ## Windows.Perception.Spatial.Surfaces.SpatialSurfaceMeshBuffer.get_ElementCount
  withIface(self.p, ISpatialSurfaceMeshBuffer, it):
    var tmp: uint32
    it.call(ISpatialSurfaceMeshBuffer_get_ElementCount, tmp.addr)
    result = tmp

proc data*(self: SpatialSurfaceMeshBuffer): Buffer =
  ## Windows.Perception.Spatial.Surfaces.SpatialSurfaceMeshBuffer.get_Data
  withIface(self.p, ISpatialSurfaceMeshBuffer, it):
    var tmp: pointer
    it.call(ISpatialSurfaceMeshBuffer_get_Data, tmp.addr)
    result = adopt[Buffer](tmp)

proc newSpatialSurfaceMeshOptions*(): SpatialSurfaceMeshOptions =
  ## Activate a `Windows.Perception.Spatial.Surfaces.SpatialSurfaceMeshOptions`.
  adopt[SpatialSurfaceMeshOptions](activateAs("Windows.Perception.Spatial.Surfaces.SpatialSurfaceMeshOptions", IID_ISpatialSurfaceMeshOptions))

proc vertexPositionFormat*(self: SpatialSurfaceMeshOptions): DirectXPixelFormat =
  ## Windows.Perception.Spatial.Surfaces.SpatialSurfaceMeshOptions.get_VertexPositionFormat
  withIface(self.p, ISpatialSurfaceMeshOptions, it):
    var tmp: DirectXPixelFormat
    it.call(ISpatialSurfaceMeshOptions_get_VertexPositionFormat, tmp.addr)
    result = tmp

proc `vertexPositionFormat=`*(self: SpatialSurfaceMeshOptions,
                              value: DirectXPixelFormat) =
  ## Windows.Perception.Spatial.Surfaces.SpatialSurfaceMeshOptions.put_VertexPositionFormat
  withIface(self.p, ISpatialSurfaceMeshOptions, it):
    it.call(ISpatialSurfaceMeshOptions_put_VertexPositionFormat, value)

proc triangleIndexFormat*(self: SpatialSurfaceMeshOptions): DirectXPixelFormat =
  ## Windows.Perception.Spatial.Surfaces.SpatialSurfaceMeshOptions.get_TriangleIndexFormat
  withIface(self.p, ISpatialSurfaceMeshOptions, it):
    var tmp: DirectXPixelFormat
    it.call(ISpatialSurfaceMeshOptions_get_TriangleIndexFormat, tmp.addr)
    result = tmp

proc `triangleIndexFormat=`*(self: SpatialSurfaceMeshOptions,
                             value: DirectXPixelFormat) =
  ## Windows.Perception.Spatial.Surfaces.SpatialSurfaceMeshOptions.put_TriangleIndexFormat
  withIface(self.p, ISpatialSurfaceMeshOptions, it):
    it.call(ISpatialSurfaceMeshOptions_put_TriangleIndexFormat, value)

proc vertexNormalFormat*(self: SpatialSurfaceMeshOptions): DirectXPixelFormat =
  ## Windows.Perception.Spatial.Surfaces.SpatialSurfaceMeshOptions.get_VertexNormalFormat
  withIface(self.p, ISpatialSurfaceMeshOptions, it):
    var tmp: DirectXPixelFormat
    it.call(ISpatialSurfaceMeshOptions_get_VertexNormalFormat, tmp.addr)
    result = tmp

proc `vertexNormalFormat=`*(self: SpatialSurfaceMeshOptions,
                            value: DirectXPixelFormat) =
  ## Windows.Perception.Spatial.Surfaces.SpatialSurfaceMeshOptions.put_VertexNormalFormat
  withIface(self.p, ISpatialSurfaceMeshOptions, it):
    it.call(ISpatialSurfaceMeshOptions_put_VertexNormalFormat, value)

proc includeVertexNormals*(self: SpatialSurfaceMeshOptions): bool =
  ## Windows.Perception.Spatial.Surfaces.SpatialSurfaceMeshOptions.get_IncludeVertexNormals
  withIface(self.p, ISpatialSurfaceMeshOptions, it):
    var tmp: bool
    it.call(ISpatialSurfaceMeshOptions_get_IncludeVertexNormals, tmp.addr)
    result = tmp

proc `includeVertexNormals=`*(self: SpatialSurfaceMeshOptions, value: bool) =
  ## Windows.Perception.Spatial.Surfaces.SpatialSurfaceMeshOptions.put_IncludeVertexNormals
  withIface(self.p, ISpatialSurfaceMeshOptions, it):
    it.call(ISpatialSurfaceMeshOptions_put_IncludeVertexNormals, value)

proc supportedVertexPositionFormats*(_: typedesc[SpatialSurfaceMeshOptions]): seq[DirectXPixelFormat] =
  ## Windows.Perception.Spatial.Surfaces.SpatialSurfaceMeshOptions.get_SupportedVertexPositionFormats
  withStatics("Windows.Perception.Spatial.Surfaces.SpatialSurfaceMeshOptions",
              ISpatialSurfaceMeshOptionsStatics, it):
    var tmp: pointer
    it.call(ISpatialSurfaceMeshOptionsStatics_get_SupportedVertexPositionFormats,
            tmp.addr)
    result = toSeq[DirectXPixelFormat](tmp, IID_IVectorView_1_DirectXPixelFormat)
    release(tmp)

proc supportedTriangleIndexFormats*(_: typedesc[SpatialSurfaceMeshOptions]): seq[DirectXPixelFormat] =
  ## Windows.Perception.Spatial.Surfaces.SpatialSurfaceMeshOptions.get_SupportedTriangleIndexFormats
  withStatics("Windows.Perception.Spatial.Surfaces.SpatialSurfaceMeshOptions",
              ISpatialSurfaceMeshOptionsStatics, it):
    var tmp: pointer
    it.call(ISpatialSurfaceMeshOptionsStatics_get_SupportedTriangleIndexFormats,
            tmp.addr)
    result = toSeq[DirectXPixelFormat](tmp, IID_IVectorView_1_DirectXPixelFormat)
    release(tmp)

proc supportedVertexNormalFormats*(_: typedesc[SpatialSurfaceMeshOptions]): seq[DirectXPixelFormat] =
  ## Windows.Perception.Spatial.Surfaces.SpatialSurfaceMeshOptions.get_SupportedVertexNormalFormats
  withStatics("Windows.Perception.Spatial.Surfaces.SpatialSurfaceMeshOptions",
              ISpatialSurfaceMeshOptionsStatics, it):
    var tmp: pointer
    it.call(ISpatialSurfaceMeshOptionsStatics_get_SupportedVertexNormalFormats,
            tmp.addr)
    result = toSeq[DirectXPixelFormat](tmp, IID_IVectorView_1_DirectXPixelFormat)
    release(tmp)

proc newSpatialSurfaceObserver*(): SpatialSurfaceObserver =
  ## Activate a `Windows.Perception.Spatial.Surfaces.SpatialSurfaceObserver`.
  adopt[SpatialSurfaceObserver](activateAs("Windows.Perception.Spatial.Surfaces.SpatialSurfaceObserver", IID_ISpatialSurfaceObserver))

proc getObservedSurfaces*(self: SpatialSurfaceObserver): Table[GUID, SpatialSurfaceInfo] =
  ## Windows.Perception.Spatial.Surfaces.SpatialSurfaceObserver.GetObservedSurfaces
  withIface(self.p, ISpatialSurfaceObserver, it):
    var tmp: pointer
    it.call(ISpatialSurfaceObserver_GetObservedSurfaces, tmp.addr)
    result = toTable[GUID, SpatialSurfaceInfo](tmp,
                                               IID_IIterable_1_IKeyValuePair_22,
                                               IID_IKeyValuePair_2_Guid_SpatialSurfaceInfo)
    release(tmp)

proc setBoundingVolume*(self: SpatialSurfaceObserver,
                        bounds: SpatialBoundingVolume) =
  ## Windows.Perception.Spatial.Surfaces.SpatialSurfaceObserver.SetBoundingVolume
  withIface(self.p, ISpatialSurfaceObserver, it):
    withIface(bounds.p, ISpatialBoundingVolume, p0):
      it.call(ISpatialSurfaceObserver_SetBoundingVolume, p0)

proc setBoundingVolumes*(self: SpatialSurfaceObserver,
                         bounds: seq[SpatialBoundingVolume]) =
  ## Windows.Perception.Spatial.Surfaces.SpatialSurfaceObserver.SetBoundingVolumes
  withIface(self.p, ISpatialSurfaceObserver, it):
    let p0 = asIterable[SpatialBoundingVolume](bounds, IID_IIterable_1_SpatialBoundingVolume,
                                                       IID_IVectorView_1_SpatialBoundingVolume,
                                                       IID_IIterator_1_SpatialBoundingVolume)
    defer: discard release(p0)
    it.call(ISpatialSurfaceObserver_SetBoundingVolumes, p0)

proc onObservedSurfacesChanged*(self: SpatialSurfaceObserver,
                                handler: EventHandler[SpatialSurfaceObserver, WinRtObject]): EventRegistrationToken {.discardable.} =
  ## Windows.Perception.Spatial.Surfaces.SpatialSurfaceObserver.add_ObservedSurfacesChanged
  ## The token is what `removeObservedSurfacesChanged` takes.
  withIface(self.p, ISpatialSurfaceObserver, it):
    proc shim(a0: pointer, a1: pointer) =
      handler(borrow[SpatialSurfaceObserver](a0), borrow[WinRtObject](a1))
    let cb = newDelegate(IID_TypedEventHandler_2_SpatialSurfaceObserver_Object, shim, event = true)
    try:
      it.call(ISpatialSurfaceObserver_add_ObservedSurfacesChanged, cb, result.addr)
    finally:
      release(cb)

proc removeObservedSurfacesChanged*(self: SpatialSurfaceObserver, token: EventRegistrationToken) =
  withIface(self.p, ISpatialSurfaceObserver, it):
    it.call(ISpatialSurfaceObserver_remove_ObservedSurfacesChanged, token)

proc requestAccessAsync*(_: typedesc[SpatialSurfaceObserver]): Future[SpatialPerceptionAccessStatus] {.async.} =
  ## Windows.Perception.Spatial.Surfaces.SpatialSurfaceObserver.RequestAccessAsync
  var op: pointer
  withStatics("Windows.Perception.Spatial.Surfaces.SpatialSurfaceObserver",
              ISpatialSurfaceObserverStatics, it):
    it.call(ISpatialSurfaceObserverStatics_RequestAccessAsync, op.addr)
  result = await awaitValue[SpatialPerceptionAccessStatus](op,
                                                           IID_IAsyncOperation_1_SpatialPerceptionAccessStatus,
                                                           IID_AsyncOperationCompletedHandler_1_SpatialPerceptionAccessStatus,
                                                           alPlain,
                                                           "SpatialSurfaceObserver.RequestAccessAsync")

proc isSupported*(_: typedesc[SpatialSurfaceObserver]): bool =
  ## Windows.Perception.Spatial.Surfaces.SpatialSurfaceObserver.IsSupported
  withStatics("Windows.Perception.Spatial.Surfaces.SpatialSurfaceObserver",
              ISpatialSurfaceObserverStatics2, it):
    var tmp: bool
    it.call(ISpatialSurfaceObserverStatics2_IsSupported, tmp.addr)
    result = tmp

